<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Intersection.ProjectPointsToBreps Method </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="ProjectPointsToBreps method" /><meta name="System.Keywords" content="Intersection.ProjectPointsToBreps method" /><meta name="Microsoft.Help.F1" content="Rhino.Geometry.Intersect.Intersection.ProjectPointsToBreps" /><meta name="Microsoft.Help.Id" content="M:Rhino.Geometry.Intersect.Intersection.ProjectPointsToBreps(System.Collections.Generic.IEnumerable{Rhino.Geometry.Brep},System.Collections.Generic.IEnumerable{Rhino.Geometry.Point3d},Rhino.Geometry.Vector3d,System.Double)" /><meta name="Description" content="Projects points onto breps." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Geometry.Intersect" /><meta name="file" content="M_Rhino_Geometry_Intersect_Intersection_ProjectPointsToBreps" /><meta name="guid" content="M_Rhino_Geometry_Intersect_Intersection_ProjectPointsToBreps" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.3.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon API<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="RhinoCommon API" tocid="roottoc">RhinoCommon API</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="Namespaces" tocid="R_Project_RhinoCommon">Namespaces</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Rhino_Geometry_Intersect.htm" title="Rhino.Geometry.Intersect" tocid="N_Rhino_Geometry_Intersect">Rhino.Geometry.Intersect</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Rhino_Geometry_Intersect_Intersection.htm" title="Intersection Class" tocid="T_Rhino_Geometry_Intersect_Intersection">Intersection Class</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Methods_T_Rhino_Geometry_Intersect_Intersection.htm" title="Intersection Methods" tocid="Methods_T_Rhino_Geometry_Intersect_Intersection">Intersection Methods</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_ArcArc.htm" title="ArcArc Method " tocid="M_Rhino_Geometry_Intersect_Intersection_ArcArc">ArcArc Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_BrepBrep.htm" title="BrepBrep Method " tocid="M_Rhino_Geometry_Intersect_Intersection_BrepBrep">BrepBrep Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_BrepPlane.htm" title="BrepPlane Method " tocid="M_Rhino_Geometry_Intersect_Intersection_BrepPlane">BrepPlane Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_BrepSurface.htm" title="BrepSurface Method " tocid="M_Rhino_Geometry_Intersect_Intersection_BrepSurface">BrepSurface Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_CircleCircle.htm" title="CircleCircle Method " tocid="M_Rhino_Geometry_Intersect_Intersection_CircleCircle">CircleCircle Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_Intersect_Intersection_CurveBrep.htm" title="CurveBrep Method " tocid="Overload_Rhino_Geometry_Intersect_Intersection_CurveBrep">CurveBrep Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_CurveBrepFace.htm" title="CurveBrepFace Method " tocid="M_Rhino_Geometry_Intersect_Intersection_CurveBrepFace">CurveBrepFace Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_CurveCurve.htm" title="CurveCurve Method " tocid="M_Rhino_Geometry_Intersect_Intersection_CurveCurve">CurveCurve Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_CurveCurveValidate.htm" title="CurveCurveValidate Method " tocid="M_Rhino_Geometry_Intersect_Intersection_CurveCurveValidate">CurveCurveValidate Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_CurveLine.htm" title="CurveLine Method " tocid="M_Rhino_Geometry_Intersect_Intersection_CurveLine">CurveLine Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_CurvePlane.htm" title="CurvePlane Method " tocid="M_Rhino_Geometry_Intersect_Intersection_CurvePlane">CurvePlane Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_CurveSelf.htm" title="CurveSelf Method " tocid="M_Rhino_Geometry_Intersect_Intersection_CurveSelf">CurveSelf Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_Intersect_Intersection_CurveSurface.htm" title="CurveSurface Method " tocid="Overload_Rhino_Geometry_Intersect_Intersection_CurveSurface">CurveSurface Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_Intersect_Intersection_CurveSurfaceValidate.htm" title="CurveSurfaceValidate Method " tocid="Overload_Rhino_Geometry_Intersect_Intersection_CurveSurfaceValidate">CurveSurfaceValidate Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_Intersect_Intersection_LineBox.htm" title="LineBox Method " tocid="Overload_Rhino_Geometry_Intersect_Intersection_LineBox">LineBox Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_LineCircle.htm" title="LineCircle Method " tocid="M_Rhino_Geometry_Intersect_Intersection_LineCircle">LineCircle Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_LineCylinder.htm" title="LineCylinder Method " tocid="M_Rhino_Geometry_Intersect_Intersection_LineCylinder">LineCylinder Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_Intersect_Intersection_LineLine.htm" title="LineLine Method " tocid="Overload_Rhino_Geometry_Intersect_Intersection_LineLine">LineLine Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_LinePlane.htm" title="LinePlane Method " tocid="M_Rhino_Geometry_Intersect_Intersection_LinePlane">LinePlane Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_LineSphere.htm" title="LineSphere Method " tocid="M_Rhino_Geometry_Intersect_Intersection_LineSphere">LineSphere Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_Intersect_Intersection_MeshLine.htm" title="MeshLine Method " tocid="Overload_Rhino_Geometry_Intersect_Intersection_MeshLine">MeshLine Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_MeshLineSorted.htm" title="MeshLineSorted Method " tocid="M_Rhino_Geometry_Intersect_Intersection_MeshLineSorted">MeshLineSorted Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_MeshMesh.htm" title="MeshMesh Method " tocid="M_Rhino_Geometry_Intersect_Intersection_MeshMesh">MeshMesh Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_MeshMeshAccurate.htm" title="MeshMeshAccurate Method " tocid="M_Rhino_Geometry_Intersect_Intersection_MeshMeshAccurate">MeshMeshAccurate Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_MeshMeshFast.htm" title="MeshMeshFast Method " tocid="M_Rhino_Geometry_Intersect_Intersection_MeshMeshFast">MeshMeshFast Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_Intersect_Intersection_MeshPlane.htm" title="MeshPlane Method " tocid="Overload_Rhino_Geometry_Intersect_Intersection_MeshPlane">MeshPlane Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_MeshPolyline.htm" title="MeshPolyline Method " tocid="M_Rhino_Geometry_Intersect_Intersection_MeshPolyline">MeshPolyline Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_MeshPolylineSorted.htm" title="MeshPolylineSorted Method " tocid="M_Rhino_Geometry_Intersect_Intersection_MeshPolylineSorted">MeshPolylineSorted Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_Intersect_Intersection_MeshRay.htm" title="MeshRay Method " tocid="Overload_Rhino_Geometry_Intersect_Intersection_MeshRay">MeshRay Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_PlaneCircle.htm" title="PlaneCircle Method " tocid="M_Rhino_Geometry_Intersect_Intersection_PlaneCircle">PlaneCircle Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_PlanePlane.htm" title="PlanePlane Method " tocid="M_Rhino_Geometry_Intersect_Intersection_PlanePlane">PlanePlane Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_PlanePlanePlane.htm" title="PlanePlanePlane Method " tocid="M_Rhino_Geometry_Intersect_Intersection_PlanePlanePlane">PlanePlanePlane Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_PlaneSphere.htm" title="PlaneSphere Method " tocid="M_Rhino_Geometry_Intersect_Intersection_PlaneSphere">PlaneSphere Method </a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_ProjectPointsToBreps.htm" title="ProjectPointsToBreps Method " tocid="M_Rhino_Geometry_Intersect_Intersection_ProjectPointsToBreps">ProjectPointsToBreps Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_ProjectPointsToBrepsEx.htm" title="ProjectPointsToBrepsEx Method " tocid="M_Rhino_Geometry_Intersect_Intersection_ProjectPointsToBrepsEx">ProjectPointsToBrepsEx Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_ProjectPointsToMeshes.htm" title="ProjectPointsToMeshes Method " tocid="M_Rhino_Geometry_Intersect_Intersection_ProjectPointsToMeshes">ProjectPointsToMeshes Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_ProjectPointsToMeshesEx.htm" title="ProjectPointsToMeshesEx Method " tocid="M_Rhino_Geometry_Intersect_Intersection_ProjectPointsToMeshesEx">ProjectPointsToMeshesEx Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_Intersect_Intersection_RayShoot.htm" title="RayShoot Method " tocid="Overload_Rhino_Geometry_Intersect_Intersection_RayShoot">RayShoot Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_SphereSphere.htm" title="SphereSphere Method " tocid="M_Rhino_Geometry_Intersect_Intersection_SphereSphere">SphereSphere Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Intersect_Intersection_SurfaceSurface.htm" title="SurfaceSurface Method " tocid="M_Rhino_Geometry_Intersect_Intersection_SurfaceSurface">SurfaceSurface Method </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn"><h1>Intersection<span id="LSTD24035B8_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD24035B8_0?cpp=::|nu=.");</script>ProjectPointsToBreps Method </h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            Projects points onto breps.
            </div><p> </p>
    <strong>Namespace:</strong> 
   <a href="N_Rhino_Geometry_Intersect.htm">Rhino.Geometry.Intersect</a><br />
    <strong>Assembly:</strong>
   RhinoCommon (in RhinoCommon.dll)<div class="since"><strong>Since:</strong> 5.0</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">static</span> <span class="identifier">Point3d</span>[] <span class="identifier">ProjectPointsToBreps</span>(
	<span class="identifier">IEnumerable</span>&lt;<span class="identifier">Brep</span>&gt; <span class="parameter">breps</span>,
	<span class="identifier">IEnumerable</span>&lt;<span class="identifier">Point3d</span>&gt; <span class="parameter">points</span>,
	<span class="identifier">Vector3d</span> <span class="parameter">direction</span>,
	<span class="identifier">double</span> <span class="parameter">tolerance</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Shared</span> <span class="keyword">Function</span> <span class="identifier">ProjectPointsToBreps</span> ( 
	<span class="parameter">breps</span> <span class="keyword">As</span> <span class="identifier">IEnumerable</span>(<span class="keyword">Of</span> <span class="identifier">Brep</span>),
	<span class="parameter">points</span> <span class="keyword">As</span> <span class="identifier">IEnumerable</span>(<span class="keyword">Of</span> <span class="identifier">Point3d</span>),
	<span class="parameter">direction</span> <span class="keyword">As</span> <span class="identifier">Vector3d</span>,
	<span class="parameter">tolerance</span> <span class="keyword">As</span> <span class="identifier">Double</span>
) <span class="keyword">As</span> <span class="identifier">Point3d</span>()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">breps</span></dt><dd>Type: <a href="https://docs.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1" target="_blank">System.Collections.Generic<span id="LSTD24035B8_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD24035B8_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>IEnumerable</a><span id="LSTD24035B8_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD24035B8_2?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script><a href="T_Rhino_Geometry_Brep.htm">Brep</a><span id="LSTD24035B8_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD24035B8_3?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script><br />The breps projection targets.</dd><dt><span class="parameter">points</span></dt><dd>Type: <a href="https://docs.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1" target="_blank">System.Collections.Generic<span id="LSTD24035B8_4"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD24035B8_4?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>IEnumerable</a><span id="LSTD24035B8_5"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD24035B8_5?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script><a href="T_Rhino_Geometry_Point3d.htm">Point3d</a><span id="LSTD24035B8_6"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD24035B8_6?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script><br />The points to project.</dd><dt><span class="parameter">direction</span></dt><dd>Type: <a href="T_Rhino_Geometry_Vector3d.htm">Rhino.Geometry<span id="LSTD24035B8_7"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD24035B8_7?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Vector3d</a><br />The direction to project.</dd><dt><span class="parameter">tolerance</span></dt><dd>Type: <a href="https://docs.microsoft.com/dotnet/api/system.double" target="_blank">System<span id="LSTD24035B8_8"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD24035B8_8?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Double</a><br />The tolerance used for intersections.</dd></dl><h4 class="subHeading">Return Value</h4>Type: <span id="LSTD24035B8_9"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD24035B8_9?cpp=array&lt;");</script><a href="T_Rhino_Geometry_Point3d.htm">Point3d</a><span id="LSTD24035B8_10"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD24035B8_10?cpp=&gt;|vb=()|nu=[]");</script><br />
            Array of projected points, or null in case of any error or invalid input.
            </div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBBBA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBBBA','cs','1','2');return false;">C#</a></div><div id="ID0EBBBBA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBBBA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBBBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBBBBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBBBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">using</span> Rhino;
<span class="highlight-keyword">using</span> Rhino.DocObjects;
<span class="highlight-keyword">using</span> Rhino.Input.Custom;
<span class="highlight-keyword">using</span> Rhino.Commands;
<span class="highlight-keyword">using</span> System.Collections.Generic;
<span class="highlight-keyword">using</span> Rhino.Geometry;
<span class="highlight-keyword">using</span> Rhino.Geometry.Intersect;

<span class="highlight-keyword">namespace</span> examples_cs
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">class</span> ProjectPointsToBrepsCommand : Command
  {
    <span class="highlight-keyword">public</span> <span class="highlight-keyword">override</span> <span class="highlight-keyword">string</span> EnglishName { <span class="highlight-keyword">get</span> { <span class="highlight-keyword">return</span> <span class="highlight-literal">"csProjectPtointsToBreps"</span>; } }

    <span class="highlight-keyword">protected</span> <span class="highlight-keyword">override</span> Result RunCommand(RhinoDoc doc, RunMode mode)
    {
      <span class="highlight-keyword">var</span> gs = <span class="highlight-keyword">new</span> GetObject();
      gs.SetCommandPrompt(<span class="highlight-literal">"select surface"</span>);
      gs.GeometryFilter = ObjectType.Surface | ObjectType.PolysrfFilter;
      gs.DisablePreSelect();
      gs.SubObjectSelect = <span class="highlight-keyword">false</span>;
      gs.Get();
      <span class="highlight-keyword">if</span> (gs.CommandResult() != Result.Success)
        <span class="highlight-keyword">return</span> gs.CommandResult();
      <span class="highlight-keyword">var</span> brep = gs.Object(<span class="highlight-number">0</span>).Brep();
      <span class="highlight-keyword">if</span> (brep == <span class="highlight-keyword">null</span>)
        <span class="highlight-keyword">return</span> Result.Failure;

      <span class="highlight-keyword">var</span> points = Intersection.ProjectPointsToBreps(
                   <span class="highlight-keyword">new</span> List&lt;Brep&gt; {brep}, <span class="highlight-comment">// brep on which to project</span>
                   <span class="highlight-keyword">new</span> List&lt;Point3d&gt; {<span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">0</span>, <span class="highlight-number">0</span>, <span class="highlight-number">0</span>), <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">3</span>,<span class="highlight-number">0</span>,<span class="highlight-number">3</span>), <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">-2</span>,<span class="highlight-number">0</span>,<span class="highlight-number">-2</span>)}, <span class="highlight-comment">// some random points to project</span>
                   <span class="highlight-keyword">new</span> Vector3d(<span class="highlight-number">0</span>, <span class="highlight-number">1</span>, <span class="highlight-number">0</span>), <span class="highlight-comment">// project on Y axis</span>
                   doc.ModelAbsoluteTolerance);

      <span class="highlight-keyword">if</span> (points != <span class="highlight-keyword">null</span> &amp;&amp; points.Length &gt; <span class="highlight-number">0</span>)
      {
        <span class="highlight-keyword">foreach</span> (<span class="highlight-keyword">var</span> point <span class="highlight-keyword">in</span> points)
        {
          doc.Objects.AddPoint(point);
        }
      }
      doc.Views.Redraw();
      <span class="highlight-keyword">return</span> Result.Success;
    }
  }
}</pre></div><div id="ID0EBBBBA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Imports</span> Rhino
<span class="highlight-keyword">Imports</span> Rhino.DocObjects
<span class="highlight-keyword">Imports</span> Rhino.Input.Custom
<span class="highlight-keyword">Imports</span> Rhino.Commands
<span class="highlight-keyword">Imports</span> System.Collections.Generic
<span class="highlight-keyword">Imports</span> Rhino.Geometry
<span class="highlight-keyword">Imports</span> Rhino.Geometry.Intersect

<span class="highlight-keyword">Namespace</span> examples_vb
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Class</span> ProjectPointsToBrepsCommand
    <span class="highlight-keyword">Inherits</span> Command
    <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">ReadOnly</span> <span class="highlight-keyword">Property</span> EnglishName() <span class="highlight-keyword">As</span> <span class="highlight-keyword">String</span>
      <span class="highlight-keyword">Get</span>
        <span class="highlight-keyword">Return</span> <span class="highlight-literal">"vbProjectPtointsToBreps"</span>
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">Get</span>
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Property</span>

    <span class="highlight-keyword">Protected</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">Function</span> RunCommand(doc <span class="highlight-keyword">As</span> RhinoDoc, mode <span class="highlight-keyword">As</span> RunMode) <span class="highlight-keyword">As</span> Result
      <span class="highlight-keyword">Dim</span> gs = <span class="highlight-keyword">New</span> GetObject()
      gs.SetCommandPrompt(<span class="highlight-literal">"select surface"</span>)
      gs.GeometryFilter = ObjectType.Surface <span class="highlight-keyword">Or</span> ObjectType.PolysrfFilter
      gs.DisablePreSelect()
      gs.SubObjectSelect = <span class="highlight-keyword">False</span>
      gs.[<span class="highlight-keyword">Get</span>]()
      <span class="highlight-keyword">If</span> gs.CommandResult() &lt;&gt; Result.Success <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> gs.CommandResult()
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
      <span class="highlight-keyword">Dim</span> brep = gs.[<span class="highlight-keyword">Object</span>](<span class="highlight-number">0</span>).Brep()
      <span class="highlight-keyword">If</span> brep <span class="highlight-keyword">Is</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> Result.Failure
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

      <span class="highlight-comment">' brep on which to project</span>
      <span class="highlight-comment">' some random points to project</span>
      <span class="highlight-comment">' project on Y axis</span>
      <span class="highlight-keyword">Dim</span> points = Intersection.ProjectPointsToBreps(<span class="highlight-keyword">New</span> List(<span class="highlight-keyword">Of</span> Brep)() From { _
        brep _
      }, <span class="highlight-keyword">New</span> List(<span class="highlight-keyword">Of</span> Point3d)() From { _
        <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">0</span>, <span class="highlight-number">0</span>, <span class="highlight-number">0</span>), _
        <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">3</span>, <span class="highlight-number">0</span>, <span class="highlight-number">3</span>), _
        <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">-2</span>, <span class="highlight-number">0</span>, <span class="highlight-number">-2</span>) _
      }, <span class="highlight-keyword">New</span> Vector3d(<span class="highlight-number">0</span>, <span class="highlight-number">1</span>, <span class="highlight-number">0</span>), doc.ModelAbsoluteTolerance)

      <span class="highlight-keyword">If</span> points <span class="highlight-keyword">IsNot</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">AndAlso</span> points.Length &gt; <span class="highlight-number">0</span> <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">For</span> <span class="highlight-keyword">Each</span> point <span class="highlight-keyword">As</span> Point3d <span class="highlight-keyword">In</span> points
          doc.Objects.AddPoint(point)
        <span class="highlight-keyword">Next</span>
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
      doc.Views.Redraw()
      <span class="highlight-keyword">Return</span> Result.Success
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Namespace</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBBBA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EAABBA_tab1" class="codeSnippetContainerTabSingle">Python</div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAABBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EAABBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAABBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">import</span> rhinoscriptsyntax <span class="highlight-keyword">as</span> rs
<span class="highlight-keyword">from</span> scriptcontext <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.Geometry <span class="highlight-keyword">import</span> *

<span class="highlight-keyword">def</span> RunCommand():
  srfid = rs.GetObject(<span class="highlight-literal">"select surface"</span>, rs.filter.surface | rs.filter.polysurface)
  <span class="highlight-keyword">if</span> <span class="highlight-keyword">not</span> srfid: <span class="highlight-keyword">return</span>
  brep = rs.coercebrep(srfid)
  <span class="highlight-keyword">if</span> <span class="highlight-keyword">not</span> brep: <span class="highlight-keyword">return</span>

  pts = Intersect.Intersection.ProjectPointsToBreps(
      [brep], <span class="highlight-comment"># brep on which to project</span>
      [Point3d(<span class="highlight-number">0</span>, <span class="highlight-number">0</span>, <span class="highlight-number">0</span>), Point3d(<span class="highlight-number">3</span>,<span class="highlight-number">0</span>,<span class="highlight-number">3</span>), Point3d(<span class="highlight-number">-2</span>,<span class="highlight-number">0</span>,<span class="highlight-number">-2</span>)], <span class="highlight-comment"># points to project</span>
      Vector3d(<span class="highlight-number">0</span>, <span class="highlight-number">1</span>, <span class="highlight-number">0</span>), <span class="highlight-comment"># project on Y axis</span>
      doc.ModelAbsoluteTolerance)

  <span class="highlight-keyword">if</span> pts != None <span class="highlight-keyword">and</span> pts.Length &gt; <span class="highlight-number">0</span>:
    <span class="highlight-keyword">for</span> pt <span class="highlight-keyword">in</span> pts:
      doc.Objects.AddPoint(pt)

  doc.Views.Redraw()

<span class="highlight-keyword">if</span> __name__ == <span class="highlight-literal">"__main__"</span>:
    RunCommand()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAABBA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_Geometry_Intersect_Intersection.htm">Intersection Class</a></div><div class="seeAlsoStyle"><a href="N_Rhino_Geometry_Intersect.htm">Rhino.Geometry.Intersect Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Rhino 7.18.22124.03000 (Last updated: 5/10/2022)<br />Copyright © 2009-2022 Robert McNeel &amp; Associates<p><a href="https://discourse.mcneel.com/c/rhino-developer" target="_blank">Report wishes and bugs at discourse.mcneel.com</a></p> </div></body></html>