<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>ObjectTable.AddLeader Method (Plane, IEnumerable(Point2d))</title><meta name="Language" content="en-us" /><meta name="Microsoft.Help.Id" content="M:Rhino.DocObjects.Tables.ObjectTable.AddLeader(Rhino.Geometry.Plane,System.Collections.Generic.IEnumerable{Rhino.Geometry.Point2d})" /><meta name="Description" content="summaryM:Rhino.DocObjects.Tables.ObjectTable.AddLeader(Rhino.Geometry.Plane,System.Collections.Generic.IEnumerable{Rhino.Geometry.Point2d})" /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.DocObjects.Tables" /><meta name="file" content="M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_3" /><meta name="guid" content="M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_3" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.3.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon API<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="RhinoCommon API" tocid="roottoc">RhinoCommon API</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="Namespaces" tocid="R_Project_RhinoCommon">Namespaces</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Rhino_DocObjects_Tables.htm" title="Rhino.DocObjects.Tables" tocid="N_Rhino_DocObjects_Tables">Rhino.DocObjects.Tables</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Rhino_DocObjects_Tables_ObjectTable.htm" title="ObjectTable Class" tocid="T_Rhino_DocObjects_Tables_ObjectTable">ObjectTable Class</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Methods_T_Rhino_DocObjects_Tables_ObjectTable.htm" title="ObjectTable Methods" tocid="Methods_T_Rhino_DocObjects_Tables_ObjectTable">ObjectTable Methods</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_DocObjects_Tables_ObjectTable_AddLeader.htm" title="AddLeader Method " tocid="Overload_Rhino_DocObjects_Tables_ObjectTable_AddLeader">AddLeader Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_Tables_ObjectTable_AddLeader.htm" title="AddLeader Method (Leader)" tocid="M_Rhino_DocObjects_Tables_ObjectTable_AddLeader">AddLeader Method (Leader)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_5.htm" title="AddLeader Method (IEnumerable(Point3d))" tocid="M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_5">AddLeader Method (IEnumerable(Point3d))</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_9.htm" title="AddLeader Method (String, IEnumerable(Point3d))" tocid="M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_9">AddLeader Method (String, IEnumerable(Point3d))</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_1.htm" title="AddLeader Method (Leader, ObjectAttributes)" tocid="M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_1">AddLeader Method (Leader, ObjectAttributes)</a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_3.htm" title="AddLeader Method (Plane, IEnumerable(Point2d))" tocid="M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_3">AddLeader Method (Plane, IEnumerable(Point2d))</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_6.htm" title="AddLeader Method (String, Plane, IEnumerable(Point2d))" tocid="M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_6">AddLeader Method (String, Plane, IEnumerable(Point2d))</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_4.htm" title="AddLeader Method (Plane, IEnumerable(Point2d), ObjectAttributes)" tocid="M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_4">AddLeader Method (Plane, IEnumerable(Point2d), ObjectAttributes)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_7.htm" title="AddLeader Method (String, Plane, IEnumerable(Point2d), ObjectAttributes)" tocid="M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_7">AddLeader Method (String, Plane, IEnumerable(Point2d), ObjectAttributes)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_2.htm" title="AddLeader Method (Leader, ObjectAttributes, HistoryRecord, Boolean)" tocid="M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_2">AddLeader Method (Leader, ObjectAttributes, HistoryRecord, Boolean)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_8.htm" title="AddLeader Method (String, Plane, IEnumerable(Point2d), ObjectAttributes, HistoryRecord, Boolean)" tocid="M_Rhino_DocObjects_Tables_ObjectTable_AddLeader_8">AddLeader Method (String, Plane, IEnumerable(Point2d), ObjectAttributes, HistoryRecord, Boolean)</a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn"><h1>ObjectTable<span id="LSTD419D7AC_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD419D7AC_0?cpp=::|nu=.");</script>AddLeader Method (Plane, IEnumerable<span id="LSTD419D7AC_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD419D7AC_1?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script>Point2d<span id="LSTD419D7AC_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD419D7AC_2?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script>)</h1></td></tr></table><span class="introStyle"></span> <div class="summary"><p style="color: #dc143c; font-size: 8.5pt; font-weight: bold;">[Missing &lt;summary&gt; documentation for "M:Rhino.DocObjects.Tables.ObjectTable.AddLeader(Rhino.Geometry.Plane,System.Collections.Generic.IEnumerable{Rhino.Geometry.Point2d})"]</p></div><p> </p>
    <strong>Namespace:</strong> 
   <a href="N_Rhino_DocObjects_Tables.htm">Rhino.DocObjects.Tables</a><br />
    <strong>Assembly:</strong>
   RhinoCommon (in RhinoCommon.dll)<div class="since"><strong>Since:</strong> 5.0</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">Guid</span> <span class="identifier">AddLeader</span>(
	<span class="identifier">Plane</span> <span class="parameter">plane</span>,
	<span class="identifier">IEnumerable</span>&lt;<span class="identifier">Point2d</span>&gt; <span class="parameter">points</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Function</span> <span class="identifier">AddLeader</span> ( 
	<span class="parameter">plane</span> <span class="keyword">As</span> <span class="identifier">Plane</span>,
	<span class="parameter">points</span> <span class="keyword">As</span> <span class="identifier">IEnumerable</span>(<span class="keyword">Of</span> <span class="identifier">Point2d</span>)
) <span class="keyword">As</span> <span class="identifier">Guid</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">plane</span></dt><dd>Type: <a href="T_Rhino_Geometry_Plane.htm">Rhino.Geometry<span id="LSTD419D7AC_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD419D7AC_3?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Plane</a><br /><p style="color: #dc143c; font-size: 8.5pt; font-weight: bold;">[Missing &lt;param name="plane"/&gt; documentation for "M:Rhino.DocObjects.Tables.ObjectTable.AddLeader(Rhino.Geometry.Plane,System.Collections.Generic.IEnumerable{Rhino.Geometry.Point2d})"]</p></dd><dt><span class="parameter">points</span></dt><dd>Type: <a href="https://docs.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1" target="_blank">System.Collections.Generic<span id="LSTD419D7AC_4"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD419D7AC_4?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>IEnumerable</a><span id="LSTD419D7AC_5"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD419D7AC_5?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script><a href="T_Rhino_Geometry_Point2d.htm">Point2d</a><span id="LSTD419D7AC_6"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD419D7AC_6?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script><br /><p style="color: #dc143c; font-size: 8.5pt; font-weight: bold;">[Missing &lt;param name="points"/&gt; documentation for "M:Rhino.DocObjects.Tables.ObjectTable.AddLeader(Rhino.Geometry.Plane,System.Collections.Generic.IEnumerable{Rhino.Geometry.Point2d})"]</p></dd></dl><h4 class="subHeading">Return Value</h4>Type: <a href="https://docs.microsoft.com/dotnet/api/system.guid" target="_blank">Guid</a><br /><p style="color: #dc143c; font-size: 8.5pt; font-weight: bold;">[Missing &lt;returns&gt; documentation for "M:Rhino.DocObjects.Tables.ObjectTable.AddLeader(Rhino.Geometry.Plane,System.Collections.Generic.IEnumerable{Rhino.Geometry.Point2d})"]</p></div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBFBA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBFBA','cs','1','2');return false;">C#</a></div><div id="ID0EBBFBA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBFBA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBFBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBBFBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBFBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">using</span> Rhino;
<span class="highlight-keyword">using</span> Rhino.Geometry;
<span class="highlight-keyword">using</span> Rhino.Commands;
<span class="highlight-keyword">using</span> System.Collections.Generic;
<span class="highlight-keyword">using</span> System.Linq;

<span class="highlight-keyword">namespace</span> examples_cs
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">class</span> LeaderCommand : Command
  {
    <span class="highlight-keyword">public</span> <span class="highlight-keyword">override</span> <span class="highlight-keyword">string</span> EnglishName { <span class="highlight-keyword">get</span> { <span class="highlight-keyword">return</span> <span class="highlight-literal">"csLeader"</span>; } }

    <span class="highlight-keyword">protected</span> <span class="highlight-keyword">override</span> Result RunCommand(RhinoDoc doc, RunMode mode)
    {
      <span class="highlight-keyword">var</span> points = <span class="highlight-keyword">new</span> Point3d[]
      {
        <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">1</span>, <span class="highlight-number">1</span>, <span class="highlight-number">0</span>),
        <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">5</span>, <span class="highlight-number">1</span>, <span class="highlight-number">0</span>),
        <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">5</span>, <span class="highlight-number">5</span>, <span class="highlight-number">0</span>),
        <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">9</span>, <span class="highlight-number">5</span>, <span class="highlight-number">0</span>)
      };

      <span class="highlight-keyword">var</span> xy_plane = Plane.WorldXY;

      <span class="highlight-keyword">var</span> points2d = <span class="highlight-keyword">new</span> List&lt;Point2d&gt;();
      <span class="highlight-keyword">foreach</span> (<span class="highlight-keyword">var</span> point3d <span class="highlight-keyword">in</span> points)
      {
        <span class="highlight-keyword">double</span> x, y;
        <span class="highlight-keyword">if</span> (xy_plane.ClosestParameter(point3d, <span class="highlight-keyword">out</span> x, <span class="highlight-keyword">out</span> y))
        {
          <span class="highlight-keyword">var</span> point2d = <span class="highlight-keyword">new</span> Point2d(x, y);
          <span class="highlight-keyword">if</span> (points2d.Count &lt; <span class="highlight-number">1</span> || point2d.DistanceTo(points2d.Last&lt;Point2d&gt;()) &gt; RhinoMath.SqrtEpsilon)
            points2d.Add(point2d);
        }
      }

      doc.Objects.AddLeader(xy_plane, points2d);
      doc.Views.Redraw();
      <span class="highlight-keyword">return</span> Result.Success;
    }
  }
}</pre></div><div id="ID0EBBFBA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Imports</span> Rhino
<span class="highlight-keyword">Imports</span> Rhino.Geometry
<span class="highlight-keyword">Imports</span> Rhino.Commands
<span class="highlight-keyword">Imports</span> System.Collections.Generic
<span class="highlight-keyword">Imports</span> System.Linq

<span class="highlight-keyword">Namespace</span> examples_vb
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Class</span> LeaderCommand
    <span class="highlight-keyword">Inherits</span> Command
    <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">ReadOnly</span> <span class="highlight-keyword">Property</span> EnglishName() <span class="highlight-keyword">As</span> <span class="highlight-keyword">String</span>
      <span class="highlight-keyword">Get</span>
        <span class="highlight-keyword">Return</span> <span class="highlight-literal">"vbLeader"</span>
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">Get</span>
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Property</span>

    <span class="highlight-keyword">Protected</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">Function</span> RunCommand(doc <span class="highlight-keyword">As</span> RhinoDoc, mode <span class="highlight-keyword">As</span> RunMode) <span class="highlight-keyword">As</span> Result
      <span class="highlight-keyword">Dim</span> points = <span class="highlight-keyword">New</span> List(<span class="highlight-keyword">Of</span> Point3d)() From { _
        <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">1</span>, <span class="highlight-number">1</span>, <span class="highlight-number">0</span>), _
        <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">5</span>, <span class="highlight-number">1</span>, <span class="highlight-number">0</span>), _
        <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">5</span>, <span class="highlight-number">5</span>, <span class="highlight-number">0</span>), _
        <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">9</span>, <span class="highlight-number">5</span>, <span class="highlight-number">0</span>) _
      }

      <span class="highlight-keyword">Dim</span> xyPlane = Plane.WorldXY

      <span class="highlight-keyword">Dim</span> points2d = <span class="highlight-keyword">New</span> List(<span class="highlight-keyword">Of</span> Point2d)()
      <span class="highlight-keyword">For</span> <span class="highlight-keyword">Each</span> point3d <span class="highlight-keyword">As</span> Point3d <span class="highlight-keyword">In</span> points
        <span class="highlight-keyword">Dim</span> x <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span>, y <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span>
        <span class="highlight-keyword">If</span> xyPlane.ClosestParameter(point3d, x, y) <span class="highlight-keyword">Then</span>
          <span class="highlight-keyword">Dim</span> point2d = <span class="highlight-keyword">New</span> Point2d(x, y)
          <span class="highlight-keyword">If</span> points2d.Count &lt; <span class="highlight-number">1</span> <span class="highlight-keyword">OrElse</span> point2d.DistanceTo(points2d.Last()) &gt; RhinoMath.SqrtEpsilon <span class="highlight-keyword">Then</span>
            points2d.Add(point2d)
          <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
        <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
      <span class="highlight-keyword">Next</span>

      doc.Objects.AddLeader(xyPlane, points2d)
      doc.Views.Redraw()
      <span class="highlight-keyword">Return</span> Result.Success
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Namespace</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBFBA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EAAFBA_tab1" class="codeSnippetContainerTabSingle">Python</div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAAFBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EAAFBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAAFBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">import</span> rhinoscriptsyntax <span class="highlight-keyword">as</span> rs

<span class="highlight-keyword">def</span> RunCommand():
  points = [(<span class="highlight-number">1</span>,<span class="highlight-number">1</span>,<span class="highlight-number">0</span>), (<span class="highlight-number">5</span>,<span class="highlight-number">1</span>,<span class="highlight-number">0</span>), (<span class="highlight-number">5</span>,<span class="highlight-number">5</span>,<span class="highlight-number">0</span>), (<span class="highlight-number">9</span>,<span class="highlight-number">5</span>,<span class="highlight-number">0</span>)]
  rs.AddLeader(points)

<span class="highlight-keyword">if</span> __name__ == <span class="highlight-literal">"__main__"</span>:
    RunCommand()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAAFBA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_DocObjects_Tables_ObjectTable.htm">ObjectTable Class</a></div><div class="seeAlsoStyle"><a href="Overload_Rhino_DocObjects_Tables_ObjectTable_AddLeader.htm">AddLeader Overload</a></div><div class="seeAlsoStyle"><a href="N_Rhino_DocObjects_Tables.htm">Rhino.DocObjects.Tables Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Rhino 7.18.22124.03000 (Last updated: 5/10/2022)<br />Copyright © 2009-2022 Robert McNeel &amp; Associates<p><a href="https://discourse.mcneel.com/c/rhino-developer" target="_blank">Report wishes and bugs at discourse.mcneel.com</a></p> </div></body></html>