<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Brep.CreateFromLoft Method (IEnumerable(Curve), Point3d, Point3d, Boolean, Boolean, BrepTrim, BrepTrim, LoftType, Boolean)</title><meta name="Language" content="en-us" /><meta name="Microsoft.Help.Id" content="M:Rhino.Geometry.Brep.CreateFromLoft(System.Collections.Generic.IEnumerable{Rhino.Geometry.Curve},Rhino.Geometry.Point3d,Rhino.Geometry.Point3d,System.Boolean,System.Boolean,Rhino.Geometry.BrepTrim,Rhino.Geometry.BrepTrim,Rhino.Geometry.LoftType,System.Boolean)" /><meta name="Description" content="Constructs one or more Breps by lofting through a set of curves, optionally matching start and end tangents of surfaces when first and/or last loft curves are surface edges" /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Geometry" /><meta name="file" content="M_Rhino_Geometry_Brep_CreateFromLoft_1" /><meta name="guid" content="M_Rhino_Geometry_Brep_CreateFromLoft_1" /><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.3.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon API<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="RhinoCommon API" tocid="roottoc">RhinoCommon API</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="Namespaces" tocid="R_Project_RhinoCommon">Namespaces</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Rhino_Geometry.htm" title="Rhino.Geometry" tocid="N_Rhino_Geometry">Rhino.Geometry</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Rhino_Geometry_Brep.htm" title="Brep Class" tocid="T_Rhino_Geometry_Brep">Brep Class</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Methods_T_Rhino_Geometry_Brep.htm" title="Brep Methods" tocid="Methods_T_Rhino_Geometry_Brep">Brep Methods</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_Brep_CreateFromLoft.htm" title="CreateFromLoft Method " tocid="Overload_Rhino_Geometry_Brep_CreateFromLoft">CreateFromLoft Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Brep_CreateFromLoft.htm" title="CreateFromLoft Method (IEnumerable(Curve), Point3d, Point3d, LoftType, Boolean)" tocid="M_Rhino_Geometry_Brep_CreateFromLoft">CreateFromLoft Method (IEnumerable(Curve), Point3d, Point3d, LoftType, Boolean)</a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_Brep_CreateFromLoft_1.htm" title="CreateFromLoft Method (IEnumerable(Curve), Point3d, Point3d, Boolean, Boolean, BrepTrim, BrepTrim, LoftType, Boolean)" tocid="M_Rhino_Geometry_Brep_CreateFromLoft_1">CreateFromLoft Method (IEnumerable(Curve), Point3d, Point3d, Boolean, Boolean, BrepTrim, BrepTrim, LoftType, Boolean)</a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn"><h1>Brep<span id="LST36DDC635_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST36DDC635_0?cpp=::|nu=.");</script>CreateFromLoft Method (IEnumerable<span id="LST36DDC635_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST36DDC635_1?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script>Curve<span id="LST36DDC635_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST36DDC635_2?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script>, Point3d, Point3d, Boolean, Boolean, BrepTrim, BrepTrim, LoftType, Boolean)</h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            Constructs one or more Breps by lofting through a set of curves, optionally matching start and
            end tangents of surfaces when first and/or last loft curves are surface edges
            </div><p> </p>
    <strong>Namespace:</strong> 
   <a href="N_Rhino_Geometry.htm">Rhino.Geometry</a><br />
    <strong>Assembly:</strong>
   RhinoCommon (in RhinoCommon.dll)<div class="since"><strong>Since:</strong> 7.0</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">static</span> <span class="identifier">Brep</span>[] <span class="identifier">CreateFromLoft</span>(
	<span class="identifier">IEnumerable</span>&lt;<span class="identifier">Curve</span>&gt; <span class="parameter">curves</span>,
	<span class="identifier">Point3d</span> <span class="parameter">start</span>,
	<span class="identifier">Point3d</span> <span class="parameter">end</span>,
	<span class="identifier">bool</span> <span class="parameter">StartTangent</span>,
	<span class="identifier">bool</span> <span class="parameter">EndTangent</span>,
	<span class="identifier">BrepTrim</span> <span class="parameter">StartTrim</span>,
	<span class="identifier">BrepTrim</span> <span class="parameter">EndTrim</span>,
	<span class="identifier">LoftType</span> <span class="parameter">loftType</span>,
	<span class="identifier">bool</span> <span class="parameter">closed</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Shared</span> <span class="keyword">Function</span> <span class="identifier">CreateFromLoft</span> ( 
	<span class="parameter">curves</span> <span class="keyword">As</span> <span class="identifier">IEnumerable</span>(<span class="keyword">Of</span> <span class="identifier">Curve</span>),
	<span class="parameter">start</span> <span class="keyword">As</span> <span class="identifier">Point3d</span>,
	<span class="parameter">end</span> <span class="keyword">As</span> <span class="identifier">Point3d</span>,
	<span class="parameter">StartTangent</span> <span class="keyword">As</span> <span class="identifier">Boolean</span>,
	<span class="parameter">EndTangent</span> <span class="keyword">As</span> <span class="identifier">Boolean</span>,
	<span class="parameter">StartTrim</span> <span class="keyword">As</span> <span class="identifier">BrepTrim</span>,
	<span class="parameter">EndTrim</span> <span class="keyword">As</span> <span class="identifier">BrepTrim</span>,
	<span class="parameter">loftType</span> <span class="keyword">As</span> <span class="identifier">LoftType</span>,
	<span class="parameter">closed</span> <span class="keyword">As</span> <span class="identifier">Boolean</span>
) <span class="keyword">As</span> <span class="identifier">Brep</span>()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">curves</span></dt><dd>Type: <a href="https://docs.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1" target="_blank">System.Collections.Generic<span id="LST36DDC635_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST36DDC635_3?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>IEnumerable</a><span id="LST36DDC635_4"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST36DDC635_4?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script><a href="T_Rhino_Geometry_Curve.htm">Curve</a><span id="LST36DDC635_5"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST36DDC635_5?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script><br />
            The curves to loft through. This function will not perform any curve sorting. You must pass in
            curves in the order you want them lofted. This function will not adjust the directions of open
            curves. Use Curve.DoDirectionsMatch and Curve.Reverse to adjust the directions of open curves.
            This function will not adjust the seams of closed curves. Use Curve.ChangeClosedCurveSeam to
            adjust the seam of closed curves.
            </dd><dt><span class="parameter">start</span></dt><dd>Type: <a href="T_Rhino_Geometry_Point3d.htm">Rhino.Geometry<span id="LST36DDC635_6"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST36DDC635_6?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Point3d</a><br />
            Optional starting point of loft. Use Point3d.Unset if you do not want to include a start point.
            "start" and "StartTangent" cannot both be true.
            </dd><dt><span class="parameter">end</span></dt><dd>Type: <a href="T_Rhino_Geometry_Point3d.htm">Rhino.Geometry<span id="LST36DDC635_7"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST36DDC635_7?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Point3d</a><br />
            Optional ending point of loft. Use Point3d.Unset if you do not want to include an end point.
            "end and "EndTangent" cannot both be true.
            </dd><dt><span class="parameter">StartTangent</span></dt><dd>Type: <a href="https://docs.microsoft.com/dotnet/api/system.boolean" target="_blank">System<span id="LST36DDC635_8"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST36DDC635_8?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Boolean</a><br />
            If StartTangent is true and the first loft curve is a surface edge, the loft will match the tangent 
            of the surface behind that edge.
            </dd><dt><span class="parameter">EndTangent</span></dt><dd>Type: <a href="https://docs.microsoft.com/dotnet/api/system.boolean" target="_blank">System<span id="LST36DDC635_9"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST36DDC635_9?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Boolean</a><br />
            If EndTangent is true and the first loft curve is a surface edge, the loft will match the tangent 
            of the surface behind that edge.
            </dd><dt><span class="parameter">StartTrim</span></dt><dd>Type: <a href="T_Rhino_Geometry_BrepTrim.htm">Rhino.Geometry<span id="LST36DDC635_10"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST36DDC635_10?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>BrepTrim</a><br />
            BrepTrim from the surface edge where start tangent is to be matched
            </dd><dt><span class="parameter">EndTrim</span></dt><dd>Type: <a href="T_Rhino_Geometry_BrepTrim.htm">Rhino.Geometry<span id="LST36DDC635_11"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST36DDC635_11?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>BrepTrim</a><br />
            BrepTrim from the surface edge where end tangent is to be matched
            </dd><dt><span class="parameter">loftType</span></dt><dd>Type: <a href="T_Rhino_Geometry_LoftType.htm">Rhino.Geometry<span id="LST36DDC635_12"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST36DDC635_12?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>LoftType</a><br />type of loft to perform.</dd><dt><span class="parameter">closed</span></dt><dd>Type: <a href="https://docs.microsoft.com/dotnet/api/system.boolean" target="_blank">System<span id="LST36DDC635_13"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST36DDC635_13?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Boolean</a><br />true if the last curve in this loft should be connected back to the first one.</dd></dl><h4 class="subHeading">Return Value</h4>Type: <span id="LST36DDC635_14"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST36DDC635_14?cpp=array&lt;");</script><a href="T_Rhino_Geometry_Brep.htm">Brep</a><span id="LST36DDC635_15"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST36DDC635_15?cpp=&gt;|vb=()|nu=[]");</script><br />
            Constructs a closed surface, continuing the surface past the last curve around to the
            first curve. Available when you have selected three shape curves.
            </div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID2RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_Geometry_Brep.htm">Brep Class</a></div><div class="seeAlsoStyle"><a href="Overload_Rhino_Geometry_Brep_CreateFromLoft.htm">CreateFromLoft Overload</a></div><div class="seeAlsoStyle"><a href="N_Rhino_Geometry.htm">Rhino.Geometry Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Rhino 7.16.22067.13000 (Last updated: 3/10/2022)<br />Copyright © 2009-2022 Robert McNeel &amp; Associates<p><a href="https://discourse.mcneel.com/c/rhino-developer" target="_blank">Report wishes and bugs at discourse.mcneel.com</a></p> </div></body></html>