<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Curve.Extend Method (CurveEnd, CurveExtensionStyle, IEnumerable(GeometryBase))</title><meta name="Language" content="en-us" /><meta name="Microsoft.Help.Id" content="M:Rhino.Geometry.Curve.Extend(Rhino.Geometry.CurveEnd,Rhino.Geometry.CurveExtensionStyle,System.Collections.Generic.IEnumerable{Rhino.Geometry.GeometryBase})" /><meta name="Description" content="Extends a curve until it intersects a collection of objects." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Geometry" /><meta name="file" content="M_Rhino_Geometry_Curve_Extend_1" /><meta name="guid" content="M_Rhino_Geometry_Curve_Extend_1" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-1.11.0.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon SDK<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino.htm" title="RhinoCommon SDK" tocid="roottoc">RhinoCommon SDK</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino_Geometry.htm" title="Rhino.Geometry" tocid="N_Rhino_Geometry">Rhino.Geometry</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="T_Rhino_Geometry_Curve.htm" title="Curve Class" tocid="T_Rhino_Geometry_Curve">Curve Class</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Methods_T_Rhino_Geometry_Curve.htm" title="Curve Methods" tocid="Methods_T_Rhino_Geometry_Curve">Curve Methods</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Overload_Rhino_Geometry_Curve_Extend.htm" title="Extend Method " tocid="Overload_Rhino_Geometry_Curve_Extend">Extend Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Curve_Extend_3.htm" title="Extend Method (Interval)" tocid="M_Rhino_Geometry_Curve_Extend_3">Extend Method (Interval)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Curve_Extend_4.htm" title="Extend Method (Double, Double)" tocid="M_Rhino_Geometry_Curve_Extend_4">Extend Method (Double, Double)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Curve_Extend.htm" title="Extend Method (CurveEnd, CurveExtensionStyle, Point3d)" tocid="M_Rhino_Geometry_Curve_Extend">Extend Method (CurveEnd, CurveExtensionStyle, Point3d)</a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Curve_Extend_1.htm" title="Extend Method (CurveEnd, CurveExtensionStyle, IEnumerable(GeometryBase))" tocid="M_Rhino_Geometry_Curve_Extend_1">Extend Method (CurveEnd, CurveExtensionStyle, IEnumerable(GeometryBase))</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Curve_Extend_2.htm" title="Extend Method (CurveEnd, Double, CurveExtensionStyle)" tocid="M_Rhino_Geometry_Curve_Extend_2">Extend Method (CurveEnd, Double, CurveExtensionStyle)</a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn">Curve<span id="LST1D70D895_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1D70D895_0?cpp=::|nu=.");</script>Extend Method (CurveEnd, CurveExtensionStyle, IEnumerable<span id="LST1D70D895_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1D70D895_1?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script>GeometryBase<span id="LST1D70D895_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1D70D895_2?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script>)</td></tr></table><span class="introStyle">Rhino for Mac 5.1</span><div class="summary">
            Extends a curve until it intersects a collection of objects.
            </div><p> </p><strong>Namespace:</strong> <a href="N_Rhino_Geometry.htm">Rhino.Geometry</a><br /><strong>Assembly:</strong> RhinoCommon (in RhinoCommon.dll) Version: 5.1.50000.0 (5.0.20693.0)<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">Curve</span> <span class="identifier">Extend</span>(
	<span class="identifier">CurveEnd</span> <span class="parameter">side</span>,
	<span class="identifier">CurveExtensionStyle</span> <span class="parameter">style</span>,
	<span class="identifier">IEnumerable</span>&lt;<span class="identifier">GeometryBase</span>&gt; <span class="parameter">geometry</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Function</span> <span class="identifier">Extend</span> ( 
	<span class="parameter">side</span> <span class="keyword">As</span> <span class="identifier">CurveEnd</span>,
	<span class="parameter">style</span> <span class="keyword">As</span> <span class="identifier">CurveExtensionStyle</span>,
	<span class="parameter">geometry</span> <span class="keyword">As</span> <span class="identifier">IEnumerable</span>(<span class="keyword">Of</span> <span class="identifier">GeometryBase</span>)
) <span class="keyword">As</span> <span class="identifier">Curve</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">side</span></dt><dd>Type: <a href="T_Rhino_Geometry_CurveEnd.htm">Rhino.Geometry<span id="LST1D70D895_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1D70D895_3?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>CurveEnd</a><br />The end of the curve to extend.</dd><dt><span class="parameter">style</span></dt><dd>Type: <a href="T_Rhino_Geometry_CurveExtensionStyle.htm">Rhino.Geometry<span id="LST1D70D895_4"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1D70D895_4?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>CurveExtensionStyle</a><br />The style or type of extension to use.</dd><dt><span class="parameter">geometry</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/9eekhta0" target="_blank">System.Collections.Generic<span id="LST1D70D895_5"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1D70D895_5?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>IEnumerable</a><span id="LST1D70D895_6"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1D70D895_6?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script><a href="T_Rhino_Geometry_GeometryBase.htm">GeometryBase</a><span id="LST1D70D895_7"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1D70D895_7?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script><br />A collection of objects. Allowable object types are Curve, Surface, Brep.</dd></dl><h4 class="subHeading">Return Value</h4>Type: <a href="T_Rhino_Geometry_Curve.htm">Curve</a><br />New extended curve result on success, null on failure.</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBABA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','cs','1','2');return false;">C#</a></div><div id="ID0EBBABA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBBABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">using</span> System.Linq;
<span class="highlight-keyword">using</span> Rhino;
<span class="highlight-keyword">using</span> Rhino.Geometry;
<span class="highlight-keyword">using</span> Rhino.DocObjects;
<span class="highlight-keyword">using</span> Rhino.Commands;
<span class="highlight-keyword">using</span> Rhino.Input;
<span class="highlight-keyword">using</span> Rhino.Input.Custom;

<span class="highlight-keyword">namespace</span> examples_cs
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">class</span> ExtendCurveCommand : Command
  {
    <span class="highlight-keyword">public</span> <span class="highlight-keyword">override</span> <span class="highlight-keyword">string</span> EnglishName { <span class="highlight-keyword">get</span> { <span class="highlight-keyword">return</span> <span class="highlight-literal">"csExtendCurve"</span>; } }

    <span class="highlight-keyword">protected</span> <span class="highlight-keyword">override</span> Result RunCommand(RhinoDoc doc, RunMode mode)
    {
      ObjRef[] boundary_obj_refs;
      <span class="highlight-keyword">var</span> rc = RhinoGet.GetMultipleObjects(<span class="highlight-literal">"Select boundary objects"</span>, <span class="highlight-keyword">false</span>, ObjectType.AnyObject, <span class="highlight-keyword">out</span> boundary_obj_refs);
      <span class="highlight-keyword">if</span> (rc != Result.Success)
        <span class="highlight-keyword">return</span> rc;
      <span class="highlight-keyword">if</span> (boundary_obj_refs == <span class="highlight-keyword">null</span> || boundary_obj_refs.Length == <span class="highlight-number">0</span>)
        <span class="highlight-keyword">return</span> Result.Nothing;

      <span class="highlight-keyword">var</span> gc = <span class="highlight-keyword">new</span> GetObject();
      gc.SetCommandPrompt(<span class="highlight-literal">"Select curve to extend"</span>);
      gc.GeometryFilter = ObjectType.Curve;
      gc.GeometryAttributeFilter = GeometryAttributeFilter.OpenCurve;
      gc.Get();
      <span class="highlight-keyword">if</span> (gc.CommandResult() != Result.Success)
        <span class="highlight-keyword">return</span> gc.CommandResult();
      <span class="highlight-keyword">var</span> curve_obj_ref = gc.Object(<span class="highlight-number">0</span>);

      <span class="highlight-keyword">var</span> curve = curve_obj_ref.Curve();
      <span class="highlight-keyword">if</span> (curve == <span class="highlight-keyword">null</span>) <span class="highlight-keyword">return</span> Result.Failure;
      <span class="highlight-keyword">double</span> t;
      <span class="highlight-keyword">if</span> (!curve.ClosestPoint(curve_obj_ref.SelectionPoint(), <span class="highlight-keyword">out</span> t))
        <span class="highlight-keyword">return</span> Result.Failure;
      <span class="highlight-keyword">var</span> curve_end = t &lt;= curve.Domain.Mid ? CurveEnd.Start : CurveEnd.End;

      <span class="highlight-keyword">var</span> geometry = boundary_obj_refs.Select(obj=&gt; obj.Geometry());
      <span class="highlight-keyword">var</span> extended_curve = curve.Extend(curve_end, CurveExtensionStyle.Line, geometry);
      <span class="highlight-keyword">if</span> (extended_curve != <span class="highlight-keyword">null</span> &amp;&amp; extended_curve.IsValid)
      {
        <span class="highlight-keyword">if</span> (!doc.Objects.Replace(curve_obj_ref.ObjectId, extended_curve))
          <span class="highlight-keyword">return</span> Result.Failure;
        doc.Views.Redraw();
      }
      <span class="highlight-keyword">else</span>
      {
        RhinoApp.WriteLine(<span class="highlight-literal">"No boundary object was intersected so curve not extended"</span>);
        <span class="highlight-keyword">return</span> Result.Nothing;
      }

      <span class="highlight-keyword">return</span> Result.Success;
    }
  }
}</pre></div><div id="ID0EBBABA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Imports</span> System.Linq
<span class="highlight-keyword">Imports</span> Rhino
<span class="highlight-keyword">Imports</span> Rhino.Geometry
<span class="highlight-keyword">Imports</span> Rhino.DocObjects
<span class="highlight-keyword">Imports</span> Rhino.Commands
<span class="highlight-keyword">Imports</span> Rhino.Input
<span class="highlight-keyword">Imports</span> Rhino.Input.Custom

<span class="highlight-keyword">Namespace</span> examples_vb
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Class</span> ExtendCurveCommand
    <span class="highlight-keyword">Inherits</span> Command
    <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">ReadOnly</span> <span class="highlight-keyword">Property</span> EnglishName() <span class="highlight-keyword">As</span> <span class="highlight-keyword">String</span>
      <span class="highlight-keyword">Get</span>
        <span class="highlight-keyword">Return</span> <span class="highlight-literal">"vbExtendCurve"</span>
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">Get</span>
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Property</span>

    <span class="highlight-keyword">Protected</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">Function</span> RunCommand(doc <span class="highlight-keyword">As</span> RhinoDoc, mode <span class="highlight-keyword">As</span> RunMode) <span class="highlight-keyword">As</span> Result
      <span class="highlight-keyword">Dim</span> boundary_obj_refs <span class="highlight-keyword">As</span> ObjRef() = <span class="highlight-keyword">Nothing</span>
      <span class="highlight-keyword">Dim</span> rc = RhinoGet.GetMultipleObjects(<span class="highlight-literal">"Select boundary objects"</span>, <span class="highlight-keyword">False</span>, ObjectType.AnyObject, boundary_obj_refs)
      <span class="highlight-keyword">If</span> rc &lt;&gt; Result.Success <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> rc
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
      <span class="highlight-keyword">If</span> boundary_obj_refs <span class="highlight-keyword">Is</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">OrElse</span> boundary_obj_refs.Length = <span class="highlight-number">0</span> <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> Result.[<span class="highlight-keyword">Nothing</span>]
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

      <span class="highlight-keyword">Dim</span> gc = <span class="highlight-keyword">New</span> GetObject()
      gc.SetCommandPrompt(<span class="highlight-literal">"Select curve to extend"</span>)
      gc.GeometryFilter = ObjectType.Curve
      gc.GeometryAttributeFilter = GeometryAttributeFilter.OpenCurve
      gc.[<span class="highlight-keyword">Get</span>]()
      <span class="highlight-keyword">If</span> gc.CommandResult() &lt;&gt; Result.Success <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> gc.CommandResult()
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
      <span class="highlight-keyword">Dim</span> curve_obj_ref = gc.[<span class="highlight-keyword">Object</span>](<span class="highlight-number">0</span>)

      <span class="highlight-keyword">Dim</span> curve = curve_obj_ref.Curve()
      <span class="highlight-keyword">If</span> curve <span class="highlight-keyword">Is</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> Result.Failure
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
      <span class="highlight-keyword">Dim</span> t <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span>
      <span class="highlight-keyword">If</span> <span class="highlight-keyword">Not</span> curve.ClosestPoint(curve_obj_ref.SelectionPoint(), t) <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> Result.Failure
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
      <span class="highlight-keyword">Dim</span> curve_end = <span class="highlight-keyword">If</span>(t &lt;= curve.Domain.Mid, CurveEnd.Start, CurveEnd.[<span class="highlight-keyword">End</span>])

      <span class="highlight-keyword">Dim</span> geometry = boundary_obj_refs.[<span class="highlight-keyword">Select</span>](<span class="highlight-keyword">Function</span>(obj) obj.Geometry())
      <span class="highlight-keyword">Dim</span> extended_curve = curve.Extend(curve_end, CurveExtensionStyle.Line, geometry)
      <span class="highlight-keyword">If</span> extended_curve <span class="highlight-keyword">IsNot</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">AndAlso</span> extended_curve.IsValid <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">If</span> <span class="highlight-keyword">Not</span> doc.Objects.Replace(curve_obj_ref.ObjectId, extended_curve) <span class="highlight-keyword">Then</span>
          <span class="highlight-keyword">Return</span> Result.Failure
        <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
        doc.Views.Redraw()
      <span class="highlight-keyword">Else</span>
        RhinoApp.WriteLine(<span class="highlight-literal">"No boundary object was intersected so curve not extended"</span>)
        <span class="highlight-keyword">Return</span> Result.[<span class="highlight-keyword">Nothing</span>]
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

      <span class="highlight-keyword">Return</span> Result.Success
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Namespace</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBABA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAAABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EAAABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAAABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">from</span> Rhino <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.Geometry <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.DocObjects <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.Commands <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.Input <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.Input.Custom <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> scriptcontext <span class="highlight-keyword">import</span> doc

<span class="highlight-keyword">def</span> RunCommand():

  rc, boundary_obj_refs = RhinoGet.GetMultipleObjects(<span class="highlight-literal">"Select boundary objects"</span>, False, ObjectType.AnyObject)
  <span class="highlight-keyword">if</span> rc &lt;&gt; Result.Success:
    <span class="highlight-keyword">return</span> rc
  <span class="highlight-keyword">if</span> boundary_obj_refs == None <span class="highlight-keyword">or</span> boundary_obj_refs.Length == <span class="highlight-number">0</span>:
    <span class="highlight-keyword">return</span> Result.Nothing

  gc = GetObject()
  gc.SetCommandPrompt(<span class="highlight-literal">"Select curve to extend"</span>)
  gc.GeometryFilter = ObjectType.Curve
  gc.GeometryAttributeFilter = GeometryAttributeFilter.OpenCurve
  gc.Get()
  <span class="highlight-keyword">if</span> gc.CommandResult() &lt;&gt; Result.Success:
    <span class="highlight-keyword">return</span> gc.CommandResult()
  curve_obj_ref = gc.Object(<span class="highlight-number">0</span>)

  curve = curve_obj_ref.Curve()
  <span class="highlight-keyword">if</span> curve == None: <span class="highlight-keyword">return</span> Result.Failure
  b, t = curve.ClosestPoint(curve_obj_ref.SelectionPoint())
  <span class="highlight-keyword">if</span> <span class="highlight-keyword">not</span> b: <span class="highlight-keyword">return</span> Result.Failure
  curve_end = CurveEnd.Start <span class="highlight-keyword">if</span> t &lt;= curve.Domain.Mid <span class="highlight-keyword">else</span> CurveEnd.End

  geometry = [obj.Geometry() <span class="highlight-keyword">for</span> obj <span class="highlight-keyword">in</span> boundary_obj_refs]
  extended_curve = curve.Extend(curve_end, CurveExtensionStyle.Line, geometry)
  <span class="highlight-keyword">if</span> extended_curve &lt;&gt; None <span class="highlight-keyword">and</span> extended_curve.IsValid:
    <span class="highlight-keyword">if</span> <span class="highlight-keyword">not</span> doc.Objects.Replace(curve_obj_ref.ObjectId, extended_curve):
      <span class="highlight-keyword">return</span> Result.Failure
    doc.Views.Redraw()
    <span class="highlight-keyword">return</span> Result.Success
  <span class="highlight-keyword">else</span>:
    RhinoApp.WriteLine(<span class="highlight-literal">"No boundary object was intersected so curve not extended"</span>)
    <span class="highlight-keyword">return</span> Result.Nothing

<span class="highlight-keyword">if</span> __name__ == <span class="highlight-literal">"__main__"</span>:
  RunCommand()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAAABA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_Geometry_Curve.htm">Curve Class</a></div><div class="seeAlsoStyle"><a href="Overload_Rhino_Geometry_Curve_Extend.htm">Extend Overload</a></div><div class="seeAlsoStyle"><a href="N_Rhino_Geometry.htm">Rhino.Geometry Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Updated 4 October 2015 - Robert McNeel and Associates<p><a href="http://discourse.mcneel.com/" target="_blank">Report wishes and bugs: http://discourse.mcneel.com/</a></p><div class="feedbackLink">Send comments on this topic to
        <a id="HT_MailLink" href="mailto:steve%40mcneel.com?Subject=RhinoCommon SDK">steve@mcneel.com</a></div><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title + "\u0026body=" + encodeURIComponent("Your feedback is used to improve the documentation and the product. Your e-mail address will not be used for any other purpose and is disposed of after the issue you report is resolved. While working to resolve the issue that you report, you may be contacted via e-mail to get further details or clarification on the feedback you sent. After the issue you report has been addressed, you may receive an e-mail to let you know that your feedback has been addressed.");
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script> </div></body></html>