<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>ObjectTable.AddClippingPlane Method (Plane, Double, Double, Guid)</title><meta name="Language" content="en-us" /><meta name="Microsoft.Help.Id" content="M:Rhino.DocObjects.Tables.ObjectTable.AddClippingPlane(Rhino.Geometry.Plane,System.Double,System.Double,System.Guid)" /><meta name="Description" content="Adds a clipping plane object to Rhino." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.DocObjects.Tables" /><meta name="file" content="M_Rhino_DocObjects_Tables_ObjectTable_AddClippingPlane_3" /><meta name="guid" content="M_Rhino_DocObjects_Tables_ObjectTable_AddClippingPlane_3" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-1.11.0.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon SDK<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino.htm" title="RhinoCommon SDK" tocid="roottoc">RhinoCommon SDK</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino_DocObjects_Tables.htm" title="Rhino.DocObjects.Tables" tocid="N_Rhino_DocObjects_Tables">Rhino.DocObjects.Tables</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="T_Rhino_DocObjects_Tables_ObjectTable.htm" title="ObjectTable Class" tocid="T_Rhino_DocObjects_Tables_ObjectTable">ObjectTable Class</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Methods_T_Rhino_DocObjects_Tables_ObjectTable.htm" title="ObjectTable Methods" tocid="Methods_T_Rhino_DocObjects_Tables_ObjectTable">ObjectTable Methods</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Overload_Rhino_DocObjects_Tables_ObjectTable_AddClippingPlane.htm" title="AddClippingPlane Method " tocid="Overload_Rhino_DocObjects_Tables_ObjectTable_AddClippingPlane">AddClippingPlane Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_DocObjects_Tables_ObjectTable_AddClippingPlane.htm" title="AddClippingPlane Method (Plane, Double, Double, IEnumerable(Guid))" tocid="M_Rhino_DocObjects_Tables_ObjectTable_AddClippingPlane">AddClippingPlane Method (Plane, Double, Double, IEnumerable(Guid))</a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_DocObjects_Tables_ObjectTable_AddClippingPlane_3.htm" title="AddClippingPlane Method (Plane, Double, Double, Guid)" tocid="M_Rhino_DocObjects_Tables_ObjectTable_AddClippingPlane_3">AddClippingPlane Method (Plane, Double, Double, Guid)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_DocObjects_Tables_ObjectTable_AddClippingPlane_1.htm" title="AddClippingPlane Method (Plane, Double, Double, IEnumerable(Guid), ObjectAttributes)" tocid="M_Rhino_DocObjects_Tables_ObjectTable_AddClippingPlane_1">AddClippingPlane Method (Plane, Double, Double, IEnumerable(Guid), ObjectAttributes)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_DocObjects_Tables_ObjectTable_AddClippingPlane_2.htm" title="AddClippingPlane Method (Plane, Double, Double, IEnumerable(Guid), ObjectAttributes, HistoryRecord, Boolean)" tocid="M_Rhino_DocObjects_Tables_ObjectTable_AddClippingPlane_2">AddClippingPlane Method (Plane, Double, Double, IEnumerable(Guid), ObjectAttributes, HistoryRecord, Boolean)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_DocObjects_Tables_ObjectTable_AddClippingPlane_4.htm" title="AddClippingPlane Method (Plane, Double, Double, Guid, ObjectAttributes, HistoryRecord, Boolean)" tocid="M_Rhino_DocObjects_Tables_ObjectTable_AddClippingPlane_4">AddClippingPlane Method (Plane, Double, Double, Guid, ObjectAttributes, HistoryRecord, Boolean)</a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn">ObjectTable<span id="LSTFFC039B_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTFFC039B_0?cpp=::|nu=.");</script>AddClippingPlane Method (Plane, Double, Double, Guid)</td></tr></table><span class="introStyle">Rhino for Mac 5.1</span><div class="summary">
            Adds a clipping plane object to Rhino.
            </div><p> </p><strong>Namespace:</strong> <a href="N_Rhino_DocObjects_Tables.htm">Rhino.DocObjects.Tables</a><br /><strong>Assembly:</strong> RhinoCommon (in RhinoCommon.dll) Version: 5.1.50000.0 (5.0.20693.0)<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">Guid</span> <span class="identifier">AddClippingPlane</span>(
	<span class="identifier">Plane</span> <span class="parameter">plane</span>,
	<span class="identifier">double</span> <span class="parameter">uMagnitude</span>,
	<span class="identifier">double</span> <span class="parameter">vMagnitude</span>,
	<span class="identifier">Guid</span> <span class="parameter">clippedViewportId</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Function</span> <span class="identifier">AddClippingPlane</span> ( 
	<span class="parameter">plane</span> <span class="keyword">As</span> <span class="identifier">Plane</span>,
	<span class="parameter">uMagnitude</span> <span class="keyword">As</span> <span class="identifier">Double</span>,
	<span class="parameter">vMagnitude</span> <span class="keyword">As</span> <span class="identifier">Double</span>,
	<span class="parameter">clippedViewportId</span> <span class="keyword">As</span> <span class="identifier">Guid</span>
) <span class="keyword">As</span> <span class="identifier">Guid</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">plane</span></dt><dd>Type: <a href="T_Rhino_Geometry_Plane.htm">Rhino.Geometry<span id="LSTFFC039B_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTFFC039B_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Plane</a><br />The plane value.</dd><dt><span class="parameter">uMagnitude</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">System<span id="LSTFFC039B_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTFFC039B_2?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Double</a><br />The size in the U direction.</dd><dt><span class="parameter">vMagnitude</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">System<span id="LSTFFC039B_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTFFC039B_3?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Double</a><br />The size in the V direction.</dd><dt><span class="parameter">clippedViewportId</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/cey1zx63" target="_blank">System<span id="LSTFFC039B_4"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTFFC039B_4?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Guid</a><br />Viewport ID that the new clipping plane will clip.</dd></dl><h4 class="subHeading">Return Value</h4>Type: <a href="http://msdn2.microsoft.com/en-us/library/cey1zx63" target="_blank">Guid</a><br />A unique identifier for the object.</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBABA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','cs','1','2');return false;">C#</a></div><div id="ID0EBBABA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBBABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">using</span> System;

<span class="highlight-keyword">partial</span> <span class="highlight-keyword">class</span> Examples
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">static</span> Rhino.Commands.Result AddClippingPlane(Rhino.RhinoDoc doc)
  {
    <span class="highlight-comment">// Define the corners of the clipping plane</span>
    Rhino.Geometry.Point3d[] corners;
    Rhino.Commands.Result rc = Rhino.Input.RhinoGet.GetRectangle(<span class="highlight-keyword">out</span> corners);
    <span class="highlight-keyword">if</span> (rc != Rhino.Commands.Result.Success)
      <span class="highlight-keyword">return</span> rc;

    <span class="highlight-comment">// Get the active view</span>
    Rhino.Display.RhinoView view = doc.Views.ActiveView;
    <span class="highlight-keyword">if</span> (view == <span class="highlight-keyword">null</span>)
      <span class="highlight-keyword">return</span> Rhino.Commands.Result.Failure;

    Rhino.Geometry.Point3d p0 = corners[<span class="highlight-number">0</span>];
    Rhino.Geometry.Point3d p1 = corners[<span class="highlight-number">1</span>];
    Rhino.Geometry.Point3d p3 = corners[<span class="highlight-number">3</span>];

    <span class="highlight-comment">// Create a plane from the corner points</span>
    Rhino.Geometry.Plane plane = <span class="highlight-keyword">new</span> Rhino.Geometry.Plane(p0, p1, p3);

    <span class="highlight-comment">// Add a clipping plane object to the document</span>
    Guid id = doc.Objects.AddClippingPlane(plane, p0.DistanceTo(p1), p0.DistanceTo(p3), view.ActiveViewportID);
    <span class="highlight-keyword">if</span> (id != Guid.Empty)
    {
      doc.Views.Redraw();
      <span class="highlight-keyword">return</span> Rhino.Commands.Result.Success;
    }
    <span class="highlight-keyword">return</span> Rhino.Commands.Result.Failure;
  }
}</pre></div><div id="ID0EBBABA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Partial</span> <span class="highlight-keyword">Class</span> Examples
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Shared</span> <span class="highlight-keyword">Function</span> AddClippingPlane(<span class="highlight-keyword">ByVal</span> doc <span class="highlight-keyword">As</span> Rhino.RhinoDoc) <span class="highlight-keyword">As</span> Rhino.Commands.Result
    <span class="highlight-comment">' Define the corners of the clipping plane</span>
    <span class="highlight-keyword">Dim</span> corners <span class="highlight-keyword">As</span> Rhino.Geometry.Point3d() = <span class="highlight-keyword">Nothing</span>
    <span class="highlight-keyword">Dim</span> rc <span class="highlight-keyword">As</span> Rhino.Commands.Result = Rhino.Input.RhinoGet.GetRectangle(corners)
    <span class="highlight-keyword">If</span> rc &lt;&gt; Rhino.Commands.Result.Success <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">Return</span> rc
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

    <span class="highlight-comment">' Get the active view</span>
    <span class="highlight-keyword">Dim</span> view <span class="highlight-keyword">As</span> Rhino.Display.RhinoView = doc.Views.ActiveView
    <span class="highlight-keyword">If</span> view <span class="highlight-keyword">Is</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Failure
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

    <span class="highlight-keyword">Dim</span> p0 <span class="highlight-keyword">As</span> Rhino.Geometry.Point3d = corners(<span class="highlight-number">0</span>)
    <span class="highlight-keyword">Dim</span> p1 <span class="highlight-keyword">As</span> Rhino.Geometry.Point3d = corners(<span class="highlight-number">1</span>)
    <span class="highlight-keyword">Dim</span> p3 <span class="highlight-keyword">As</span> Rhino.Geometry.Point3d = corners(<span class="highlight-number">3</span>)

    <span class="highlight-comment">' Create a plane from the corner points</span>
    <span class="highlight-keyword">Dim</span> plane <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Rhino.Geometry.Plane(p0, p1, p3)

    <span class="highlight-comment">' Add a clipping plane object to the document</span>
    <span class="highlight-keyword">Dim</span> id <span class="highlight-keyword">As</span> Guid = doc.Objects.AddClippingPlane(plane, p0.DistanceTo(p1), p0.DistanceTo(p3), view.ActiveViewportID)
    <span class="highlight-keyword">If</span> id &lt;&gt; Guid.Empty <span class="highlight-keyword">Then</span>
      doc.Views.Redraw()
      <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Success
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
    <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Failure
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBABA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAAABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EAAABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAAABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">import</span> Rhino
<span class="highlight-keyword">import</span> scriptcontext
<span class="highlight-keyword">import</span> System.Guid

<span class="highlight-keyword">def</span> AddClippingPlane():
    <span class="highlight-comment"># Define the corners of the clipping plane</span>
    rc, corners = Rhino.Input.RhinoGet.GetRectangle()
    <span class="highlight-keyword">if</span> rc!=Rhino.Commands.Result.Success: <span class="highlight-keyword">return</span> rc

    <span class="highlight-comment"># Get the active view</span>
    view = scriptcontext.doc.Views.ActiveView
    <span class="highlight-keyword">if</span> view <span class="highlight-keyword">is</span> None: <span class="highlight-keyword">return</span> Rhino.Commands.Result.Failure

    p0, p1, p2, p3 = corners
    <span class="highlight-comment"># Create a plane from the corner points</span>
    plane = Rhino.Geometry.Plane(p0, p1, p3)

    <span class="highlight-comment"># Add a clipping plane object to the document</span>
    id = scriptcontext.doc.Objects.AddClippingPlane(plane, p0.DistanceTo(p1), p0.DistanceTo(p3), view.ActiveViewportID)
    <span class="highlight-keyword">if</span> id!=System.Guid.Empty:
        scriptcontext.doc.Views.Redraw()
        <span class="highlight-keyword">return</span> Rhino.Commands.Result.Success
    <span class="highlight-keyword">return</span> Rhino.Commands.Result.Failure

<span class="highlight-keyword">if</span> __name__==<span class="highlight-literal">"__main__"</span>:
    AddClippingPlane()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAAABA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_DocObjects_Tables_ObjectTable.htm">ObjectTable Class</a></div><div class="seeAlsoStyle"><a href="Overload_Rhino_DocObjects_Tables_ObjectTable_AddClippingPlane.htm">AddClippingPlane Overload</a></div><div class="seeAlsoStyle"><a href="N_Rhino_DocObjects_Tables.htm">Rhino.DocObjects.Tables Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Updated 4 October 2015 - Robert McNeel and Associates<p><a href="http://discourse.mcneel.com/" target="_blank">Report wishes and bugs: http://discourse.mcneel.com/</a></p><div class="feedbackLink">Send comments on this topic to
        <a id="HT_MailLink" href="mailto:steve%40mcneel.com?Subject=RhinoCommon SDK">steve@mcneel.com</a></div><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title + "\u0026body=" + encodeURIComponent("Your feedback is used to improve the documentation and the product. Your e-mail address will not be used for any other purpose and is disposed of after the issue you report is resolved. While working to resolve the issue that you report, you may be contacted via e-mail to get further details or clarification on the feedback you sent. After the issue you report has been addressed, you may receive an e-mail to let you know that your feedback has been addressed.");
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script> </div></body></html>