<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>LineCurve Constructor (Point3d, Point3d)</title><meta name="Language" content="en-us" /><meta name="Microsoft.Help.Id" content="M:Rhino.Geometry.LineCurve.#ctor(Rhino.Geometry.Point3d,Rhino.Geometry.Point3d)" /><meta name="Description" content="Initializes a new instance of the class, by setting start and end point from two 3D points." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Geometry" /><meta name="file" content="M_Rhino_Geometry_LineCurve__ctor_5" /><meta name="guid" content="M_Rhino_Geometry_LineCurve__ctor_5" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.3.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon API<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="RhinoCommon API" tocid="roottoc">RhinoCommon API</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="Namespaces" tocid="R_Project_RhinoCommon">Namespaces</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Rhino_Geometry.htm" title="Rhino.Geometry" tocid="N_Rhino_Geometry">Rhino.Geometry</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Rhino_Geometry_LineCurve.htm" title="LineCurve Class" tocid="T_Rhino_Geometry_LineCurve">LineCurve Class</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_LineCurve__ctor.htm" title="LineCurve Constructor " tocid="Overload_Rhino_Geometry_LineCurve__ctor">LineCurve Constructor </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_LineCurve__ctor.htm" title="LineCurve Constructor " tocid="M_Rhino_Geometry_LineCurve__ctor">LineCurve Constructor </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_LineCurve__ctor_1.htm" title="LineCurve Constructor (Line)" tocid="M_Rhino_Geometry_LineCurve__ctor_1">LineCurve Constructor (Line)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_LineCurve__ctor_3.htm" title="LineCurve Constructor (LineCurve)" tocid="M_Rhino_Geometry_LineCurve__ctor_3">LineCurve Constructor (LineCurve)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_LineCurve__ctor_6.htm" title="LineCurve Constructor (SerializationInfo, StreamingContext)" tocid="M_Rhino_Geometry_LineCurve__ctor_6">LineCurve Constructor (SerializationInfo, StreamingContext)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_LineCurve__ctor_4.htm" title="LineCurve Constructor (Point2d, Point2d)" tocid="M_Rhino_Geometry_LineCurve__ctor_4">LineCurve Constructor (Point2d, Point2d)</a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_LineCurve__ctor_5.htm" title="LineCurve Constructor (Point3d, Point3d)" tocid="M_Rhino_Geometry_LineCurve__ctor_5">LineCurve Constructor (Point3d, Point3d)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_LineCurve__ctor_2.htm" title="LineCurve Constructor (Line, Double, Double)" tocid="M_Rhino_Geometry_LineCurve__ctor_2">LineCurve Constructor (Line, Double, Double)</a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn"><h1>LineCurve Constructor (Point3d, Point3d)</h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            Initializes a new instance of the <a href="T_Rhino_Geometry_LineCurve.htm">LineCurve</a> class, by
            setting start and end point from two <a href="T_Rhino_Geometry_Point3d.htm">3D points</a>.</div><p> </p>
    <strong>Namespace:</strong> 
   <a href="N_Rhino_Geometry.htm">Rhino.Geometry</a><br />
    <strong>Assembly:</strong>
   RhinoCommon (in RhinoCommon.dll)<div class="since"><strong>Since:</strong> 5.0</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">LineCurve</span>(
	<span class="identifier">Point3d</span> <span class="parameter">from</span>,
	<span class="identifier">Point3d</span> <span class="parameter">to</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Sub</span> <span class="identifier">New</span> ( 
	<span class="parameter">from</span> <span class="keyword">As</span> <span class="identifier">Point3d</span>,
	<span class="parameter">to</span> <span class="keyword">As</span> <span class="identifier">Point3d</span>
)</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">from</span></dt><dd>Type: <a href="T_Rhino_Geometry_Point3d.htm">Rhino.Geometry<span id="LSTAF9BA3DA_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTAF9BA3DA_0?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Point3d</a><br />A start point.</dd><dt><span class="parameter">to</span></dt><dd>Type: <a href="T_Rhino_Geometry_Point3d.htm">Rhino.Geometry<span id="LSTAF9BA3DA_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTAF9BA3DA_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Point3d</a><br />An end point.</dd></dl></div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBEBA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBEBA','cs','1','2');return false;">C#</a></div><div id="ID0EBBEBA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBEBA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBEBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBBEBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBEBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">using</span> System;
<span class="highlight-keyword">using</span> Rhino.Geometry;

<span class="highlight-keyword">partial</span> <span class="highlight-keyword">class</span> Examples
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">static</span> Rhino.Commands.Result AddTruncatedCone(Rhino.RhinoDoc doc)
  {
    Point3d bottom_pt = <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">0</span>,<span class="highlight-number">0</span>,<span class="highlight-number">0</span>);
    <span class="highlight-keyword">const</span> <span class="highlight-keyword">double</span> bottom_radius = <span class="highlight-number">2</span>;
    Circle bottom_circle = <span class="highlight-keyword">new</span> Circle(bottom_pt, bottom_radius);

    Point3d top_pt = <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">0</span>,<span class="highlight-number">0</span>,<span class="highlight-number">10</span>);
    <span class="highlight-keyword">const</span> <span class="highlight-keyword">double</span> top_radius = <span class="highlight-number">6</span>;
    Circle top_circle = <span class="highlight-keyword">new</span> Circle(top_pt, top_radius);

    LineCurve shapeCurve = <span class="highlight-keyword">new</span> LineCurve(bottom_circle.PointAt(<span class="highlight-number">0</span>), top_circle.PointAt(<span class="highlight-number">0</span>));
    Line axis = <span class="highlight-keyword">new</span> Line(bottom_circle.Center, top_circle.Center);
    RevSurface revsrf = RevSurface.Create(shapeCurve, axis);
    Brep tcone_brep = Brep.CreateFromRevSurface(revsrf, <span class="highlight-keyword">true</span>, <span class="highlight-keyword">true</span>);
    <span class="highlight-keyword">if</span>( doc.Objects.AddBrep(tcone_brep) != Guid.Empty )
    {
      doc.Views.Redraw();
      <span class="highlight-keyword">return</span> Rhino.Commands.Result.Success;
    }
    <span class="highlight-keyword">return</span> Rhino.Commands.Result.Failure;
  }
}</pre></div><div id="ID0EBBEBA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Imports</span> Rhino.Geometry

<span class="highlight-keyword">Partial</span> <span class="highlight-keyword">Class</span> Examples
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Shared</span> <span class="highlight-keyword">Function</span> AddTruncatedCone(<span class="highlight-keyword">ByVal</span> doc <span class="highlight-keyword">As</span> Rhino.RhinoDoc) <span class="highlight-keyword">As</span> Rhino.Commands.Result
    <span class="highlight-keyword">Dim</span> bottom_pt <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">0</span>, <span class="highlight-number">0</span>, <span class="highlight-number">0</span>)
    <span class="highlight-keyword">Const</span> bottom_radius <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span> = <span class="highlight-number">2</span>
    <span class="highlight-keyword">Dim</span> bottom_circle <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Circle(bottom_pt, bottom_radius)

    <span class="highlight-keyword">Dim</span> top_pt <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">0</span>, <span class="highlight-number">0</span>, <span class="highlight-number">10</span>)
    <span class="highlight-keyword">Const</span> top_radius <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span> = <span class="highlight-number">6</span>
    <span class="highlight-keyword">Dim</span> top_circle <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Circle(top_pt, top_radius)

    <span class="highlight-keyword">Dim</span> shapeCurve <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> LineCurve(bottom_circle.PointAt(<span class="highlight-number">0</span>), top_circle.PointAt(<span class="highlight-number">0</span>))
    <span class="highlight-keyword">Dim</span> axis <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Line(bottom_circle.Center, top_circle.Center)
    <span class="highlight-keyword">Dim</span> revsrf <span class="highlight-keyword">As</span> RevSurface = RevSurface.Create(shapeCurve, axis)
    <span class="highlight-keyword">Dim</span> tcone_brep <span class="highlight-keyword">As</span> Brep = Brep.CreateFromRevSurface(revsrf, <span class="highlight-keyword">True</span>, <span class="highlight-keyword">True</span>)
    <span class="highlight-keyword">If</span> doc.Objects.AddBrep(tcone_brep) &lt;&gt; Guid.Empty <span class="highlight-keyword">Then</span>
      doc.Views.Redraw()
      <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Success
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
    <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Failure
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBEBA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EAAEBA_tab1" class="codeSnippetContainerTabSingle">Python</div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAAEBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EAAEBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAAEBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">import</span> Rhino
<span class="highlight-keyword">import</span> scriptcontext
<span class="highlight-keyword">import</span> System.Guid

<span class="highlight-keyword">def</span> AddTruncatedCone():
    bottom_pt = Rhino.Geometry.Point3d(<span class="highlight-number">0</span>,<span class="highlight-number">0</span>,<span class="highlight-number">0</span>)
    bottom_radius = <span class="highlight-number">2</span>
    bottom_circle = Rhino.Geometry.Circle(bottom_pt, bottom_radius)

    top_pt = Rhino.Geometry.Point3d(<span class="highlight-number">0</span>,<span class="highlight-number">0</span>,<span class="highlight-number">10</span>)
    top_radius = <span class="highlight-number">6</span>
    top_circle = Rhino.Geometry.Circle(top_pt, top_radius)

    shapeCurve = Rhino.Geometry.LineCurve(bottom_circle.PointAt(<span class="highlight-number">0</span>), top_circle.PointAt(<span class="highlight-number">0</span>))
    axis = Rhino.Geometry.Line(bottom_circle.Center, top_circle.Center)
    revsrf = Rhino.Geometry.RevSurface.Create(shapeCurve, axis)
    tcone_brep = Rhino.Geometry.Brep.CreateFromRevSurface(revsrf, True, True)

    <span class="highlight-keyword">if</span> scriptcontext.doc.Objects.AddBrep(tcone_brep)!=System.Guid.Empty:
        scriptcontext.doc.Views.Redraw()
        <span class="highlight-keyword">return</span> Rhino.Commands.Result.Success
    <span class="highlight-keyword">return</span> Rhino.Commands.Result.Failure


<span class="highlight-keyword">if</span> __name__==<span class="highlight-literal">"__main__"</span>:
    AddTruncatedCone()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAAEBA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_Geometry_LineCurve.htm">LineCurve Class</a></div><div class="seeAlsoStyle"><a href="Overload_Rhino_Geometry_LineCurve__ctor.htm">LineCurve Overload</a></div><div class="seeAlsoStyle"><a href="N_Rhino_Geometry.htm">Rhino.Geometry Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Rhino 7.17.22102.05000 (Last updated: 4/21/2022)<br />Copyright © 2009-2022 Robert McNeel &amp; Associates<p><a href="https://discourse.mcneel.com/c/rhino-developer" target="_blank">Report wishes and bugs at discourse.mcneel.com</a></p> </div></body></html>