<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Plane.DistanceTo Method </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="DistanceTo method" /><meta name="System.Keywords" content="Plane.DistanceTo method" /><meta name="Microsoft.Help.F1" content="Rhino.Geometry.Plane.DistanceTo" /><meta name="Microsoft.Help.Id" content="M:Rhino.Geometry.Plane.DistanceTo(Rhino.Geometry.Point3d)" /><meta name="Description" content="Returns the signed distance from testPoint to its projection onto this plane. If the point is below the plane, a negative distance is returned." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Geometry" /><meta name="file" content="M_Rhino_Geometry_Plane_DistanceTo" /><meta name="guid" content="M_Rhino_Geometry_Plane_DistanceTo" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-1.11.0.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon SDK<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino.htm" title="RhinoCommon SDK" tocid="roottoc">RhinoCommon SDK</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino_Geometry.htm" title="Rhino.Geometry" tocid="N_Rhino_Geometry">Rhino.Geometry</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="T_Rhino_Geometry_Plane.htm" title="Plane Structure" tocid="T_Rhino_Geometry_Plane">Plane Structure</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Methods_T_Rhino_Geometry_Plane.htm" title="Plane Methods" tocid="Methods_T_Rhino_Geometry_Plane">Plane Methods</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Plane_ClosestParameter.htm" title="ClosestParameter Method " tocid="M_Rhino_Geometry_Plane_ClosestParameter">ClosestParameter Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Plane_ClosestPoint.htm" title="ClosestPoint Method " tocid="M_Rhino_Geometry_Plane_ClosestPoint">ClosestPoint Method </a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Plane_DistanceTo.htm" title="DistanceTo Method " tocid="M_Rhino_Geometry_Plane_DistanceTo">DistanceTo Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Plane_EpsilonEquals.htm" title="EpsilonEquals Method " tocid="M_Rhino_Geometry_Plane_EpsilonEquals">EpsilonEquals Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Overload_Rhino_Geometry_Plane_Equals.htm" title="Equals Method " tocid="Overload_Rhino_Geometry_Plane_Equals">Equals Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Overload_Rhino_Geometry_Plane_ExtendThroughBox.htm" title="ExtendThroughBox Method " tocid="Overload_Rhino_Geometry_Plane_ExtendThroughBox">ExtendThroughBox Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Overload_Rhino_Geometry_Plane_FitPlaneToPoints.htm" title="FitPlaneToPoints Method " tocid="Overload_Rhino_Geometry_Plane_FitPlaneToPoints">FitPlaneToPoints Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Plane_Flip.htm" title="Flip Method " tocid="M_Rhino_Geometry_Plane_Flip">Flip Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Plane_GetHashCode.htm" title="GetHashCode Method " tocid="M_Rhino_Geometry_Plane_GetHashCode">GetHashCode Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Plane_GetPlaneEquation.htm" title="GetPlaneEquation Method " tocid="M_Rhino_Geometry_Plane_GetPlaneEquation">GetPlaneEquation Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Overload_Rhino_Geometry_Plane_PointAt.htm" title="PointAt Method " tocid="Overload_Rhino_Geometry_Plane_PointAt">PointAt Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Plane_RemapToPlaneSpace.htm" title="RemapToPlaneSpace Method " tocid="M_Rhino_Geometry_Plane_RemapToPlaneSpace">RemapToPlaneSpace Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Overload_Rhino_Geometry_Plane_Rotate.htm" title="Rotate Method " tocid="Overload_Rhino_Geometry_Plane_Rotate">Rotate Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Plane_ToString.htm" title="ToString Method " tocid="M_Rhino_Geometry_Plane_ToString">ToString Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Plane_Transform.htm" title="Transform Method " tocid="M_Rhino_Geometry_Plane_Transform">Transform Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Plane_Translate.htm" title="Translate Method " tocid="M_Rhino_Geometry_Plane_Translate">Translate Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Plane_ValueAt.htm" title="ValueAt Method " tocid="M_Rhino_Geometry_Plane_ValueAt">ValueAt Method </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn">Plane<span id="LST4E6F00FD_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST4E6F00FD_0?cpp=::|nu=.");</script>DistanceTo Method </td></tr></table><span class="introStyle">Rhino for Mac 5.1</span><div class="summary">
            Returns the signed distance from testPoint to its projection onto this plane.
            If the point is below the plane, a negative distance is returned.
            </div><p> </p><strong>Namespace:</strong> <a href="N_Rhino_Geometry.htm">Rhino.Geometry</a><br /><strong>Assembly:</strong> RhinoCommon (in RhinoCommon.dll) Version: 5.1.50000.0 (5.0.20693.0)<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">double</span> <span class="identifier">DistanceTo</span>(
	<span class="identifier">Point3d</span> <span class="parameter">testPoint</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Function</span> <span class="identifier">DistanceTo</span> ( 
	<span class="parameter">testPoint</span> <span class="keyword">As</span> <span class="identifier">Point3d</span>
) <span class="keyword">As</span> <span class="identifier">Double</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">testPoint</span></dt><dd>Type: <a href="T_Rhino_Geometry_Point3d.htm">Rhino.Geometry<span id="LST4E6F00FD_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST4E6F00FD_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Point3d</a><br />Point to test.</dd></dl><h4 class="subHeading">Return Value</h4>Type: <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">Double</a><br />Signed distance from this plane to testPoint.</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBABA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','cs','1','2');return false;">C#</a></div><div id="ID0EBBABA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBBABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">using</span> System.Linq;
<span class="highlight-keyword">using</span> Rhino;
<span class="highlight-keyword">using</span> Rhino.DocObjects;
<span class="highlight-keyword">using</span> Rhino.Geometry;
<span class="highlight-keyword">using</span> Rhino.Commands;
<span class="highlight-keyword">using</span> Rhino.Input;

<span class="highlight-keyword">namespace</span> examples_cs
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">class</span> IsPlanarSurfaceInPlaneCommand : Command
  {
    <span class="highlight-keyword">public</span> <span class="highlight-keyword">override</span> <span class="highlight-keyword">string</span> EnglishName { <span class="highlight-keyword">get</span> { <span class="highlight-keyword">return</span> <span class="highlight-literal">"csIsPlanarSurfaceInPlane"</span>; } }

    <span class="highlight-keyword">protected</span> <span class="highlight-keyword">override</span> Result RunCommand(RhinoDoc doc, RunMode mode)
    {
      ObjRef obj_ref;
      <span class="highlight-keyword">var</span> rc = RhinoGet.GetOneObject(<span class="highlight-literal">"select surface"</span>, <span class="highlight-keyword">true</span>, ObjectType.Surface, <span class="highlight-keyword">out</span> obj_ref);
      <span class="highlight-keyword">if</span> (rc != Result.Success)
        <span class="highlight-keyword">return</span> rc;
      <span class="highlight-keyword">var</span> surface = obj_ref.Surface();

      Point3d[] corners;
      rc = RhinoGet.GetRectangle(<span class="highlight-keyword">out</span> corners);
      <span class="highlight-keyword">if</span> (rc != Result.Success)
        <span class="highlight-keyword">return</span> rc;

      <span class="highlight-keyword">var</span> plane = <span class="highlight-keyword">new</span> Plane(corners[<span class="highlight-number">0</span>], corners[<span class="highlight-number">1</span>], corners[<span class="highlight-number">2</span>]);

      <span class="highlight-keyword">var</span> is_or_isnt = <span class="highlight-literal">""</span>;
      <span class="highlight-keyword">if</span> (IsSurfaceInPlane(surface, plane, doc.ModelAbsoluteTolerance))
        is_or_isnt = <span class="highlight-literal">" not "</span>;

      RhinoApp.WriteLine(<span class="highlight-literal">"Surface is{0} in plane."</span>, is_or_isnt);
      <span class="highlight-keyword">return</span> Result.Success;
    }

    <span class="highlight-keyword">private</span> <span class="highlight-keyword">bool</span> IsSurfaceInPlane(Surface surface, Plane plane, <span class="highlight-keyword">double</span> tolerance)
    {
      <span class="highlight-keyword">if</span> (!surface.IsPlanar(tolerance))
        <span class="highlight-keyword">return</span> <span class="highlight-keyword">false</span>;

      <span class="highlight-keyword">var</span> bbox = surface.GetBoundingBox(<span class="highlight-keyword">true</span>);
      <span class="highlight-keyword">return</span> bbox.GetCorners().All(
        corner =&gt; System.Math.Abs(plane.DistanceTo(corner)) &lt;= tolerance);
    }
  }
}</pre></div><div id="ID0EBBABA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Imports</span> System.Linq
<span class="highlight-keyword">Imports</span> Rhino
<span class="highlight-keyword">Imports</span> Rhino.DocObjects
<span class="highlight-keyword">Imports</span> Rhino.Geometry
<span class="highlight-keyword">Imports</span> Rhino.Commands
<span class="highlight-keyword">Imports</span> Rhino.Input

<span class="highlight-keyword">Namespace</span> examples_vb
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Class</span> IsPlanarSurfaceInPlaneCommand
    <span class="highlight-keyword">Inherits</span> Command
    <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">ReadOnly</span> <span class="highlight-keyword">Property</span> EnglishName() <span class="highlight-keyword">As</span> <span class="highlight-keyword">String</span>
      <span class="highlight-keyword">Get</span>
        <span class="highlight-keyword">Return</span> <span class="highlight-literal">"vbIsPlanarSurfaceInPlane"</span>
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">Get</span>
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Property</span>

    <span class="highlight-keyword">Protected</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">Function</span> RunCommand(doc <span class="highlight-keyword">As</span> RhinoDoc, mode <span class="highlight-keyword">As</span> RunMode) <span class="highlight-keyword">As</span> Result
      <span class="highlight-keyword">Dim</span> obj_ref <span class="highlight-keyword">As</span> ObjRef = <span class="highlight-keyword">Nothing</span>
      <span class="highlight-keyword">Dim</span> rc = RhinoGet.GetOneObject(<span class="highlight-literal">"select surface"</span>, <span class="highlight-keyword">True</span>, ObjectType.Surface, obj_ref)
      <span class="highlight-keyword">If</span> rc &lt;&gt; Result.Success <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> rc
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
      <span class="highlight-keyword">Dim</span> surface = obj_ref.Surface()

      <span class="highlight-keyword">Dim</span> corners <span class="highlight-keyword">As</span> Point3d() = <span class="highlight-keyword">Nothing</span>
      rc = RhinoGet.GetRectangle(corners)
      <span class="highlight-keyword">If</span> rc &lt;&gt; Result.Success <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> rc
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

      <span class="highlight-keyword">Dim</span> plane = <span class="highlight-keyword">New</span> Plane(corners(<span class="highlight-number">0</span>), corners(<span class="highlight-number">1</span>), corners(<span class="highlight-number">2</span>))

      <span class="highlight-keyword">Dim</span> is_or_isnt = <span class="highlight-keyword">If</span>(IsSurfaceInPlane(surface, plane, doc.ModelAbsoluteTolerance), <span class="highlight-literal">""</span>, <span class="highlight-literal">" not "</span>)
      RhinoApp.WriteLine(<span class="highlight-literal">"Surface is{0} in plane."</span>, is_or_isnt)
      <span class="highlight-keyword">Return</span> Result.Success
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>

    <span class="highlight-keyword">Private</span> <span class="highlight-keyword">Function</span> IsSurfaceInPlane(surface <span class="highlight-keyword">As</span> Surface, plane <span class="highlight-keyword">As</span> Plane, tolerance <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span>) <span class="highlight-keyword">As</span> <span class="highlight-keyword">Boolean</span>
      <span class="highlight-keyword">If</span> <span class="highlight-keyword">Not</span> surface.IsPlanar(tolerance) <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> <span class="highlight-keyword">False</span>
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

      <span class="highlight-keyword">Dim</span> bbox = surface.GetBoundingBox(<span class="highlight-keyword">True</span>)
      <span class="highlight-keyword">Return</span> bbox.GetCorners().All(<span class="highlight-keyword">Function</span>(corner) Math.Abs(plane.DistanceTo(corner)) &lt;= tolerance)
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Namespace</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBABA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAAABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EAAABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAAABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">import</span> Rhino
<span class="highlight-keyword">from</span> Rhino.Geometry <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">import</span> rhinoscriptsyntax <span class="highlight-keyword">as</span> rs
<span class="highlight-keyword">from</span> scriptcontext <span class="highlight-keyword">import</span> doc
<span class="highlight-keyword">import</span> math

<span class="highlight-keyword">def</span> RunCommand():
  surface_id = rs.GetSurfaceObject()[<span class="highlight-number">0</span>]
  <span class="highlight-keyword">if</span> surface_id == None:
    <span class="highlight-keyword">return</span>
  surface = rs.coercesurface(surface_id)

  corners = rs.GetRectangle()
  <span class="highlight-keyword">if</span> corners == None:
    <span class="highlight-keyword">return</span>

  plane = Plane(corners[<span class="highlight-number">0</span>], corners[<span class="highlight-number">1</span>], corners[<span class="highlight-number">2</span>])

  is_or_isnt = <span class="highlight-literal">""</span> <span class="highlight-keyword">if</span> IsSurfaceInPlane(surface, plane, doc.ModelAbsoluteTolerance) <span class="highlight-keyword">else</span> <span class="highlight-literal">" not "</span>
  <span class="highlight-keyword">print</span> <span class="highlight-literal">"Surface is{0} in plane."</span>.format(is_or_isnt)

<span class="highlight-keyword">def</span> IsSurfaceInPlane(surface, plane, tolerance):
  <span class="highlight-keyword">if</span> <span class="highlight-keyword">not</span> surface.IsPlanar(tolerance):
    <span class="highlight-keyword">return</span> False

  bbox = surface.GetBoundingBox(True)
  rc = True
  <span class="highlight-keyword">for</span> corner <span class="highlight-keyword">in</span> bbox.GetCorners():
      <span class="highlight-keyword">if</span> math.fabs(plane.DistanceTo(corner)) &gt; tolerance:
          rc = False
          <span class="highlight-keyword">break</span>

  <span class="highlight-keyword">return</span> rc

<span class="highlight-keyword">if</span> __name__ == <span class="highlight-literal">"__main__"</span>:
    RunCommand()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAAABA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_Geometry_Plane.htm">Plane Structure</a></div><div class="seeAlsoStyle"><a href="N_Rhino_Geometry.htm">Rhino.Geometry Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Updated 4 October 2015 - Robert McNeel and Associates<p><a href="http://discourse.mcneel.com/" target="_blank">Report wishes and bugs: http://discourse.mcneel.com/</a></p><div class="feedbackLink">Send comments on this topic to
        <a id="HT_MailLink" href="mailto:steve%40mcneel.com?Subject=RhinoCommon SDK">steve@mcneel.com</a></div><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title + "\u0026body=" + encodeURIComponent("Your feedback is used to improve the documentation and the product. Your e-mail address will not be used for any other purpose and is disposed of after the issue you report is resolved. While working to resolve the issue that you report, you may be contacted via e-mail to get further details or clarification on the feedback you sent. After the issue you report has been addressed, you may receive an e-mail to let you know that your feedback has been addressed.");
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script> </div></body></html>