<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>RhinoViewport.ChangeToTwoPointPerspectiveProjection Method (Double, Vector3d, Double)</title><meta name="Language" content="en-us" /><meta name="Microsoft.Help.Id" content="M:Rhino.Display.RhinoViewport.ChangeToTwoPointPerspectiveProjection(System.Double,Rhino.Geometry.Vector3d,System.Double)" /><meta name="Description" content="Use this function to change projections of valid viewports to a two point perspective. It will make common additional adjustments to the frustum and camera location and direction so the resulting views are similar." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Display" /><meta name="file" content="M_Rhino_Display_RhinoViewport_ChangeToTwoPointPerspectiveProjection_1" /><meta name="guid" content="M_Rhino_Display_RhinoViewport_ChangeToTwoPointPerspectiveProjection_1" /><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.3.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon API<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="RhinoCommon API" tocid="roottoc">RhinoCommon API</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="Namespaces" tocid="R_Project_RhinoCommon">Namespaces</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Rhino_Display.htm" title="Rhino.Display" tocid="N_Rhino_Display">Rhino.Display</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Rhino_Display_RhinoViewport.htm" title="RhinoViewport Class" tocid="T_Rhino_Display_RhinoViewport">RhinoViewport Class</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Methods_T_Rhino_Display_RhinoViewport.htm" title="RhinoViewport Methods" tocid="Methods_T_Rhino_Display_RhinoViewport">RhinoViewport Methods</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Display_RhinoViewport_ChangeToTwoPointPerspectiveProjection.htm" title="ChangeToTwoPointPerspectiveProjection Method " tocid="Overload_Rhino_Display_RhinoViewport_ChangeToTwoPointPerspectiveProjection">ChangeToTwoPointPerspectiveProjection Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Display_RhinoViewport_ChangeToTwoPointPerspectiveProjection.htm" title="ChangeToTwoPointPerspectiveProjection Method (Double)" tocid="M_Rhino_Display_RhinoViewport_ChangeToTwoPointPerspectiveProjection">ChangeToTwoPointPerspectiveProjection Method (Double)</a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Display_RhinoViewport_ChangeToTwoPointPerspectiveProjection_1.htm" title="ChangeToTwoPointPerspectiveProjection Method (Double, Vector3d, Double)" tocid="M_Rhino_Display_RhinoViewport_ChangeToTwoPointPerspectiveProjection_1">ChangeToTwoPointPerspectiveProjection Method (Double, Vector3d, Double)</a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn"><h1>RhinoViewport<span id="LST1FBF48AD_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1FBF48AD_0?cpp=::|nu=.");</script>ChangeToTwoPointPerspectiveProjection Method (Double, Vector3d, Double)</h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            Use this function to change projections of valid viewports
            to a two point perspective.  It will make common additional
            adjustments to the frustum and camera location and direction
            so the resulting views are similar.
            </div><p> </p>
    <strong>Namespace:</strong> 
   <a href="N_Rhino_Display.htm">Rhino.Display</a><br />
    <strong>Assembly:</strong>
   RhinoCommon (in RhinoCommon.dll)<div class="since"><strong>Since:</strong> 6.0</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">bool</span> <span class="identifier">ChangeToTwoPointPerspectiveProjection</span>(
	<span class="identifier">double</span> <span class="parameter">targetDistance</span>,
	<span class="identifier">Vector3d</span> <span class="parameter">up</span>,
	<span class="identifier">double</span> <span class="parameter">lensLength</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Function</span> <span class="identifier">ChangeToTwoPointPerspectiveProjection</span> ( 
	<span class="parameter">targetDistance</span> <span class="keyword">As</span> <span class="identifier">Double</span>,
	<span class="parameter">up</span> <span class="keyword">As</span> <span class="identifier">Vector3d</span>,
	<span class="parameter">lensLength</span> <span class="keyword">As</span> <span class="identifier">Double</span>
) <span class="keyword">As</span> <span class="identifier">Boolean</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">targetDistance</span></dt><dd>Type: <a href="https://docs.microsoft.com/dotnet/api/system.double" target="_blank">System<span id="LST1FBF48AD_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1FBF48AD_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Double</a><br />
            If RhinoMath.UnsetValue this parameter is ignored. Otherwise it must be &gt; 0 and indicates
            which plane in the current view frustum should be preserved.
            </dd><dt><span class="parameter">up</span></dt><dd>Type: <a href="T_Rhino_Geometry_Vector3d.htm">Rhino.Geometry<span id="LST1FBF48AD_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1FBF48AD_2?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Vector3d</a><br />
             This direction will be the locked up direction.  Pass 
             ON_3dVector::ZeroVector if you want to use the world axis
             direction that is closest to the current up direction.
             Pass CameraY() if you want to preserve the current up direction.
            </dd><dt><span class="parameter">lensLength</span></dt><dd>Type: <a href="https://docs.microsoft.com/dotnet/api/system.double" target="_blank">System<span id="LST1FBF48AD_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1FBF48AD_3?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Double</a><br />
            (pass 50.0 when in doubt) 35 mm lens length to use when changing from parallel to perspective
            projections. If the current projection is perspective or lens_length is &lt;= 0.0, then
            this parameter is ignored.
            </dd></dl><h4 class="subHeading">Return Value</h4>Type: <a href="https://docs.microsoft.com/dotnet/api/system.boolean" target="_blank">Boolean</a><br />
            If the current projection is perspective and bSymmetricFrustum, FrustumIsLeftRightSymmetric()
            and FrustumIsTopBottomSymmetric() are all equal, then no changes are made and true is returned.
            </div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID2RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_Display_RhinoViewport.htm">RhinoViewport Class</a></div><div class="seeAlsoStyle"><a href="Overload_Rhino_Display_RhinoViewport_ChangeToTwoPointPerspectiveProjection.htm">ChangeToTwoPointPerspectiveProjection Overload</a></div><div class="seeAlsoStyle"><a href="N_Rhino_Display.htm">Rhino.Display Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Rhino 7.16.22067.13000 (Last updated: 3/10/2022)<br />Copyright © 2009-2022 Robert McNeel &amp; Associates<p><a href="https://discourse.mcneel.com/c/rhino-developer" target="_blank">Report wishes and bugs at discourse.mcneel.com</a></p> </div></body></html>