<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>ObjRef.SelectionPoint Method </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="SelectionPoint method" /><meta name="System.Keywords" content="ObjRef.SelectionPoint method" /><meta name="Microsoft.Help.F1" content="Rhino.DocObjects.ObjRef.SelectionPoint" /><meta name="Microsoft.Help.Id" content="M:Rhino.DocObjects.ObjRef.SelectionPoint" /><meta name="Description" content="If the object was selected by picking a point on it, then SelectionPoint() returns the point where the selection occured, otherwise it returns Point3d.Unset." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.DocObjects" /><meta name="file" content="M_Rhino_DocObjects_ObjRef_SelectionPoint" /><meta name="guid" content="M_Rhino_DocObjects_ObjRef_SelectionPoint" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-1.11.0.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon API<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html\R_Project_RhinoCommon.htm" title="RhinoCommon API" tocid="roottoc">RhinoCommon API</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="Namespaces" tocid="R_Project_RhinoCommon">Namespaces</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Rhino_DocObjects.htm" title="Rhino.DocObjects" tocid="N_Rhino_DocObjects">Rhino.DocObjects</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Rhino_DocObjects_ObjRef.htm" title="ObjRef Class" tocid="T_Rhino_DocObjects_ObjRef">ObjRef Class</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Methods_T_Rhino_DocObjects_ObjRef.htm" title="ObjRef Methods" tocid="Methods_T_Rhino_DocObjects_ObjRef">ObjRef Methods</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_Brep.htm" title="Brep Method " tocid="M_Rhino_DocObjects_ObjRef_Brep">Brep Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_ClippingPlaneSurface.htm" title="ClippingPlaneSurface Method " tocid="M_Rhino_DocObjects_ObjRef_ClippingPlaneSurface">ClippingPlaneSurface Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_Curve.htm" title="Curve Method " tocid="M_Rhino_DocObjects_ObjRef_Curve">Curve Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_CurveParameter.htm" title="CurveParameter Method " tocid="M_Rhino_DocObjects_ObjRef_CurveParameter">CurveParameter Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_DocObjects_ObjRef_Dispose.htm" title="Dispose Method " tocid="Overload_Rhino_DocObjects_ObjRef_Dispose">Dispose Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_Edge.htm" title="Edge Method " tocid="M_Rhino_DocObjects_ObjRef_Edge">Edge Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_Face.htm" title="Face Method " tocid="M_Rhino_DocObjects_ObjRef_Face">Face Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_Finalize.htm" title="Finalize Method " tocid="M_Rhino_DocObjects_ObjRef_Finalize">Finalize Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_Geometry.htm" title="Geometry Method " tocid="M_Rhino_DocObjects_ObjRef_Geometry">Geometry Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_Hatch.htm" title="Hatch Method " tocid="M_Rhino_DocObjects_ObjRef_Hatch">Hatch Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_InstanceDefinitionPart.htm" title="InstanceDefinitionPart Method " tocid="M_Rhino_DocObjects_ObjRef_InstanceDefinitionPart">InstanceDefinitionPart Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_Light.htm" title="Light Method " tocid="M_Rhino_DocObjects_ObjRef_Light">Light Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_Mesh.htm" title="Mesh Method " tocid="M_Rhino_DocObjects_ObjRef_Mesh">Mesh Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_Object.htm" title="Object Method " tocid="M_Rhino_DocObjects_ObjRef_Object">Object Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_Point.htm" title="Point Method " tocid="M_Rhino_DocObjects_ObjRef_Point">Point Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_PointCloud.htm" title="PointCloud Method " tocid="M_Rhino_DocObjects_ObjRef_PointCloud">PointCloud Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_SelectionMethod.htm" title="SelectionMethod Method " tocid="M_Rhino_DocObjects_ObjRef_SelectionMethod">SelectionMethod Method </a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_SelectionPoint.htm" title="SelectionPoint Method " tocid="M_Rhino_DocObjects_ObjRef_SelectionPoint">SelectionPoint Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_SelectionView.htm" title="SelectionView Method " tocid="M_Rhino_DocObjects_ObjRef_SelectionView">SelectionView Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_SelectionViewDetailSerialNumber.htm" title="SelectionViewDetailSerialNumber Method " tocid="M_Rhino_DocObjects_ObjRef_SelectionViewDetailSerialNumber">SelectionViewDetailSerialNumber Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_SetSelectionComponent.htm" title="SetSelectionComponent Method " tocid="M_Rhino_DocObjects_ObjRef_SetSelectionComponent">SetSelectionComponent Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_SubD.htm" title="SubD Method " tocid="M_Rhino_DocObjects_ObjRef_SubD">SubD Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_Surface.htm" title="Surface Method " tocid="M_Rhino_DocObjects_ObjRef_Surface">Surface Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_SurfaceParameter.htm" title="SurfaceParameter Method " tocid="M_Rhino_DocObjects_ObjRef_SurfaceParameter">SurfaceParameter Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_TextDot.htm" title="TextDot Method " tocid="M_Rhino_DocObjects_ObjRef_TextDot">TextDot Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_TextEntity.htm" title="TextEntity Method " tocid="M_Rhino_DocObjects_ObjRef_TextEntity">TextEntity Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_DocObjects_ObjRef_Trim.htm" title="Trim Method " tocid="M_Rhino_DocObjects_ObjRef_Trim">Trim Method </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn"><h1>ObjRef<span id="LST5A415DDF_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST5A415DDF_0?cpp=::|nu=.");</script>SelectionPoint Method </h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            If the object was selected by picking a point on it, then
            SelectionPoint() returns the point where the selection
            occured, otherwise it returns Point3d.Unset.
            </div><p> </p>
    <strong>Namespace:</strong> 
   <a href="N_Rhino_DocObjects.htm">Rhino.DocObjects</a><br />
    <strong>Assembly:</strong>
   RhinoCommon (in RhinoCommon.dll)<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">Point3d</span> <span class="identifier">SelectionPoint</span>()</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Function</span> <span class="identifier">SelectionPoint</span> <span class="keyword">As</span> <span class="identifier">Point3d</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Return Value</h4>Type: <a href="T_Rhino_Geometry_Point3d.htm">Point3d</a><br />
            The point where the selection occured or Point3d.Unset on failure.
            </div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBABA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','cs','1','2');return false;">C#</a></div><div id="ID0EBBABA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBABA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBBABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">using</span> System;

<span class="highlight-keyword">partial</span> <span class="highlight-keyword">class</span> Examples
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">static</span> Rhino.Commands.Result ConstrainedCopy(Rhino.RhinoDoc doc)
  {
    <span class="highlight-comment">// Get a single planar closed curve</span>
    <span class="highlight-keyword">var</span> go = <span class="highlight-keyword">new</span> Rhino.Input.Custom.GetObject();
    go.SetCommandPrompt(<span class="highlight-literal">"Select curve"</span>);
    go.GeometryFilter = Rhino.DocObjects.ObjectType.Curve;
    go.GeometryAttributeFilter = Rhino.Input.Custom.GeometryAttributeFilter.ClosedCurve;
    go.Get();
    <span class="highlight-keyword">if</span>( go.CommandResult() != Rhino.Commands.Result.Success )
      <span class="highlight-keyword">return</span> go.CommandResult();
    <span class="highlight-keyword">var</span> objref = go.Object(<span class="highlight-number">0</span>);
    <span class="highlight-keyword">var</span> base_curve = objref.Curve();
    <span class="highlight-keyword">var</span> first_point = objref.SelectionPoint();
    <span class="highlight-keyword">if</span>( base_curve==<span class="highlight-keyword">null</span> || !first_point.IsValid )
      <span class="highlight-keyword">return</span> Rhino.Commands.Result.Cancel;

    Rhino.Geometry.Plane plane;
    <span class="highlight-keyword">if</span>( !base_curve.TryGetPlane(<span class="highlight-keyword">out</span> plane) )
      <span class="highlight-keyword">return</span> Rhino.Commands.Result.Cancel;

    <span class="highlight-comment">// Get a point constrained to a line passing through the initial selection</span>
    <span class="highlight-comment">// point and parallel to the plane's normal</span>
    <span class="highlight-keyword">var</span> gp = <span class="highlight-keyword">new</span> Rhino.Input.Custom.GetPoint();
    gp.SetCommandPrompt(<span class="highlight-literal">"Offset point"</span>);
    gp.DrawLineFromPoint(first_point, <span class="highlight-keyword">true</span>);
    <span class="highlight-keyword">var</span> line = <span class="highlight-keyword">new</span> Rhino.Geometry.Line(first_point, first_point+plane.Normal);
    gp.Constrain(line);
    gp.Get();
    <span class="highlight-keyword">if</span>( gp.CommandResult() != Rhino.Commands.Result.Success )
      <span class="highlight-keyword">return</span> gp.CommandResult();
    <span class="highlight-keyword">var</span> second_point = gp.Point();
    Rhino.Geometry.Vector3d vec = second_point - first_point;
    <span class="highlight-keyword">if</span>( vec.Length &gt; <span class="highlight-number">0.001</span> )
    {
      <span class="highlight-keyword">var</span> xf = Rhino.Geometry.Transform.Translation(vec);
      Guid id = doc.Objects.Transform(objref, xf, <span class="highlight-keyword">false</span>);
      <span class="highlight-keyword">if</span>( id!=Guid.Empty )
      {
        doc.Views.Redraw();
        <span class="highlight-keyword">return</span> Rhino.Commands.Result.Success;
      }
    }
    <span class="highlight-keyword">return</span> Rhino.Commands.Result.Cancel;
  }
}</pre></div><div id="ID0EBBABA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Partial</span> <span class="highlight-keyword">Class</span> Examples
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Shared</span> <span class="highlight-keyword">Function</span> ConstrainedCopy(doc <span class="highlight-keyword">As</span> Rhino.RhinoDoc) <span class="highlight-keyword">As</span> Rhino.Commands.Result
    <span class="highlight-comment">' Get a single planar closed curve</span>
    <span class="highlight-keyword">Dim</span> go = <span class="highlight-keyword">New</span> Rhino.Input.Custom.GetObject()
    go.SetCommandPrompt(<span class="highlight-literal">"Select curve"</span>)
    go.GeometryFilter = Rhino.DocObjects.ObjectType.Curve
    go.GeometryAttributeFilter = Rhino.Input.Custom.GeometryAttributeFilter.ClosedCurve
    go.<span class="highlight-keyword">Get</span>()
    <span class="highlight-keyword">If</span> go.CommandResult() &lt;&gt; Rhino.Commands.Result.Success <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">Return</span> go.CommandResult()
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
    <span class="highlight-keyword">Dim</span> objref = go.<span class="highlight-keyword">Object</span>(<span class="highlight-number">0</span>)
    <span class="highlight-keyword">Dim</span> base_curve = objref.Curve()
    <span class="highlight-keyword">Dim</span> first_point = objref.SelectionPoint()
    <span class="highlight-keyword">If</span> base_curve <span class="highlight-keyword">Is</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">OrElse</span> <span class="highlight-keyword">Not</span> first_point.IsValid <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Cancel
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

    <span class="highlight-keyword">Dim</span> plane <span class="highlight-keyword">As</span> Rhino.Geometry.Plane
    <span class="highlight-keyword">If</span> <span class="highlight-keyword">Not</span> base_curve.TryGetPlane(plane) <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Cancel
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

    <span class="highlight-comment">' Get a point constrained to a line passing through the initial selection</span>
    <span class="highlight-comment">' point and parallel to the plane's normal</span>
    <span class="highlight-keyword">Dim</span> gp = <span class="highlight-keyword">New</span> Rhino.Input.Custom.GetPoint()
    gp.SetCommandPrompt(<span class="highlight-literal">"Offset point"</span>)
    gp.DrawLineFromPoint(first_point, <span class="highlight-keyword">True</span>)
    <span class="highlight-keyword">Dim</span> line = <span class="highlight-keyword">New</span> Rhino.Geometry.Line(first_point, first_point + plane.Normal)
    gp.Constrain(line)
    gp.<span class="highlight-keyword">Get</span>()
    <span class="highlight-keyword">If</span> gp.CommandResult() &lt;&gt; Rhino.Commands.Result.Success <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">Return</span> gp.CommandResult()
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
    <span class="highlight-keyword">Dim</span> second_point = gp.Point()
    <span class="highlight-keyword">Dim</span> vec <span class="highlight-keyword">As</span> Rhino.Geometry.Vector3d = second_point - first_point
    <span class="highlight-keyword">If</span> vec.Length &gt; <span class="highlight-number">0.001</span> <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">Dim</span> xf = Rhino.Geometry.Transform.Translation(vec)
      <span class="highlight-keyword">Dim</span> id <span class="highlight-keyword">As</span> Guid = doc.Objects.Transform(objref, xf, <span class="highlight-keyword">False</span>)
      <span class="highlight-keyword">If</span> id &lt;&gt; Guid.Empty <span class="highlight-keyword">Then</span>
        doc.Views.Redraw()
        <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Success
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
    <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Cancel
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBABA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EAAABA_tab1" class="codeSnippetContainerTabSingle">Python</div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAAABA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EAAABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAAABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">import</span> Rhino
<span class="highlight-keyword">import</span> scriptcontext

<span class="highlight-keyword">def</span> constrainedcopy():
    <span class="highlight-comment">#get a single closed curve</span>
    go = Rhino.Input.Custom.GetObject()
    go.SetCommandPrompt(<span class="highlight-literal">"Select curve"</span>)
    go.GeometryFilter = Rhino.DocObjects.ObjectType.Curve
    go.GeometryAttributeFilter = Rhino.Input.Custom.GeometryAttributeFilter.ClosedCurve
    go.Get()
    <span class="highlight-keyword">if</span> go.CommandResult() != Rhino.Commands.Result.Success: <span class="highlight-keyword">return</span>
    objref = go.Object(<span class="highlight-number">0</span>)
    base_curve = objref.Curve()
    first_point = objref.SelectionPoint()
    <span class="highlight-keyword">if</span> <span class="highlight-keyword">not</span> base_curve <span class="highlight-keyword">or</span> <span class="highlight-keyword">not</span> first_point.IsValid:
        <span class="highlight-keyword">return</span>
    isplanar, plane = base_curve.TryGetPlane()
    <span class="highlight-keyword">if</span> <span class="highlight-keyword">not</span> isplanar: <span class="highlight-keyword">return</span>

    gp = Rhino.Input.Custom.GetPoint()
    gp.SetCommandPrompt(<span class="highlight-literal">"Offset point"</span>)
    gp.DrawLineFromPoint(first_point, True)
    line = Rhino.Geometry.Line(first_point, first_point + plane.Normal)
    gp.Constrain(line)
    gp.Get()
    <span class="highlight-keyword">if</span> gp.CommandResult() != Rhino.Commands.Result.Success:
        <span class="highlight-keyword">return</span>
    second_point = gp.Point()
    vec = second_point - first_point
    <span class="highlight-keyword">if</span> vec.Length &gt; <span class="highlight-number">0.001</span>:
        xf = Rhino.Geometry.Transform.Translation(vec)
        id = scriptcontext.doc.Objects.Transform(objref, xf, False)
        scriptcontext.doc.Views.Redraw()
        <span class="highlight-keyword">return</span> id

<span class="highlight-keyword">if</span> __name__==<span class="highlight-literal">"__main__"</span>:
    constrainedcopy()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAAABA");</script></div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Version Information</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Rhino for Mac</h4>Supported in: 5.4<br /><h4 class="subHeading">Rhino for Windows</h4>Supported in: 7.0<br /></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID4RB')" onkeypress="SectionExpandCollapse_CheckKey('ID4RB', event)" tabindex="0"><img id="ID4RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID4RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_DocObjects_ObjRef.htm">ObjRef Class</a></div><div class="seeAlsoStyle"><a href="N_Rhino_DocObjects.htm">Rhino.DocObjects Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Rhino 7.0.19298.18110 (Last updated: 10/25/2019)<br />Copyright © 2009-2019 Robert McNeel &amp; Associates<p><a href="https://discourse.mcneel.com/c/rhino-developer" target="_blank">Report wishes and bugs at discourse.mcneel.com</a></p> </div></body></html>