<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>NurbsCurve.Create Method </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="Create method" /><meta name="System.Keywords" content="NurbsCurve.Create method" /><meta name="Microsoft.Help.F1" content="Rhino.Geometry.NurbsCurve.Create" /><meta name="Microsoft.Help.Id" content="M:Rhino.Geometry.NurbsCurve.Create(System.Boolean,System.Int32,System.Collections.Generic.IEnumerable{Rhino.Geometry.Point3d})" /><meta name="Description" content="Constructs a 3D NURBS curve from a list of control points." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Geometry" /><meta name="file" content="M_Rhino_Geometry_NurbsCurve_Create" /><meta name="guid" content="M_Rhino_Geometry_NurbsCurve_Create" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.3.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon API<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="RhinoCommon API" tocid="roottoc">RhinoCommon API</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="Namespaces" tocid="R_Project_RhinoCommon">Namespaces</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Rhino_Geometry.htm" title="Rhino.Geometry" tocid="N_Rhino_Geometry">Rhino.Geometry</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Rhino_Geometry_NurbsCurve.htm" title="NurbsCurve Class" tocid="T_Rhino_Geometry_NurbsCurve">NurbsCurve Class</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Methods_T_Rhino_Geometry_NurbsCurve.htm" title="NurbsCurve Methods" tocid="Methods_T_Rhino_Geometry_NurbsCurve">NurbsCurve Methods</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_Append.htm" title="Append Method " tocid="M_Rhino_Geometry_NurbsCurve_Append">Append Method </a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_Create.htm" title="Create Method " tocid="M_Rhino_Geometry_NurbsCurve_Create">Create Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_NurbsCurve_CreateFromArc.htm" title="CreateFromArc Method " tocid="Overload_Rhino_Geometry_NurbsCurve_CreateFromArc">CreateFromArc Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_NurbsCurve_CreateFromCircle.htm" title="CreateFromCircle Method " tocid="Overload_Rhino_Geometry_NurbsCurve_CreateFromCircle">CreateFromCircle Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_CreateFromEllipse.htm" title="CreateFromEllipse Method " tocid="M_Rhino_Geometry_NurbsCurve_CreateFromEllipse">CreateFromEllipse Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_CreateFromLine.htm" title="CreateFromLine Method " tocid="M_Rhino_Geometry_NurbsCurve_CreateFromLine">CreateFromLine Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_NurbsCurve_CreateHSpline.htm" title="CreateHSpline Method " tocid="Overload_Rhino_Geometry_NurbsCurve_CreateHSpline">CreateHSpline Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_CreateParabolaFromFocus.htm" title="CreateParabolaFromFocus Method " tocid="M_Rhino_Geometry_NurbsCurve_CreateParabolaFromFocus">CreateParabolaFromFocus Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_CreateParabolaFromVertex.htm" title="CreateParabolaFromVertex Method " tocid="M_Rhino_Geometry_NurbsCurve_CreateParabolaFromVertex">CreateParabolaFromVertex Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_CreatePlanarRailFrames.htm" title="CreatePlanarRailFrames Method " tocid="M_Rhino_Geometry_NurbsCurve_CreatePlanarRailFrames">CreatePlanarRailFrames Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_CreateRailFrames.htm" title="CreateRailFrames Method " tocid="M_Rhino_Geometry_NurbsCurve_CreateRailFrames">CreateRailFrames Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_NurbsCurve_CreateSpiral.htm" title="CreateSpiral Method " tocid="Overload_Rhino_Geometry_NurbsCurve_CreateSpiral">CreateSpiral Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_NurbsCurve_CreateSubDFriendly.htm" title="CreateSubDFriendly Method " tocid="Overload_Rhino_Geometry_NurbsCurve_CreateSubDFriendly">CreateSubDFriendly Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_EpsilonEquals.htm" title="EpsilonEquals Method " tocid="M_Rhino_Geometry_NurbsCurve_EpsilonEquals">EpsilonEquals Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_GrevilleParameter.htm" title="GrevilleParameter Method " tocid="M_Rhino_Geometry_NurbsCurve_GrevilleParameter">GrevilleParameter Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_GrevilleParameters.htm" title="GrevilleParameters Method " tocid="M_Rhino_Geometry_NurbsCurve_GrevilleParameters">GrevilleParameters Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_GrevillePoint.htm" title="GrevillePoint Method " tocid="M_Rhino_Geometry_NurbsCurve_GrevillePoint">GrevillePoint Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_NurbsCurve_GrevillePoints.htm" title="GrevillePoints Method " tocid="Overload_Rhino_Geometry_NurbsCurve_GrevillePoints">GrevillePoints Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_IncreaseDegree.htm" title="IncreaseDegree Method " tocid="M_Rhino_Geometry_NurbsCurve_IncreaseDegree">IncreaseDegree Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_IsDuplicate.htm" title="IsDuplicate Method " tocid="M_Rhino_Geometry_NurbsCurve_IsDuplicate">IsDuplicate Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_MakeCompatible.htm" title="MakeCompatible Method " tocid="M_Rhino_Geometry_NurbsCurve_MakeCompatible">MakeCompatible Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_MakePiecewiseBezier.htm" title="MakePiecewiseBezier Method " tocid="M_Rhino_Geometry_NurbsCurve_MakePiecewiseBezier">MakePiecewiseBezier Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_Reparameterize.htm" title="Reparameterize Method " tocid="M_Rhino_Geometry_NurbsCurve_Reparameterize">Reparameterize Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_NurbsCurve_SetEndCondition.htm" title="SetEndCondition Method " tocid="Overload_Rhino_Geometry_NurbsCurve_SetEndCondition">SetEndCondition Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_SetGrevillePoints.htm" title="SetGrevillePoints Method " tocid="M_Rhino_Geometry_NurbsCurve_SetGrevillePoints">SetGrevillePoints Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Geometry_NurbsCurve_UVNDirectionsAt.htm" title="UVNDirectionsAt Method " tocid="M_Rhino_Geometry_NurbsCurve_UVNDirectionsAt">UVNDirectionsAt Method </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn"><h1>NurbsCurve<span id="LST1C9B4B59_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1C9B4B59_0?cpp=::|nu=.");</script>Create Method </h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            Constructs a 3D NURBS curve from a list of control points.
            </div><p> </p>
    <strong>Namespace:</strong> 
   <a href="N_Rhino_Geometry.htm">Rhino.Geometry</a><br />
    <strong>Assembly:</strong>
   RhinoCommon (in RhinoCommon.dll)<div class="since"><strong>Since:</strong> 5.0</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">static</span> <span class="identifier">NurbsCurve</span> <span class="identifier">Create</span>(
	<span class="identifier">bool</span> <span class="parameter">periodic</span>,
	<span class="identifier">int</span> <span class="parameter">degree</span>,
	<span class="identifier">IEnumerable</span>&lt;<span class="identifier">Point3d</span>&gt; <span class="parameter">points</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Shared</span> <span class="keyword">Function</span> <span class="identifier">Create</span> ( 
	<span class="parameter">periodic</span> <span class="keyword">As</span> <span class="identifier">Boolean</span>,
	<span class="parameter">degree</span> <span class="keyword">As</span> <span class="identifier">Integer</span>,
	<span class="parameter">points</span> <span class="keyword">As</span> <span class="identifier">IEnumerable</span>(<span class="keyword">Of</span> <span class="identifier">Point3d</span>)
) <span class="keyword">As</span> <span class="identifier">NurbsCurve</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">periodic</span></dt><dd>Type: <a href="https://docs.microsoft.com/dotnet/api/system.boolean" target="_blank">System<span id="LST1C9B4B59_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1C9B4B59_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Boolean</a><br />If true, create a periodic uniform curve. If false, create a clamped uniform curve.</dd><dt><span class="parameter">degree</span></dt><dd>Type: <a href="https://docs.microsoft.com/dotnet/api/system.int32" target="_blank">System<span id="LST1C9B4B59_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1C9B4B59_2?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Int32</a><br />(&gt;=1) degree=order-1.</dd><dt><span class="parameter">points</span></dt><dd>Type: <a href="https://docs.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1" target="_blank">System.Collections.Generic<span id="LST1C9B4B59_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1C9B4B59_3?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>IEnumerable</a><span id="LST1C9B4B59_4"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1C9B4B59_4?cs=&lt;|vb=(Of |cpp=&lt;|fs=&lt;'|nu=(");</script><a href="T_Rhino_Geometry_Point3d.htm">Point3d</a><span id="LST1C9B4B59_5"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST1C9B4B59_5?cs=&gt;|vb=)|cpp=&gt;|fs=&gt;|nu=)");</script><br />control vertex locations.</dd></dl><h4 class="subHeading">Return Value</h4>Type: <a href="T_Rhino_Geometry_NurbsCurve.htm">NurbsCurve</a><br />
            new NURBS curve on success
            null on error.
            </div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBBBA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBBBA','cs','1','2');return false;">C#</a></div><div id="ID0EBBBBA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBBBA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBBBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBBBBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBBBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">using</span> System;

<span class="highlight-keyword">partial</span> <span class="highlight-keyword">class</span> Examples
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">static</span> Rhino.Commands.Result AddNurbsCurve(Rhino.RhinoDoc doc)
  {
    Rhino.Collections.Point3dList points = <span class="highlight-keyword">new</span> Rhino.Collections.Point3dList(<span class="highlight-number">5</span>);
    points.Add(<span class="highlight-number">0</span>, <span class="highlight-number">0</span>, <span class="highlight-number">0</span>);
    points.Add(<span class="highlight-number">0</span>, <span class="highlight-number">2</span>, <span class="highlight-number">0</span>);
    points.Add(<span class="highlight-number">2</span>, <span class="highlight-number">3</span>, <span class="highlight-number">0</span>);
    points.Add(<span class="highlight-number">4</span>, <span class="highlight-number">2</span>, <span class="highlight-number">0</span>);
    points.Add(<span class="highlight-number">4</span>, <span class="highlight-number">0</span>, <span class="highlight-number">0</span>);
    Rhino.Geometry.NurbsCurve nc = Rhino.Geometry.NurbsCurve.Create(<span class="highlight-keyword">false</span>, <span class="highlight-number">3</span>, points);
    Rhino.Commands.Result rc = Rhino.Commands.Result.Failure;
    <span class="highlight-keyword">if</span> (nc != <span class="highlight-keyword">null</span> &amp;&amp; nc.IsValid)
    {
      <span class="highlight-keyword">if</span> (doc.Objects.AddCurve(nc) != Guid.Empty)
      {
        doc.Views.Redraw();
        rc = Rhino.Commands.Result.Success;
      }
    }
    <span class="highlight-keyword">return</span> rc;
  }
}</pre></div><div id="ID0EBBBBA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Partial</span> <span class="highlight-keyword">Class</span> Examples
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Shared</span> <span class="highlight-keyword">Function</span> AddNurbsCurve(<span class="highlight-keyword">ByVal</span> doc <span class="highlight-keyword">As</span> Rhino.RhinoDoc) <span class="highlight-keyword">As</span> Rhino.Commands.Result
    <span class="highlight-keyword">Dim</span> points <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Rhino.Collections.Point3dList(<span class="highlight-number">5</span>)
    points.Add(<span class="highlight-number">0</span>, <span class="highlight-number">0</span>, <span class="highlight-number">0</span>)
    points.Add(<span class="highlight-number">0</span>, <span class="highlight-number">2</span>, <span class="highlight-number">0</span>)
    points.Add(<span class="highlight-number">2</span>, <span class="highlight-number">3</span>, <span class="highlight-number">0</span>)
    points.Add(<span class="highlight-number">4</span>, <span class="highlight-number">2</span>, <span class="highlight-number">0</span>)
    points.Add(<span class="highlight-number">4</span>, <span class="highlight-number">0</span>, <span class="highlight-number">0</span>)
    <span class="highlight-keyword">Dim</span> nc <span class="highlight-keyword">As</span> Rhino.Geometry.NurbsCurve = Rhino.Geometry.NurbsCurve.Create(<span class="highlight-keyword">False</span>, <span class="highlight-number">3</span>, points)
    <span class="highlight-keyword">Dim</span> rc <span class="highlight-keyword">As</span> Rhino.Commands.Result = Rhino.Commands.Result.Failure
    <span class="highlight-keyword">If</span> nc <span class="highlight-keyword">IsNot</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">AndAlso</span> nc.IsValid <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">If</span> doc.Objects.AddCurve(nc) &lt;&gt; Guid.Empty <span class="highlight-keyword">Then</span>
        doc.Views.Redraw()
        rc = Rhino.Commands.Result.Success
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
    <span class="highlight-keyword">Return</span> rc
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBBBA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EAABBA_tab1" class="codeSnippetContainerTabSingle">Python</div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAABBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EAABBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAABBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">import</span> Rhino
<span class="highlight-keyword">import</span> scriptcontext
<span class="highlight-keyword">import</span> System.Guid

<span class="highlight-keyword">def</span> AddNurbsCurve():
    points = Rhino.Collections.Point3dList(<span class="highlight-number">5</span>)
    points.Add(<span class="highlight-number">0</span>, <span class="highlight-number">0</span>, <span class="highlight-number">0</span>)
    points.Add(<span class="highlight-number">0</span>, <span class="highlight-number">2</span>, <span class="highlight-number">0</span>)
    points.Add(<span class="highlight-number">2</span>, <span class="highlight-number">3</span>, <span class="highlight-number">0</span>)
    points.Add(<span class="highlight-number">4</span>, <span class="highlight-number">2</span>, <span class="highlight-number">0</span>)
    points.Add(<span class="highlight-number">4</span>, <span class="highlight-number">0</span>, <span class="highlight-number">0</span>)

    nc = Rhino.Geometry.NurbsCurve.Create(False, <span class="highlight-number">3</span>, points)
    rc = Rhino.Commands.Result.Failure
    <span class="highlight-keyword">if</span> nc <span class="highlight-keyword">and</span> nc.IsValid:
        <span class="highlight-keyword">if</span> scriptcontext.doc.Objects.AddCurve(nc)!=System.Guid.Empty:
            scriptcontext.doc.Views.Redraw()
            rc = Rhino.Commands.Result.Success
    <span class="highlight-keyword">return</span> rc

<span class="highlight-keyword">if</span> __name__==<span class="highlight-literal">"__main__"</span>:
    AddNurbsCurve()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAABBA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_Geometry_NurbsCurve.htm">NurbsCurve Class</a></div><div class="seeAlsoStyle"><a href="N_Rhino_Geometry.htm">Rhino.Geometry Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Rhino 7.16.22067.13000 (Last updated: 3/10/2022)<br />Copyright © 2009-2022 Robert McNeel &amp; Associates<p><a href="https://discourse.mcneel.com/c/rhino-developer" target="_blank">Report wishes and bugs at discourse.mcneel.com</a></p> </div></body></html>