<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>RhinoPageView.SetActiveDetail Method (Guid)</title><meta name="Language" content="en-us" /><meta name="Microsoft.Help.Id" content="M:Rhino.Display.RhinoPageView.SetActiveDetail(System.Guid)" /><meta name="Description" content="Sets the active detail." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Display" /><meta name="file" content="M_Rhino_Display_RhinoPageView_SetActiveDetail" /><meta name="guid" content="M_Rhino_Display_RhinoPageView_SetActiveDetail" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.3.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon API<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="RhinoCommon API" tocid="roottoc">RhinoCommon API</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="Namespaces" tocid="R_Project_RhinoCommon">Namespaces</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Rhino_Display.htm" title="Rhino.Display" tocid="N_Rhino_Display">Rhino.Display</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Rhino_Display_RhinoPageView.htm" title="RhinoPageView Class" tocid="T_Rhino_Display_RhinoPageView">RhinoPageView Class</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Methods_T_Rhino_Display_RhinoPageView.htm" title="RhinoPageView Methods" tocid="Methods_T_Rhino_Display_RhinoPageView">RhinoPageView Methods</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Display_RhinoPageView_SetActiveDetail.htm" title="SetActiveDetail Method " tocid="Overload_Rhino_Display_RhinoPageView_SetActiveDetail">SetActiveDetail Method </a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Display_RhinoPageView_SetActiveDetail.htm" title="SetActiveDetail Method (Guid)" tocid="M_Rhino_Display_RhinoPageView_SetActiveDetail">SetActiveDetail Method (Guid)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/M_Rhino_Display_RhinoPageView_SetActiveDetail_1.htm" title="SetActiveDetail Method (String, Boolean)" tocid="M_Rhino_Display_RhinoPageView_SetActiveDetail_1">SetActiveDetail Method (String, Boolean)</a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn"><h1>RhinoPageView<span id="LST8FC1EBB1_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST8FC1EBB1_0?cpp=::|nu=.");</script>SetActiveDetail Method (Guid)</h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            Sets the active detail. 
            </div><p> </p>
    <strong>Namespace:</strong> 
   <a href="N_Rhino_Display.htm">Rhino.Display</a><br />
    <strong>Assembly:</strong>
   RhinoCommon (in RhinoCommon.dll)<div class="since"><strong>Since:</strong> 5.0</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">bool</span> <span class="identifier">SetActiveDetail</span>(
	<span class="identifier">Guid</span> <span class="parameter">detailId</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Function</span> <span class="identifier">SetActiveDetail</span> ( 
	<span class="parameter">detailId</span> <span class="keyword">As</span> <span class="identifier">Guid</span>
) <span class="keyword">As</span> <span class="identifier">Boolean</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">detailId</span></dt><dd>Type: <a href="https://docs.microsoft.com/dotnet/api/system.guid" target="_blank">System<span id="LST8FC1EBB1_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST8FC1EBB1_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Guid</a><br />The id of the detail view object to set active.</dd></dl><h4 class="subHeading">Return Value</h4>Type: <a href="https://docs.microsoft.com/dotnet/api/system.boolean" target="_blank">Boolean</a><br />true if successful, false otherwise.</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBBBA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBBBA','cs','1','2');return false;">C#</a></div><div id="ID0EBBBBA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBBBA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBBBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBBBBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBBBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">partial</span> <span class="highlight-keyword">class</span> Examples
{
  <span class="highlight-comment">/// &lt;summary&gt;</span>
  <span class="highlight-comment">/// Generate a layout with a single detail view that zooms to a list of objects</span>
  <span class="highlight-comment">/// &lt;/summary&gt;</span>
  <span class="highlight-comment">/// &lt;param name="doc"&gt;&lt;/param&gt;</span>
  <span class="highlight-comment">/// &lt;returns&gt;&lt;/returns&gt;</span>
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">static</span> Rhino.Commands.Result AddLayout(Rhino.RhinoDoc doc)
  {
    doc.PageUnitSystem = Rhino.UnitSystem.Millimeters;
    <span class="highlight-keyword">var</span> page_views = doc.Views.GetPageViews();
    <span class="highlight-keyword">int</span> page_number = (page_views==<span class="highlight-keyword">null</span>) ? <span class="highlight-number">1</span> : page_views.Length + <span class="highlight-number">1</span>;
    <span class="highlight-keyword">var</span> pageview = doc.Views.AddPageView(<span class="highlight-keyword">string</span>.Format(<span class="highlight-literal">"A0_{0}"</span>,page_number), <span class="highlight-number">1189</span>, <span class="highlight-number">841</span>);
    <span class="highlight-keyword">if</span>( pageview!=<span class="highlight-keyword">null</span> )
    {
      Rhino.Geometry.Point2d top_left = <span class="highlight-keyword">new</span> Rhino.Geometry.Point2d(<span class="highlight-number">20</span>,<span class="highlight-number">821</span>);
      Rhino.Geometry.Point2d bottom_right = <span class="highlight-keyword">new</span> Rhino.Geometry.Point2d(<span class="highlight-number">1169</span>, <span class="highlight-number">20</span>);
      <span class="highlight-keyword">var</span> detail = pageview.AddDetailView(<span class="highlight-literal">"ModelView"</span>, top_left, bottom_right, Rhino.Display.DefinedViewportProjection.Top);
      <span class="highlight-keyword">if</span> (detail != <span class="highlight-keyword">null</span>)
      {
        pageview.SetActiveDetail(detail.Id);
        detail.Viewport.ZoomExtents();
        detail.DetailGeometry.IsProjectionLocked = <span class="highlight-keyword">true</span>;
        detail.DetailGeometry.SetScale(<span class="highlight-number">1</span>, doc.ModelUnitSystem, <span class="highlight-number">10</span>, doc.PageUnitSystem);
        <span class="highlight-comment">// Commit changes tells the document to replace the document's detail object</span>
        <span class="highlight-comment">// with the modified one that we just adjusted</span>
        detail.CommitChanges();
      }
      pageview.SetPageAsActive();
      doc.Views.ActiveView = pageview;
      doc.Views.Redraw();
      <span class="highlight-keyword">return</span> Rhino.Commands.Result.Success;
    }
    <span class="highlight-keyword">return</span> Rhino.Commands.Result.Failure;
  }
}</pre></div><div id="ID0EBBBBA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Partial</span> <span class="highlight-keyword">Class</span> Examples
  <span class="highlight-comment">''' &lt;summary&gt;</span>
  <span class="highlight-comment">''' Generate a layout with a single detail view that zooms to a list of objects</span>
  <span class="highlight-comment">''' &lt;/summary&gt;</span>
  <span class="highlight-comment">''' &lt;param name="doc"&gt;&lt;/param&gt;</span>
  <span class="highlight-comment">''' &lt;returns&gt;&lt;/returns&gt;</span>
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Shared</span> <span class="highlight-keyword">Function</span> AddLayout(doc <span class="highlight-keyword">As</span> Rhino.RhinoDoc) <span class="highlight-keyword">As</span> Rhino.Commands.Result
    doc.PageUnitSystem = Rhino.UnitSystem.Millimeters
    <span class="highlight-keyword">Dim</span> page_views = doc.Views.GetPageViews()
    <span class="highlight-keyword">Dim</span> page_number <span class="highlight-keyword">As</span> <span class="highlight-keyword">Integer</span> = <span class="highlight-keyword">If</span>((page_views <span class="highlight-keyword">Is</span> <span class="highlight-keyword">Nothing</span>), <span class="highlight-number">1</span>, page_views.Length + <span class="highlight-number">1</span>)
    <span class="highlight-keyword">Dim</span> pageview = doc.Views.AddPageView(<span class="highlight-keyword">String</span>.Format(<span class="highlight-literal">"A0_{0}"</span>, page_number), <span class="highlight-number">1189</span>, <span class="highlight-number">841</span>)
    <span class="highlight-keyword">If</span> pageview <span class="highlight-keyword">IsNot</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">Dim</span> top_left <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Rhino.Geometry.Point2d(<span class="highlight-number">20</span>, <span class="highlight-number">821</span>)
      <span class="highlight-keyword">Dim</span> bottom_right <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Rhino.Geometry.Point2d(<span class="highlight-number">1169</span>, <span class="highlight-number">20</span>)
      <span class="highlight-keyword">Dim</span> detail = pageview.AddDetailView(<span class="highlight-literal">"ModelView"</span>, top_left, bottom_right, Rhino.Display.DefinedViewportProjection.Top)
      <span class="highlight-keyword">If</span> detail <span class="highlight-keyword">IsNot</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">Then</span>
        pageview.SetActiveDetail(detail.Id)
        detail.Viewport.ZoomExtents()
        detail.DetailGeometry.IsProjectionLocked = <span class="highlight-keyword">True</span>
        detail.DetailGeometry.SetScale(<span class="highlight-number">1</span>, doc.ModelUnitSystem, <span class="highlight-number">10</span>, doc.PageUnitSystem)
        <span class="highlight-comment">' Commit changes tells the document to replace the document's detail object</span>
        <span class="highlight-comment">' with the modified one that we just adjusted</span>
        detail.CommitChanges()
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
      pageview.SetPageAsActive()
      doc.Views.ActiveView = pageview
      doc.Views.Redraw()
      <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Success
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
    <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Failure
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBBBA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EAABBA_tab1" class="codeSnippetContainerTabSingle">Python</div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAABBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EAABBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAABBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">import</span> Rhino
<span class="highlight-keyword">import</span> scriptcontext

<span class="highlight-comment"># Generate a layout with a single detail view that zooms</span>
<span class="highlight-comment"># to a list of objects</span>
<span class="highlight-keyword">def</span> AddLayout():
    scriptcontext.doc.PageUnitSystem = Rhino.UnitSystem.Millimeters
    page_views = scriptcontext.doc.Views.GetPageViews()
    page_number = <span class="highlight-number">1</span>
    <span class="highlight-keyword">if</span> page_views: page_number = len(page_views) + <span class="highlight-number">1</span>
    pageview = scriptcontext.doc.Views.AddPageView(<span class="highlight-literal">"A0_{0}"</span>.format(page_number), <span class="highlight-number">1189</span>, <span class="highlight-number">841</span>)
    <span class="highlight-keyword">if</span> pageview:
        top_left = Rhino.Geometry.Point2d(<span class="highlight-number">20</span>,<span class="highlight-number">821</span>)
        bottom_right = Rhino.Geometry.Point2d(<span class="highlight-number">1169</span>, <span class="highlight-number">20</span>)
        detail = pageview.AddDetailView(<span class="highlight-literal">"ModelView"</span>, top_left, bottom_right, Rhino.Display.DefinedViewportProjection.Top)
        <span class="highlight-keyword">if</span> detail:
            pageview.SetActiveDetail(detail.Id)
            detail.Viewport.ZoomExtents()
            detail.DetailGeometry.IsProjectionLocked = True
            detail.DetailGeometry.SetScale(<span class="highlight-number">1</span>, scriptcontext.doc.ModelUnitSystem, <span class="highlight-number">10</span>, scriptcontext.doc.PageUnitSystem)
            <span class="highlight-comment"># Commit changes tells the document to replace the document's detail object</span>
            <span class="highlight-comment"># with the modified one that we just adjusted</span>
            detail.CommitChanges()
        pageview.SetPageAsActive()
        scriptcontext.doc.Views.ActiveView = pageview
        scriptcontext.doc.Views.Redraw()

<span class="highlight-keyword">if</span> __name__==<span class="highlight-literal">"__main__"</span>:
    AddLayout()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAABBA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_Display_RhinoPageView.htm">RhinoPageView Class</a></div><div class="seeAlsoStyle"><a href="Overload_Rhino_Display_RhinoPageView_SetActiveDetail.htm">SetActiveDetail Overload</a></div><div class="seeAlsoStyle"><a href="N_Rhino_Display.htm">Rhino.Display Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Rhino 7.18.22124.03000 (Last updated: 5/10/2022)<br />Copyright © 2009-2022 Robert McNeel &amp; Associates<p><a href="https://discourse.mcneel.com/c/rhino-developer" target="_blank">Report wishes and bugs at discourse.mcneel.com</a></p> </div></body></html>