<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>RevSurface.Create Method (Curve, Line)</title><meta name="Language" content="en-us" /><meta name="Microsoft.Help.Id" content="M:Rhino.Geometry.RevSurface.Create(Rhino.Geometry.Curve,Rhino.Geometry.Line)" /><meta name="Description" content="Constructs a new surface of revolution from a generatrix curve and an axis." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Geometry" /><meta name="file" content="M_Rhino_Geometry_RevSurface_Create" /><meta name="guid" content="M_Rhino_Geometry_RevSurface_Create" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-1.11.0.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon SDK<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino.htm" title="RhinoCommon SDK" tocid="roottoc">RhinoCommon SDK</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino_Geometry.htm" title="Rhino.Geometry" tocid="N_Rhino_Geometry">Rhino.Geometry</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="T_Rhino_Geometry_RevSurface.htm" title="RevSurface Class" tocid="T_Rhino_Geometry_RevSurface">RevSurface Class</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Methods_T_Rhino_Geometry_RevSurface.htm" title="RevSurface Methods" tocid="Methods_T_Rhino_Geometry_RevSurface">RevSurface Methods</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Overload_Rhino_Geometry_RevSurface_Create.htm" title="Create Method " tocid="Overload_Rhino_Geometry_RevSurface_Create">Create Method </a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_RevSurface_Create.htm" title="Create Method (Curve, Line)" tocid="M_Rhino_Geometry_RevSurface_Create">Create Method (Curve, Line)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_RevSurface_Create_2.htm" title="Create Method (Line, Line)" tocid="M_Rhino_Geometry_RevSurface_Create_2">Create Method (Line, Line)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_RevSurface_Create_4.htm" title="Create Method (Polyline, Line)" tocid="M_Rhino_Geometry_RevSurface_Create_4">Create Method (Polyline, Line)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_RevSurface_Create_1.htm" title="Create Method (Curve, Line, Double, Double)" tocid="M_Rhino_Geometry_RevSurface_Create_1">Create Method (Curve, Line, Double, Double)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_RevSurface_Create_3.htm" title="Create Method (Line, Line, Double, Double)" tocid="M_Rhino_Geometry_RevSurface_Create_3">Create Method (Line, Line, Double, Double)</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_RevSurface_Create_5.htm" title="Create Method (Polyline, Line, Double, Double)" tocid="M_Rhino_Geometry_RevSurface_Create_5">Create Method (Polyline, Line, Double, Double)</a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn">RevSurface<span id="LSTB4418301_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTB4418301_0?cpp=::|nu=.");</script>Create Method (Curve, Line)</td></tr></table><span class="introStyle">Rhino 5 for Windows</span><div class="summary">
            Constructs a new surface of revolution from a generatrix curve and an axis.
            </div><p> </p><strong>Namespace:</strong> <a href="N_Rhino_Geometry.htm">Rhino.Geometry</a><br /><strong>Assembly:</strong> RhinoCommon (in RhinoCommon.dll) Version: 5.1.30000.16 (5.0.20693.0)<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">static</span> <span class="identifier">RevSurface</span> <span class="identifier">Create</span>(
	<span class="identifier">Curve</span> <span class="parameter">revoluteCurve</span>,
	<span class="identifier">Line</span> <span class="parameter">axisOfRevolution</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Shared</span> <span class="keyword">Function</span> <span class="identifier">Create</span> ( 
	<span class="parameter">revoluteCurve</span> <span class="keyword">As</span> <span class="identifier">Curve</span>,
	<span class="parameter">axisOfRevolution</span> <span class="keyword">As</span> <span class="identifier">Line</span>
) <span class="keyword">As</span> <span class="identifier">RevSurface</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">revoluteCurve</span></dt><dd>Type: <a href="T_Rhino_Geometry_Curve.htm">Rhino.Geometry<span id="LSTB4418301_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTB4418301_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Curve</a><br />A generatrix.</dd><dt><span class="parameter">axisOfRevolution</span></dt><dd>Type: <a href="T_Rhino_Geometry_Line.htm">Rhino.Geometry<span id="LSTB4418301_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTB4418301_2?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Line</a><br />An axis.</dd></dl><h4 class="subHeading">Return Value</h4>Type: <a href="T_Rhino_Geometry_RevSurface.htm">RevSurface</a><br />A new surface of revolution, or null if any of the inputs is invalid or on error.</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBABA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','cs','1','2');return false;">C#</a></div><div id="ID0EBBABA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBBABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">using</span> System;
<span class="highlight-keyword">using</span> Rhino.Geometry;

<span class="highlight-keyword">partial</span> <span class="highlight-keyword">class</span> Examples
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">static</span> Rhino.Commands.Result AddTruncatedCone(Rhino.RhinoDoc doc)
  {
    Point3d bottom_pt = <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">0</span>,<span class="highlight-number">0</span>,<span class="highlight-number">0</span>);
    <span class="highlight-keyword">const</span> <span class="highlight-keyword">double</span> bottom_radius = <span class="highlight-number">2</span>;
    Circle bottom_circle = <span class="highlight-keyword">new</span> Circle(bottom_pt, bottom_radius);

    Point3d top_pt = <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">0</span>,<span class="highlight-number">0</span>,<span class="highlight-number">10</span>);
    <span class="highlight-keyword">const</span> <span class="highlight-keyword">double</span> top_radius = <span class="highlight-number">6</span>;
    Circle top_circle = <span class="highlight-keyword">new</span> Circle(top_pt, top_radius);

    LineCurve shapeCurve = <span class="highlight-keyword">new</span> LineCurve(bottom_circle.PointAt(<span class="highlight-number">0</span>), top_circle.PointAt(<span class="highlight-number">0</span>));
    Line axis = <span class="highlight-keyword">new</span> Line(bottom_circle.Center, top_circle.Center);
    RevSurface revsrf = RevSurface.Create(shapeCurve, axis);
    Brep tcone_brep = Brep.CreateFromRevSurface(revsrf, <span class="highlight-keyword">true</span>, <span class="highlight-keyword">true</span>);
    <span class="highlight-keyword">if</span>( doc.Objects.AddBrep(tcone_brep) != Guid.Empty )
    {
      doc.Views.Redraw();
      <span class="highlight-keyword">return</span> Rhino.Commands.Result.Success;
    }
    <span class="highlight-keyword">return</span> Rhino.Commands.Result.Failure;
  }
}</pre></div><div id="ID0EBBABA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Imports</span> Rhino.Geometry

<span class="highlight-keyword">Partial</span> <span class="highlight-keyword">Class</span> Examples
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Shared</span> <span class="highlight-keyword">Function</span> AddTruncatedCone(<span class="highlight-keyword">ByVal</span> doc <span class="highlight-keyword">As</span> Rhino.RhinoDoc) <span class="highlight-keyword">As</span> Rhino.Commands.Result
    <span class="highlight-keyword">Dim</span> bottom_pt <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">0</span>, <span class="highlight-number">0</span>, <span class="highlight-number">0</span>)
    <span class="highlight-keyword">Const</span> bottom_radius <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span> = <span class="highlight-number">2</span>
    <span class="highlight-keyword">Dim</span> bottom_circle <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Circle(bottom_pt, bottom_radius)

    <span class="highlight-keyword">Dim</span> top_pt <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">0</span>, <span class="highlight-number">0</span>, <span class="highlight-number">10</span>)
    <span class="highlight-keyword">Const</span> top_radius <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span> = <span class="highlight-number">6</span>
    <span class="highlight-keyword">Dim</span> top_circle <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Circle(top_pt, top_radius)

    <span class="highlight-keyword">Dim</span> shapeCurve <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> LineCurve(bottom_circle.PointAt(<span class="highlight-number">0</span>), top_circle.PointAt(<span class="highlight-number">0</span>))
    <span class="highlight-keyword">Dim</span> axis <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Line(bottom_circle.Center, top_circle.Center)
    <span class="highlight-keyword">Dim</span> revsrf <span class="highlight-keyword">As</span> RevSurface = RevSurface.Create(shapeCurve, axis)
    <span class="highlight-keyword">Dim</span> tcone_brep <span class="highlight-keyword">As</span> Brep = Brep.CreateFromRevSurface(revsrf, <span class="highlight-keyword">True</span>, <span class="highlight-keyword">True</span>)
    <span class="highlight-keyword">If</span> doc.Objects.AddBrep(tcone_brep) &lt;&gt; Guid.Empty <span class="highlight-keyword">Then</span>
      doc.Views.Redraw()
      <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Success
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
    <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Failure
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBABA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAAABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EAAABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAAABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">import</span> Rhino
<span class="highlight-keyword">import</span> scriptcontext
<span class="highlight-keyword">import</span> System.Guid

<span class="highlight-keyword">def</span> AddTruncatedCone():
    bottom_pt = Rhino.Geometry.Point3d(<span class="highlight-number">0</span>,<span class="highlight-number">0</span>,<span class="highlight-number">0</span>)
    bottom_radius = <span class="highlight-number">2</span>
    bottom_circle = Rhino.Geometry.Circle(bottom_pt, bottom_radius)

    top_pt = Rhino.Geometry.Point3d(<span class="highlight-number">0</span>,<span class="highlight-number">0</span>,<span class="highlight-number">10</span>)
    top_radius = <span class="highlight-number">6</span>
    top_circle = Rhino.Geometry.Circle(top_pt, top_radius)

    shapeCurve = Rhino.Geometry.LineCurve(bottom_circle.PointAt(<span class="highlight-number">0</span>), top_circle.PointAt(<span class="highlight-number">0</span>))
    axis = Rhino.Geometry.Line(bottom_circle.Center, top_circle.Center)
    revsrf = Rhino.Geometry.RevSurface.Create(shapeCurve, axis)
    tcone_brep = Rhino.Geometry.Brep.CreateFromRevSurface(revsrf, True, True)

    <span class="highlight-keyword">if</span> scriptcontext.doc.Objects.AddBrep(tcone_brep)!=System.Guid.Empty:
        scriptcontext.doc.Views.Redraw()
        <span class="highlight-keyword">return</span> Rhino.Commands.Result.Success
    <span class="highlight-keyword">return</span> Rhino.Commands.Result.Failure


<span class="highlight-keyword">if</span> __name__==<span class="highlight-literal">"__main__"</span>:
    AddTruncatedCone()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAAABA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_Geometry_RevSurface.htm">RevSurface Class</a></div><div class="seeAlsoStyle"><a href="Overload_Rhino_Geometry_RevSurface_Create.htm">Create Overload</a></div><div class="seeAlsoStyle"><a href="N_Rhino_Geometry.htm">Rhino.Geometry Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Updated 10 March 2016 - Robert McNeel and Associates<p><a href="http://discourse.mcneel.com/" target="_blank">Report wishes and bugs: http://discourse.mcneel.com/</a></p><div class="feedbackLink">Send comments on this topic to
        <a id="HT_MailLink" href="mailto:steve%40mcneel.com?Subject=RhinoCommon SDK">steve@mcneel.com</a></div><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title + "\u0026body=" + encodeURIComponent("Your feedback is used to improve the documentation and the product. Your e-mail address will not be used for any other purpose and is disposed of after the issue you report is resolved. While working to resolve the issue that you report, you may be contacted via e-mail to get further details or clarification on the feedback you sent. After the issue you report has been addressed, you may receive an e-mail to let you know that your feedback has been addressed.");
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script> </div></body></html>