<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>RhinoViewport.Name Property </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="Name property" /><meta name="System.Keywords" content="RhinoViewport.Name property" /><meta name="Microsoft.Help.F1" content="Rhino.Display.RhinoViewport.Name" /><meta name="Microsoft.Help.F1" content="Rhino.Display.RhinoViewport.get_Name" /><meta name="Microsoft.Help.F1" content="Rhino.Display.RhinoViewport.set_Name" /><meta name="Microsoft.Help.Id" content="P:Rhino.Display.RhinoViewport.Name" /><meta name="Description" content="Name associated with this viewport." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Display" /><meta name="file" content="P_Rhino_Display_RhinoViewport_Name" /><meta name="guid" content="P_Rhino_Display_RhinoViewport_Name" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.3.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon API<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="RhinoCommon API" tocid="roottoc">RhinoCommon API</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="Namespaces" tocid="R_Project_RhinoCommon">Namespaces</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Rhino_Display.htm" title="Rhino.Display" tocid="N_Rhino_Display">Rhino.Display</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Rhino_Display_RhinoViewport.htm" title="RhinoViewport Class" tocid="T_Rhino_Display_RhinoViewport">RhinoViewport Class</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Properties_T_Rhino_Display_RhinoViewport.htm" title="RhinoViewport Properties" tocid="Properties_T_Rhino_Display_RhinoViewport">RhinoViewport Properties</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_Bounds.htm" title="Bounds Property " tocid="P_Rhino_Display_RhinoViewport_Bounds">Bounds Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_Camera35mmLensLength.htm" title="Camera35mmLensLength Property " tocid="P_Rhino_Display_RhinoViewport_Camera35mmLensLength">Camera35mmLensLength Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_CameraDirection.htm" title="CameraDirection Property " tocid="P_Rhino_Display_RhinoViewport_CameraDirection">CameraDirection Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_CameraLocation.htm" title="CameraLocation Property " tocid="P_Rhino_Display_RhinoViewport_CameraLocation">CameraLocation Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_CameraTarget.htm" title="CameraTarget Property " tocid="P_Rhino_Display_RhinoViewport_CameraTarget">CameraTarget Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_CameraUp.htm" title="CameraUp Property " tocid="P_Rhino_Display_RhinoViewport_CameraUp">CameraUp Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_CameraX.htm" title="CameraX Property " tocid="P_Rhino_Display_RhinoViewport_CameraX">CameraX Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_CameraY.htm" title="CameraY Property " tocid="P_Rhino_Display_RhinoViewport_CameraY">CameraY Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_CameraZ.htm" title="CameraZ Property " tocid="P_Rhino_Display_RhinoViewport_CameraZ">CameraZ Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_ChangeCounter.htm" title="ChangeCounter Property " tocid="P_Rhino_Display_RhinoViewport_ChangeCounter">ChangeCounter Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_ConstructionAxesVisible.htm" title="ConstructionAxesVisible Property " tocid="P_Rhino_Display_RhinoViewport_ConstructionAxesVisible">ConstructionAxesVisible Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_ConstructionGridVisible.htm" title="ConstructionGridVisible Property " tocid="P_Rhino_Display_RhinoViewport_ConstructionGridVisible">ConstructionGridVisible Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_DisplayMode.htm" title="DisplayMode Property " tocid="P_Rhino_Display_RhinoViewport_DisplayMode">DisplayMode Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_FrustumAspect.htm" title="FrustumAspect Property " tocid="P_Rhino_Display_RhinoViewport_FrustumAspect">FrustumAspect Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_Id.htm" title="Id Property " tocid="P_Rhino_Display_RhinoViewport_Id">Id Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_IsParallelProjection.htm" title="IsParallelProjection Property " tocid="P_Rhino_Display_RhinoViewport_IsParallelProjection">IsParallelProjection Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_IsPerspectiveProjection.htm" title="IsPerspectiveProjection Property " tocid="P_Rhino_Display_RhinoViewport_IsPerspectiveProjection">IsPerspectiveProjection Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_IsPlanView.htm" title="IsPlanView Property " tocid="P_Rhino_Display_RhinoViewport_IsPlanView">IsPlanView Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_IsTwoPointPerspectiveProjection.htm" title="IsTwoPointPerspectiveProjection Property " tocid="P_Rhino_Display_RhinoViewport_IsTwoPointPerspectiveProjection">IsTwoPointPerspectiveProjection Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_IsValidCamera.htm" title="IsValidCamera Property " tocid="P_Rhino_Display_RhinoViewport_IsValidCamera">IsValidCamera Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_IsValidFrustum.htm" title="IsValidFrustum Property " tocid="P_Rhino_Display_RhinoViewport_IsValidFrustum">IsValidFrustum Property </a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_Name.htm" title="Name Property " tocid="P_Rhino_Display_RhinoViewport_Name">Name Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_ParentView.htm" title="ParentView Property " tocid="P_Rhino_Display_RhinoViewport_ParentView">ParentView Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_ScreenPortAspect.htm" title="ScreenPortAspect Property " tocid="P_Rhino_Display_RhinoViewport_ScreenPortAspect">ScreenPortAspect Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_Size.htm" title="Size Property " tocid="P_Rhino_Display_RhinoViewport_Size">Size Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_UserStringCount.htm" title="UserStringCount Property " tocid="P_Rhino_Display_RhinoViewport_UserStringCount">UserStringCount Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_ViewportType.htm" title="ViewportType Property " tocid="P_Rhino_Display_RhinoViewport_ViewportType">ViewportType Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_WallpaperFilename.htm" title="WallpaperFilename Property " tocid="P_Rhino_Display_RhinoViewport_WallpaperFilename">WallpaperFilename Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_WallpaperGrayscale.htm" title="WallpaperGrayscale Property " tocid="P_Rhino_Display_RhinoViewport_WallpaperGrayscale">WallpaperGrayscale Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_WallpaperVisible.htm" title="WallpaperVisible Property " tocid="P_Rhino_Display_RhinoViewport_WallpaperVisible">WallpaperVisible Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Display_RhinoViewport_WorldAxesVisible.htm" title="WorldAxesVisible Property " tocid="P_Rhino_Display_RhinoViewport_WorldAxesVisible">WorldAxesVisible Property </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn"><h1>RhinoViewport<span id="LSTD80D640E_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTD80D640E_0?cpp=::|nu=.");</script>Name Property </h1></td></tr></table><span class="introStyle"></span> <div class="summary">Name associated with this viewport.</div><p> </p>
    <strong>Namespace:</strong> 
   <a href="N_Rhino_Display.htm">Rhino.Display</a><br />
    <strong>Assembly:</strong>
   RhinoCommon (in RhinoCommon.dll)<div class="since"><strong>Since:</strong> 5.0</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">string</span> <span class="identifier">Name</span> { <span class="keyword">get</span>; <span class="keyword">set</span>; }</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Property</span> <span class="identifier">Name</span> <span class="keyword">As</span> <span class="identifier">String</span>
	<span class="keyword">Get</span>
	<span class="keyword">Set</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Property Value</h4>Type: <a href="https://docs.microsoft.com/dotnet/api/system.string" target="_blank">String</a></div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBBBA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBBBA','cs','1','2');return false;">C#</a></div><div id="ID0EBBBBA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBBBA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBBBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBBBBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBBBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">partial</span> <span class="highlight-keyword">class</span> Examples
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">static</span> Rhino.Commands.Result AddNamedView(Rhino.RhinoDoc doc)
  {
    Rhino.Display.RhinoView view;
    Rhino.Commands.Result rc = Rhino.Input.RhinoGet.GetView(<span class="highlight-literal">"Select view to adjust"</span>, <span class="highlight-keyword">out</span> view);
    <span class="highlight-keyword">if</span> (rc != Rhino.Commands.Result.Success)
      <span class="highlight-keyword">return</span> rc;

    Rhino.Geometry.Point3d location;
    rc = Rhino.Input.RhinoGet.GetPoint(<span class="highlight-literal">"Camera Location"</span>, <span class="highlight-keyword">false</span>, <span class="highlight-keyword">out</span> location);
    <span class="highlight-keyword">if</span> (rc != Rhino.Commands.Result.Success)
      <span class="highlight-keyword">return</span> rc;

    Rhino.Input.Custom.GetPoint gp = <span class="highlight-keyword">new</span> Rhino.Input.Custom.GetPoint();
    gp.SetCommandPrompt(<span class="highlight-literal">"Look At Location"</span>);
    gp.DrawLineFromPoint(location, <span class="highlight-keyword">false</span>);
    gp.Get();
    <span class="highlight-keyword">if</span> (gp.CommandResult() != Rhino.Commands.Result.Success)
      <span class="highlight-keyword">return</span> gp.CommandResult();
    Rhino.Geometry.Point3d lookat = gp.Point();

    <span class="highlight-keyword">string</span> name = view.ActiveViewport.Name;
    rc = Rhino.Input.RhinoGet.GetString(<span class="highlight-literal">"Name"</span>, <span class="highlight-keyword">true</span>, <span class="highlight-keyword">ref</span> name);
    <span class="highlight-keyword">if</span> (rc != Rhino.Commands.Result.Success)
      <span class="highlight-keyword">return</span> rc;

    Rhino.Display.RhinoViewport vp = view.ActiveViewport;
    <span class="highlight-comment">// save the current viewport projection</span>
    vp.PushViewProjection();
    vp.CameraUp = Rhino.Geometry.Vector3d.ZAxis;
    vp.SetCameraLocation(location, <span class="highlight-keyword">false</span>);
    vp.SetCameraDirection(lookat - location, <span class="highlight-keyword">true</span>);
    vp.Name = name;

    doc.NamedViews.Add(name, vp.Id);
    view.Redraw();
    <span class="highlight-keyword">return</span> Rhino.Commands.Result.Success;
  }
}</pre></div><div id="ID0EBBBBA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Partial</span> <span class="highlight-keyword">Class</span> Examples
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Shared</span> <span class="highlight-keyword">Function</span> AddNamedView(<span class="highlight-keyword">ByVal</span> doc <span class="highlight-keyword">As</span> Rhino.RhinoDoc) <span class="highlight-keyword">As</span> Rhino.Commands.Result
    <span class="highlight-keyword">Dim</span> view <span class="highlight-keyword">As</span> Rhino.Display.RhinoView = <span class="highlight-keyword">Nothing</span>
    <span class="highlight-keyword">Dim</span> rc <span class="highlight-keyword">As</span> Rhino.Commands.Result = Rhino.Input.RhinoGet.GetView(<span class="highlight-literal">"Select view to adjust"</span>, view)
    <span class="highlight-keyword">If</span> rc &lt;&gt; Rhino.Commands.Result.Success <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">Return</span> rc
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

    <span class="highlight-keyword">Dim</span> location <span class="highlight-keyword">As</span> Rhino.Geometry.Point3d
    rc = Rhino.Input.RhinoGet.GetPoint(<span class="highlight-literal">"Camera Location"</span>, <span class="highlight-keyword">False</span>, location)
    <span class="highlight-keyword">If</span> rc &lt;&gt; Rhino.Commands.Result.Success <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">Return</span> rc
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

    <span class="highlight-keyword">Dim</span> gp <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Rhino.Input.Custom.GetPoint()
    gp.SetCommandPrompt(<span class="highlight-literal">"Look At Location"</span>)
    gp.DrawLineFromPoint(location, <span class="highlight-keyword">False</span>)
    gp.<span class="highlight-keyword">Get</span>()
    <span class="highlight-keyword">If</span> gp.CommandResult() &lt;&gt; Rhino.Commands.Result.Success <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">Return</span> gp.CommandResult()
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
    <span class="highlight-keyword">Dim</span> lookat <span class="highlight-keyword">As</span> Rhino.Geometry.Point3d = gp.Point()

    <span class="highlight-keyword">Dim</span> name <span class="highlight-keyword">As</span> <span class="highlight-keyword">String</span> = view.ActiveViewport.Name
    rc = Rhino.Input.RhinoGet.GetString(<span class="highlight-literal">"Name"</span>, <span class="highlight-keyword">True</span>, name)
    <span class="highlight-keyword">If</span> rc &lt;&gt; Rhino.Commands.Result.Success <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">Return</span> rc
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

    <span class="highlight-keyword">Dim</span> vp <span class="highlight-keyword">As</span> Rhino.Display.RhinoViewport = view.ActiveViewport
    <span class="highlight-comment">' save the current viewport projection</span>
    vp.PushViewProjection()
    vp.CameraUp = Rhino.Geometry.Vector3d.ZAxis
    vp.SetCameraLocation(location, <span class="highlight-keyword">False</span>)
    vp.SetCameraDirection(lookat - location, <span class="highlight-keyword">True</span>)
    vp.Name = name

    doc.NamedViews.Add(name, vp.Id)
    view.Redraw()
    <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Success
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBBBA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EAABBA_tab1" class="codeSnippetContainerTabSingle">Python</div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAABBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EAABBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAABBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">import</span> Rhino
<span class="highlight-keyword">import</span> scriptcontext
<span class="highlight-keyword">import</span> System.Guid

<span class="highlight-keyword">def</span> AddNamedView():
    rc, view = Rhino.Input.RhinoGet.GetView(<span class="highlight-literal">"Select view to adjust"</span>)
    <span class="highlight-keyword">if</span> rc!=Rhino.Commands.Result.Success: <span class="highlight-keyword">return</span> rc

    rc, location = Rhino.Input.RhinoGet.GetPoint(<span class="highlight-literal">"Camera Location"</span>, False)
    <span class="highlight-keyword">if</span> rc!=Rhino.Commands.Result.Success: <span class="highlight-keyword">return</span> rc

    gp = Rhino.Input.Custom.GetPoint()
    gp.SetCommandPrompt(<span class="highlight-literal">"Look At Location"</span>)
    gp.DrawLineFromPoint(location, False)
    gp.Get()
    <span class="highlight-keyword">if</span> gp.CommandResult()!=Rhino.Commands.Result.Success:
        <span class="highlight-keyword">return</span> gp.CommandResult()
    lookat = gp.Point()

    name = view.ActiveViewport.Name
    rc, name = Rhino.Input.RhinoGet.GetString(<span class="highlight-literal">"Name"</span>, True, name)
    <span class="highlight-keyword">if</span> rc!=Rhino.Commands.Result.Success: <span class="highlight-keyword">return</span> rc

    vp = view.ActiveViewport
    <span class="highlight-comment"># save the current viewport projection</span>
    vp.PushViewProjection()
    vp.CameraUp = Rhino.Geometry.Vector3d.ZAxis
    vp.SetCameraLocation(location, False)
    vp.SetCameraDirection(lookat - location, True)
    vp.Name = name

    scriptcontext.doc.NamedViews.Add(name, vp.Id)
    view.Redraw()
    <span class="highlight-keyword">return</span> Rhino.Commands.Result.Success

<span class="highlight-keyword">if</span> __name__==<span class="highlight-literal">"__main__"</span>:
    AddNamedView()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAABBA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_Display_RhinoViewport.htm">RhinoViewport Class</a></div><div class="seeAlsoStyle"><a href="N_Rhino_Display.htm">Rhino.Display Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Rhino 7.17.22102.05000 (Last updated: 4/21/2022)<br />Copyright © 2009-2022 Robert McNeel &amp; Associates<p><a href="https://discourse.mcneel.com/c/rhino-developer" target="_blank">Report wishes and bugs at discourse.mcneel.com</a></p> </div></body></html>