<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>ObjectAttributes.ObjectColor Property </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="ObjectColor property" /><meta name="System.Keywords" content="ObjectAttributes.ObjectColor property" /><meta name="Microsoft.Help.F1" content="Rhino.DocObjects.ObjectAttributes.ObjectColor" /><meta name="Microsoft.Help.F1" content="Rhino.DocObjects.ObjectAttributes.get_ObjectColor" /><meta name="Microsoft.Help.F1" content="Rhino.DocObjects.ObjectAttributes.set_ObjectColor" /><meta name="Microsoft.Help.Id" content="P:Rhino.DocObjects.ObjectAttributes.ObjectColor" /><meta name="Description" content="If ON::color_from_object == ColorSource, then color is the object's display color." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.DocObjects" /><meta name="file" content="P_Rhino_DocObjects_ObjectAttributes_ObjectColor" /><meta name="guid" content="P_Rhino_DocObjects_ObjectAttributes_ObjectColor" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.3.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon API<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="RhinoCommon API" tocid="roottoc">RhinoCommon API</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="Namespaces" tocid="R_Project_RhinoCommon">Namespaces</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Rhino_DocObjects.htm" title="Rhino.DocObjects" tocid="N_Rhino_DocObjects">Rhino.DocObjects</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Rhino_DocObjects_ObjectAttributes.htm" title="ObjectAttributes Class" tocid="T_Rhino_DocObjects_ObjectAttributes">ObjectAttributes Class</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Properties_T_Rhino_DocObjects_ObjectAttributes.htm" title="ObjectAttributes Properties" tocid="Properties_T_Rhino_DocObjects_ObjectAttributes">ObjectAttributes Properties</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_CastsShadows.htm" title="CastsShadows Property " tocid="P_Rhino_DocObjects_ObjectAttributes_CastsShadows">CastsShadows Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_ColorSource.htm" title="ColorSource Property " tocid="P_Rhino_DocObjects_ObjectAttributes_ColorSource">ColorSource Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_CustomMeshingParameters.htm" title="CustomMeshingParameters Property " tocid="P_Rhino_DocObjects_ObjectAttributes_CustomMeshingParameters">CustomMeshingParameters Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_Decals.htm" title="Decals Property " tocid="P_Rhino_DocObjects_ObjectAttributes_Decals">Decals Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_DisplayOrder.htm" title="DisplayOrder Property " tocid="P_Rhino_DocObjects_ObjectAttributes_DisplayOrder">DisplayOrder Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_GroupCount.htm" title="GroupCount Property " tocid="P_Rhino_DocObjects_ObjectAttributes_GroupCount">GroupCount Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_HasMapping.htm" title="HasMapping Property " tocid="P_Rhino_DocObjects_ObjectAttributes_HasMapping">HasMapping Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_IsDocumentControlled.htm" title="IsDocumentControlled Property " tocid="P_Rhino_DocObjects_ObjectAttributes_IsDocumentControlled">IsDocumentControlled Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_IsInstanceDefinitionObject.htm" title="IsInstanceDefinitionObject Property " tocid="P_Rhino_DocObjects_ObjectAttributes_IsInstanceDefinitionObject">IsInstanceDefinitionObject Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_LayerIndex.htm" title="LayerIndex Property " tocid="P_Rhino_DocObjects_ObjectAttributes_LayerIndex">LayerIndex Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_LinetypeIndex.htm" title="LinetypeIndex Property " tocid="P_Rhino_DocObjects_ObjectAttributes_LinetypeIndex">LinetypeIndex Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_LinetypeSource.htm" title="LinetypeSource Property " tocid="P_Rhino_DocObjects_ObjectAttributes_LinetypeSource">LinetypeSource Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_MaterialIndex.htm" title="MaterialIndex Property " tocid="P_Rhino_DocObjects_ObjectAttributes_MaterialIndex">MaterialIndex Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_MaterialRefs.htm" title="MaterialRefs Property " tocid="P_Rhino_DocObjects_ObjectAttributes_MaterialRefs">MaterialRefs Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_MaterialSource.htm" title="MaterialSource Property " tocid="P_Rhino_DocObjects_ObjectAttributes_MaterialSource">MaterialSource Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_Mode.htm" title="Mode Property " tocid="P_Rhino_DocObjects_ObjectAttributes_Mode">Mode Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_Name.htm" title="Name Property " tocid="P_Rhino_DocObjects_ObjectAttributes_Name">Name Property </a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_ObjectColor.htm" title="ObjectColor Property " tocid="P_Rhino_DocObjects_ObjectAttributes_ObjectColor">ObjectColor Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_ObjectDecoration.htm" title="ObjectDecoration Property " tocid="P_Rhino_DocObjects_ObjectAttributes_ObjectDecoration">ObjectDecoration Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_ObjectId.htm" title="ObjectId Property " tocid="P_Rhino_DocObjects_ObjectAttributes_ObjectId">ObjectId Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_PlotColor.htm" title="PlotColor Property " tocid="P_Rhino_DocObjects_ObjectAttributes_PlotColor">PlotColor Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_PlotColorSource.htm" title="PlotColorSource Property " tocid="P_Rhino_DocObjects_ObjectAttributes_PlotColorSource">PlotColorSource Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_PlotWeight.htm" title="PlotWeight Property " tocid="P_Rhino_DocObjects_ObjectAttributes_PlotWeight">PlotWeight Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_PlotWeightSource.htm" title="PlotWeightSource Property " tocid="P_Rhino_DocObjects_ObjectAttributes_PlotWeightSource">PlotWeightSource Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_ReceivesShadows.htm" title="ReceivesShadows Property " tocid="P_Rhino_DocObjects_ObjectAttributes_ReceivesShadows">ReceivesShadows Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_RenderMaterial.htm" title="RenderMaterial Property " tocid="P_Rhino_DocObjects_ObjectAttributes_RenderMaterial">RenderMaterial Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_Space.htm" title="Space Property " tocid="P_Rhino_DocObjects_ObjectAttributes_Space">Space Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_Url.htm" title="Url Property " tocid="P_Rhino_DocObjects_ObjectAttributes_Url">Url Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_UserStringCount.htm" title="UserStringCount Property " tocid="P_Rhino_DocObjects_ObjectAttributes_UserStringCount">UserStringCount Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_ViewportId.htm" title="ViewportId Property " tocid="P_Rhino_DocObjects_ObjectAttributes_ViewportId">ViewportId Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_Visible.htm" title="Visible Property " tocid="P_Rhino_DocObjects_ObjectAttributes_Visible">Visible Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_DocObjects_ObjectAttributes_WireDensity.htm" title="WireDensity Property " tocid="P_Rhino_DocObjects_ObjectAttributes_WireDensity">WireDensity Property </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn"><h1>ObjectAttributes<span id="LST23838DDB_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST23838DDB_0?cpp=::|nu=.");</script>ObjectColor Property </h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            If ON::color_from_object == ColorSource, then color is the object's display color.
            </div><p> </p>
    <strong>Namespace:</strong> 
   <a href="N_Rhino_DocObjects.htm">Rhino.DocObjects</a><br />
    <strong>Assembly:</strong>
   RhinoCommon (in RhinoCommon.dll)<div class="since"><strong>Since:</strong> 5.0</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">Color</span> <span class="identifier">ObjectColor</span> { <span class="keyword">get</span>; <span class="keyword">set</span>; }</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Property</span> <span class="identifier">ObjectColor</span> <span class="keyword">As</span> <span class="identifier">Color</span>
	<span class="keyword">Get</span>
	<span class="keyword">Set</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Property Value</h4>Type: <a href="https://docs.microsoft.com/dotnet/api/system.drawing.color" target="_blank">Color</a></div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBBBA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBBBA','cs','1','2');return false;">C#</a></div><div id="ID0EBBBBA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBBBA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBBBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBBBBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBBBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">using</span> System.Drawing;
<span class="highlight-keyword">using</span> Rhino;
<span class="highlight-keyword">using</span> Rhino.DocObjects;
<span class="highlight-keyword">using</span> Rhino.Geometry;
<span class="highlight-keyword">using</span> Rhino.Input;
<span class="highlight-keyword">using</span> Rhino.Commands;

<span class="highlight-keyword">namespace</span> examples_cs
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">class</span> ModifyObjectColorCommand : Command
  {
    <span class="highlight-keyword">public</span> <span class="highlight-keyword">override</span> <span class="highlight-keyword">string</span> EnglishName { <span class="highlight-keyword">get</span> { <span class="highlight-keyword">return</span> <span class="highlight-literal">"csModifyObjectColor"</span>; } }

    <span class="highlight-keyword">protected</span> <span class="highlight-keyword">override</span> Result RunCommand(RhinoDoc doc, RunMode mode)
    {
      ObjRef obj_ref;
      <span class="highlight-keyword">var</span> rc = RhinoGet.GetOneObject(<span class="highlight-literal">"Select object"</span>, <span class="highlight-keyword">false</span>, ObjectType.AnyObject, <span class="highlight-keyword">out</span> obj_ref);
      <span class="highlight-keyword">if</span> (rc != Result.Success)
        <span class="highlight-keyword">return</span> rc;
      <span class="highlight-keyword">var</span> rhino_object = obj_ref.Object();
      <span class="highlight-keyword">var</span> color = rhino_object.Attributes.ObjectColor;
      <span class="highlight-keyword">bool</span> b = Rhino.UI.Dialogs.ShowColorDialog(<span class="highlight-keyword">ref</span> color);
      <span class="highlight-keyword">if</span> (!b) <span class="highlight-keyword">return</span> Result.Cancel;

      rhino_object.Attributes.ObjectColor = color;
      rhino_object.Attributes.ColorSource = ObjectColorSource.ColorFromObject;
      rhino_object.CommitChanges();

      <span class="highlight-comment">// an object's color attributes can also be specified</span>
      <span class="highlight-comment">// when the object is added to Rhino</span>
      <span class="highlight-keyword">var</span> sphere = <span class="highlight-keyword">new</span> Sphere(Point3d.Origin, <span class="highlight-number">5.0</span>);
      <span class="highlight-keyword">var</span> attributes = <span class="highlight-keyword">new</span> ObjectAttributes();
      attributes.ObjectColor = Color.CadetBlue;
      attributes.ColorSource = ObjectColorSource.ColorFromObject;
      doc.Objects.AddSphere(sphere, attributes);

      doc.Views.Redraw();
      <span class="highlight-keyword">return</span> Result.Success;
    }
  }
}</pre></div><div id="ID0EBBBBA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Imports</span> System.Drawing
<span class="highlight-keyword">Imports</span> Rhino
<span class="highlight-keyword">Imports</span> Rhino.DocObjects
<span class="highlight-keyword">Imports</span> Rhino.Geometry
<span class="highlight-keyword">Imports</span> Rhino.Input
<span class="highlight-keyword">Imports</span> Rhino.Commands

<span class="highlight-keyword">Namespace</span> examples_vb
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Class</span> ModifyObjectColorCommand
    <span class="highlight-keyword">Inherits</span> Command
    <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">ReadOnly</span> <span class="highlight-keyword">Property</span> EnglishName() <span class="highlight-keyword">As</span> <span class="highlight-keyword">String</span>
      <span class="highlight-keyword">Get</span>
        <span class="highlight-keyword">Return</span> <span class="highlight-literal">"vbModifyObjectColor"</span>
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">Get</span>
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Property</span>

    <span class="highlight-keyword">Protected</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">Function</span> RunCommand(doc <span class="highlight-keyword">As</span> RhinoDoc, mode <span class="highlight-keyword">As</span> RunMode) <span class="highlight-keyword">As</span> Result
      <span class="highlight-keyword">Dim</span> obj_ref <span class="highlight-keyword">As</span> ObjRef = <span class="highlight-keyword">Nothing</span>
      <span class="highlight-keyword">Dim</span> rc = RhinoGet.GetOneObject(<span class="highlight-literal">"Select object"</span>, <span class="highlight-keyword">False</span>, ObjectType.AnyObject, obj_ref)
      <span class="highlight-keyword">If</span> rc &lt;&gt; Result.Success <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> rc
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
      <span class="highlight-keyword">Dim</span> rhino_object = obj_ref.[<span class="highlight-keyword">Object</span>]()
      <span class="highlight-keyword">Dim</span> color__1 = rhino_object.Attributes.ObjectColor
      <span class="highlight-keyword">Dim</span> b <span class="highlight-keyword">As</span> <span class="highlight-keyword">Boolean</span> = Rhino.UI.Dialogs.ShowColorDialog(color__1)
      <span class="highlight-keyword">If</span> <span class="highlight-keyword">Not</span> b <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> Result.Cancel
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

      rhino_object.Attributes.ObjectColor = color__1
      rhino_object.Attributes.ColorSource = ObjectColorSource.ColorFromObject
      rhino_object.CommitChanges()

      <span class="highlight-comment">' an object's color attributes can also be specified</span>
      <span class="highlight-comment">' when the object is added to Rhino</span>
      <span class="highlight-keyword">Dim</span> sphere = <span class="highlight-keyword">New</span> Sphere(Point3d.Origin, <span class="highlight-number">5.0</span>)
      <span class="highlight-keyword">Dim</span> attributes = <span class="highlight-keyword">New</span> ObjectAttributes()
      attributes.ObjectColor = Color.CadetBlue
      attributes.ColorSource = ObjectColorSource.ColorFromObject
      doc.Objects.AddSphere(sphere, attributes)

      doc.Views.Redraw()
      <span class="highlight-keyword">Return</span> Result.Success
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Namespace</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBBBA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EAABBA_tab1" class="codeSnippetContainerTabSingle">Python</div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAABBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EAABBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAABBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">from</span> System.Drawing <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.DocObjects <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.Geometry <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.Input <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.Commands <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.UI.Dialogs <span class="highlight-keyword">import</span> ShowColorDialog
<span class="highlight-keyword">from</span> scriptcontext <span class="highlight-keyword">import</span> doc

<span class="highlight-keyword">def</span> RunCommand():
  rc, obj_ref = RhinoGet.GetOneObject(<span class="highlight-literal">"Select object"</span>, False, ObjectType.AnyObject)
  <span class="highlight-keyword">if</span> rc &lt;&gt; Result.Success:
    <span class="highlight-keyword">return</span> rc
  rhino_object = obj_ref.Object()
  color = rhino_object.Attributes.ObjectColor
  b, color = ShowColorDialog(color)
  <span class="highlight-keyword">if</span> <span class="highlight-keyword">not</span> b: <span class="highlight-keyword">return</span> Result.Cancel

  rhino_object.Attributes.ObjectColor = color
  rhino_object.Attributes.ColorSource = ObjectColorSource.ColorFromObject
  rhino_object.CommitChanges()

  <span class="highlight-comment"># an object's color attributes can also be specified</span>
  <span class="highlight-comment"># when the object is added to Rhino</span>
  sphere = Sphere(Point3d.Origin, <span class="highlight-number">5.0</span>)
  attributes = ObjectAttributes()
  attributes.ObjectColor = Color.CadetBlue
  attributes.ColorSource = ObjectColorSource.ColorFromObject
  doc.Objects.AddSphere(sphere, attributes)

  doc.Views.Redraw()
  <span class="highlight-keyword">return</span> Result.Success

<span class="highlight-keyword">if</span> __name__ == <span class="highlight-literal">"__main__"</span>:
  RunCommand()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAABBA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_DocObjects_ObjectAttributes.htm">ObjectAttributes Class</a></div><div class="seeAlsoStyle"><a href="N_Rhino_DocObjects.htm">Rhino.DocObjects Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Rhino 7.16.22067.13000 (Last updated: 3/10/2022)<br />Copyright © 2009-2022 Robert McNeel &amp; Associates<p><a href="https://discourse.mcneel.com/c/rhino-developer" target="_blank">Report wishes and bugs at discourse.mcneel.com</a></p> </div></body></html>