<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>ObjectAttributes.DisplayOrder Property </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="DisplayOrder property" /><meta name="System.Keywords" content="ObjectAttributes.DisplayOrder property" /><meta name="Microsoft.Help.F1" content="Rhino.DocObjects.ObjectAttributes.DisplayOrder" /><meta name="Microsoft.Help.F1" content="Rhino.DocObjects.ObjectAttributes.get_DisplayOrder" /><meta name="Microsoft.Help.F1" content="Rhino.DocObjects.ObjectAttributes.set_DisplayOrder" /><meta name="Microsoft.Help.Id" content="P:Rhino.DocObjects.ObjectAttributes.DisplayOrder" /><meta name="Description" content="Display order used to force objects to be drawn on top or behind each other. Larger numbers draw on top of smaller numbers." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.DocObjects" /><meta name="file" content="P_Rhino_DocObjects_ObjectAttributes_DisplayOrder" /><meta name="guid" content="P_Rhino_DocObjects_ObjectAttributes_DisplayOrder" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-1.11.0.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon SDK<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino.htm" title="RhinoCommon SDK" tocid="roottoc">RhinoCommon SDK</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino_DocObjects.htm" title="Rhino.DocObjects" tocid="N_Rhino_DocObjects">Rhino.DocObjects</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="T_Rhino_DocObjects_ObjectAttributes.htm" title="ObjectAttributes Class" tocid="T_Rhino_DocObjects_ObjectAttributes">ObjectAttributes Class</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Properties_T_Rhino_DocObjects_ObjectAttributes.htm" title="ObjectAttributes Properties" tocid="Properties_T_Rhino_DocObjects_ObjectAttributes">ObjectAttributes Properties</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_ColorSource.htm" title="ColorSource Property " tocid="P_Rhino_DocObjects_ObjectAttributes_ColorSource">ColorSource Property </a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_DisplayOrder.htm" title="DisplayOrder Property " tocid="P_Rhino_DocObjects_ObjectAttributes_DisplayOrder">DisplayOrder Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_GroupCount.htm" title="GroupCount Property " tocid="P_Rhino_DocObjects_ObjectAttributes_GroupCount">GroupCount Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_HasMapping.htm" title="HasMapping Property " tocid="P_Rhino_DocObjects_ObjectAttributes_HasMapping">HasMapping Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_IsDocumentControlled.htm" title="IsDocumentControlled Property " tocid="P_Rhino_DocObjects_ObjectAttributes_IsDocumentControlled">IsDocumentControlled Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_IsInstanceDefinitionObject.htm" title="IsInstanceDefinitionObject Property " tocid="P_Rhino_DocObjects_ObjectAttributes_IsInstanceDefinitionObject">IsInstanceDefinitionObject Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_LayerIndex.htm" title="LayerIndex Property " tocid="P_Rhino_DocObjects_ObjectAttributes_LayerIndex">LayerIndex Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_LinetypeIndex.htm" title="LinetypeIndex Property " tocid="P_Rhino_DocObjects_ObjectAttributes_LinetypeIndex">LinetypeIndex Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_LinetypeSource.htm" title="LinetypeSource Property " tocid="P_Rhino_DocObjects_ObjectAttributes_LinetypeSource">LinetypeSource Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_MaterialIndex.htm" title="MaterialIndex Property " tocid="P_Rhino_DocObjects_ObjectAttributes_MaterialIndex">MaterialIndex Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_MaterialRefs.htm" title="MaterialRefs Property " tocid="P_Rhino_DocObjects_ObjectAttributes_MaterialRefs">MaterialRefs Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_MaterialSource.htm" title="MaterialSource Property " tocid="P_Rhino_DocObjects_ObjectAttributes_MaterialSource">MaterialSource Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_Mode.htm" title="Mode Property " tocid="P_Rhino_DocObjects_ObjectAttributes_Mode">Mode Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_Name.htm" title="Name Property " tocid="P_Rhino_DocObjects_ObjectAttributes_Name">Name Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_ObjectColor.htm" title="ObjectColor Property " tocid="P_Rhino_DocObjects_ObjectAttributes_ObjectColor">ObjectColor Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_ObjectDecoration.htm" title="ObjectDecoration Property " tocid="P_Rhino_DocObjects_ObjectAttributes_ObjectDecoration">ObjectDecoration Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_ObjectId.htm" title="ObjectId Property " tocid="P_Rhino_DocObjects_ObjectAttributes_ObjectId">ObjectId Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_PlotColor.htm" title="PlotColor Property " tocid="P_Rhino_DocObjects_ObjectAttributes_PlotColor">PlotColor Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_PlotColorSource.htm" title="PlotColorSource Property " tocid="P_Rhino_DocObjects_ObjectAttributes_PlotColorSource">PlotColorSource Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_PlotWeight.htm" title="PlotWeight Property " tocid="P_Rhino_DocObjects_ObjectAttributes_PlotWeight">PlotWeight Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_PlotWeightSource.htm" title="PlotWeightSource Property " tocid="P_Rhino_DocObjects_ObjectAttributes_PlotWeightSource">PlotWeightSource Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_Space.htm" title="Space Property " tocid="P_Rhino_DocObjects_ObjectAttributes_Space">Space Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_UserStringCount.htm" title="UserStringCount Property " tocid="P_Rhino_DocObjects_ObjectAttributes_UserStringCount">UserStringCount Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_ViewportId.htm" title="ViewportId Property " tocid="P_Rhino_DocObjects_ObjectAttributes_ViewportId">ViewportId Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_Visible.htm" title="Visible Property " tocid="P_Rhino_DocObjects_ObjectAttributes_Visible">Visible Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_DocObjects_ObjectAttributes_WireDensity.htm" title="WireDensity Property " tocid="P_Rhino_DocObjects_ObjectAttributes_WireDensity">WireDensity Property </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn">ObjectAttributes<span id="LSTBB562C46_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTBB562C46_0?cpp=::|nu=.");</script>DisplayOrder Property </td></tr></table><span class="introStyle">Rhino for Mac 5.1</span><div class="summary">
            Display order used to force objects to be drawn on top or behind each other.
            Larger numbers draw on top of smaller numbers.
            <p>0  = draw object in standard depth buffered order</p><p>&lt;0 = draw object behind "normal" draw order objects</p><p>&gt;0 = draw object on top of "normal" draw order objects</p></div><p> </p><strong>Namespace:</strong> <a href="N_Rhino_DocObjects.htm">Rhino.DocObjects</a><br /><strong>Assembly:</strong> RhinoCommon (in RhinoCommon.dll) Version: 5.1.50000.0 (5.0.20693.0)<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">int</span> <span class="identifier">DisplayOrder</span> { <span class="keyword">get</span>; <span class="keyword">set</span>; }</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Property</span> <span class="identifier">DisplayOrder</span> <span class="keyword">As</span> <span class="identifier">Integer</span>
	<span class="keyword">Get</span>
	<span class="keyword">Set</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Property Value</h4>Type: <a href="http://msdn2.microsoft.com/en-us/library/td2s409d" target="_blank">Int32</a></div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBABA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','cs','1','2');return false;">C#</a></div><div id="ID0EBBABA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBBABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">using</span> System.Collections.Generic;
<span class="highlight-keyword">using</span> System.Drawing;
<span class="highlight-keyword">using</span> System.Linq;
<span class="highlight-keyword">using</span> Rhino;
<span class="highlight-keyword">using</span> Rhino.Commands;
<span class="highlight-keyword">using</span> Rhino.Display;
<span class="highlight-keyword">using</span> Rhino.Geometry;
<span class="highlight-keyword">using</span> Rhino.Input;
<span class="highlight-keyword">using</span> Rhino.DocObjects;

<span class="highlight-keyword">namespace</span> examples_cs
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">class</span> DisplayOrderCommand : Command
  {
    <span class="highlight-keyword">public</span> <span class="highlight-keyword">override</span> <span class="highlight-keyword">string</span> EnglishName { <span class="highlight-keyword">get</span> { <span class="highlight-keyword">return</span> <span class="highlight-literal">"csDisplayOrder"</span>; } }

    <span class="highlight-keyword">private</span> List&lt;RhinoObject&gt; m_line_objects = <span class="highlight-keyword">new</span> List&lt;RhinoObject&gt;(); 

    <span class="highlight-keyword">protected</span> <span class="highlight-keyword">override</span> Result RunCommand(RhinoDoc doc, RunMode mode)
    {
      <span class="highlight-comment">// make lines thick so draw order can be easily seen</span>
      <span class="highlight-keyword">var</span> dm = DisplayModeDescription.GetDisplayModes().Single(x =&gt; x.EnglishName == <span class="highlight-literal">"Wireframe"</span>);
      <span class="highlight-keyword">var</span> original_thikcness = dm.DisplayAttributes.CurveThickness;
      dm.DisplayAttributes.CurveThickness = <span class="highlight-number">10</span>;
      DisplayModeDescription.UpdateDisplayMode(dm);

      AddLine(Point3d.Origin, <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">10</span>,<span class="highlight-number">10</span>,<span class="highlight-number">0</span>), Color.Red, doc);
      AddLine(<span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">10</span>,<span class="highlight-number">0</span>,<span class="highlight-number">0</span>), <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">0</span>,<span class="highlight-number">10</span>,<span class="highlight-number">0</span>), Color.Blue, doc);
      AddLine(<span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">8</span>,<span class="highlight-number">0</span>,<span class="highlight-number">0</span>), <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">8</span>,<span class="highlight-number">10</span>,<span class="highlight-number">0</span>), Color.Green, doc);
      AddLine(<span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">0</span>,<span class="highlight-number">3</span>,<span class="highlight-number">0</span>), <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">10</span>,<span class="highlight-number">3</span>,<span class="highlight-number">0</span>), Color.Yellow, doc);
      doc.Views.Redraw();
      Pause(<span class="highlight-literal">"draw order: 1st line drawn in front, last line drawn in the back.  Any key to continue ..."</span>);

      <span class="highlight-comment">//all objects have a DisplayOrder of 0 by default so changing it to 1 moves it to the front.  Here we move the 2nd line (blue) to the front</span>
      m_line_objects[<span class="highlight-number">1</span>].Attributes.DisplayOrder = <span class="highlight-number">1</span>;
      m_line_objects[<span class="highlight-number">1</span>].CommitChanges();
      doc.Views.Redraw();
      Pause(<span class="highlight-literal">"Second (blue) line now in front.  Any key to continue ..."</span>);

      <span class="highlight-keyword">for</span> (<span class="highlight-keyword">int</span> i = <span class="highlight-number">0</span>; i &lt; m_line_objects.Count; i++)
      {
        m_line_objects[i].Attributes.DisplayOrder = i;
        m_line_objects[i].CommitChanges();
      }
      doc.Views.Redraw();
      Pause(<span class="highlight-literal">"Reverse order of original lines, i.e., Yellow 1st and Red last.  Any key to continue ..."</span>);

      <span class="highlight-comment">// restore original line thickness</span>
      dm.DisplayAttributes.CurveThickness = original_thikcness;
      DisplayModeDescription.UpdateDisplayMode(dm);

      doc.Views.Redraw();
      <span class="highlight-keyword">return</span> Result.Success;
    }

    <span class="highlight-keyword">private</span> <span class="highlight-keyword">void</span> Pause(<span class="highlight-keyword">string</span> msg)
    {
      ObjRef obj_ref;
      <span class="highlight-keyword">var</span> rc = RhinoGet.GetOneObject(msg, <span class="highlight-keyword">true</span>, ObjectType.AnyObject, <span class="highlight-keyword">out</span> obj_ref);
    }

    <span class="highlight-keyword">private</span> <span class="highlight-keyword">void</span> AddLine(Point3d <span class="highlight-keyword">from</span>, Point3d to, Color color, RhinoDoc doc)
    {
      <span class="highlight-keyword">var</span> guid = doc.Objects.AddLine(<span class="highlight-keyword">from</span>, to);
      <span class="highlight-keyword">var</span> obj = doc.Objects.Find(guid);
      m_line_objects.Add(obj);
      obj.Attributes.ObjectColor = color;
      obj.Attributes.ColorSource = ObjectColorSource.ColorFromObject;
      obj.CommitChanges();
    }
  }
}</pre></div><div id="ID0EBBABA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Imports</span> System.Collections.Generic
<span class="highlight-keyword">Imports</span> System.Drawing
<span class="highlight-keyword">Imports</span> System.Linq
<span class="highlight-keyword">Imports</span> Rhino
<span class="highlight-keyword">Imports</span> Rhino.Commands
<span class="highlight-keyword">Imports</span> Rhino.Display
<span class="highlight-keyword">Imports</span> Rhino.Geometry
<span class="highlight-keyword">Imports</span> Rhino.Input
<span class="highlight-keyword">Imports</span> Rhino.DocObjects

<span class="highlight-keyword">Namespace</span> examples_vb
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Class</span> DisplayOrderCommand
    <span class="highlight-keyword">Inherits</span> Command
    <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">ReadOnly</span> <span class="highlight-keyword">Property</span> EnglishName() <span class="highlight-keyword">As</span> <span class="highlight-keyword">String</span>
      <span class="highlight-keyword">Get</span>
        <span class="highlight-keyword">Return</span> <span class="highlight-literal">"vbDisplayOrder"</span>
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">Get</span>
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Property</span>

    <span class="highlight-keyword">Private</span> m_line_objects <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> List(<span class="highlight-keyword">Of</span> RhinoObject)()

    <span class="highlight-keyword">Protected</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">Function</span> RunCommand(doc <span class="highlight-keyword">As</span> RhinoDoc, mode <span class="highlight-keyword">As</span> RunMode) <span class="highlight-keyword">As</span> Result
      <span class="highlight-comment">' make lines thick so draw order can be easily seen</span>
      <span class="highlight-keyword">Dim</span> dm = DisplayModeDescription.GetDisplayModes().[<span class="highlight-keyword">Single</span>](<span class="highlight-keyword">Function</span>(x) x.EnglishName = <span class="highlight-literal">"Wireframe"</span>)
      <span class="highlight-keyword">Dim</span> original_thikcness = dm.DisplayAttributes.CurveThickness
      dm.DisplayAttributes.CurveThickness = <span class="highlight-number">10</span>
      DisplayModeDescription.UpdateDisplayMode(dm)

      AddLine(Point3d.Origin, <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">10</span>, <span class="highlight-number">10</span>, <span class="highlight-number">0</span>), Color.Red, doc)
      AddLine(<span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">10</span>, <span class="highlight-number">0</span>, <span class="highlight-number">0</span>), <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">0</span>, <span class="highlight-number">10</span>, <span class="highlight-number">0</span>), Color.Blue, doc)
      AddLine(<span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">8</span>, <span class="highlight-number">0</span>, <span class="highlight-number">0</span>), <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">8</span>, <span class="highlight-number">10</span>, <span class="highlight-number">0</span>), Color.Green, doc)
      AddLine(<span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">0</span>, <span class="highlight-number">3</span>, <span class="highlight-number">0</span>), <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">10</span>, <span class="highlight-number">3</span>, <span class="highlight-number">0</span>), Color.Yellow, doc)
      doc.Views.Redraw()
      Pause(<span class="highlight-literal">"draw order: 1st line drawn in front, last line drawn in the back.  Any key to continue ..."</span>)

      <span class="highlight-comment">'all objects have a DisplayOrder of 0 by default so changing it to 1 moves it to the front.  Here we move the 2nd line (blue) to the front</span>
      m_line_objects(<span class="highlight-number">1</span>).Attributes.DisplayOrder = <span class="highlight-number">1</span>
      m_line_objects(<span class="highlight-number">1</span>).CommitChanges()
      doc.Views.Redraw()
      Pause(<span class="highlight-literal">"Second (blue) line now in front.  Any key to continue ..."</span>)

      <span class="highlight-keyword">For</span> i <span class="highlight-keyword">As</span> <span class="highlight-keyword">Integer</span> = <span class="highlight-number">0</span> <span class="highlight-keyword">To</span> m_line_objects.Count - <span class="highlight-number">1</span>
        m_line_objects(i).Attributes.DisplayOrder = i
        m_line_objects(i).CommitChanges()
      <span class="highlight-keyword">Next</span>
      doc.Views.Redraw()
      Pause(<span class="highlight-literal">"Reverse order of original lines, i.e., Yellow 1st and Red last.  Any key to continue ..."</span>)

      <span class="highlight-comment">' restore original line thickness</span>
      dm.DisplayAttributes.CurveThickness = original_thikcness
      DisplayModeDescription.UpdateDisplayMode(dm)

      doc.Views.Redraw()
      <span class="highlight-keyword">Return</span> Result.Success
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>

    <span class="highlight-keyword">Private</span> <span class="highlight-keyword">Sub</span> Pause(msg <span class="highlight-keyword">As</span> <span class="highlight-keyword">String</span>)
      <span class="highlight-keyword">Dim</span> obj_ref <span class="highlight-keyword">As</span> ObjRef = <span class="highlight-keyword">Nothing</span>
      <span class="highlight-keyword">Dim</span> rc = RhinoGet.GetOneObject(msg, <span class="highlight-keyword">True</span>, ObjectType.AnyObject, obj_ref)
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Sub</span>

    <span class="highlight-keyword">Private</span> <span class="highlight-keyword">Sub</span> AddLine(from <span class="highlight-keyword">As</span> Point3d, [<span class="highlight-keyword">to</span>] <span class="highlight-keyword">As</span> Point3d, color <span class="highlight-keyword">As</span> Color, doc <span class="highlight-keyword">As</span> RhinoDoc)
      <span class="highlight-keyword">Dim</span> guid = doc.Objects.AddLine(from, [<span class="highlight-keyword">to</span>])
      <span class="highlight-keyword">Dim</span> obj = doc.Objects.Find(guid)
      m_line_objects.Add(obj)
      obj.Attributes.ObjectColor = color
      obj.Attributes.ColorSource = ObjectColorSource.ColorFromObject
      obj.CommitChanges()
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Sub</span>
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Namespace</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBABA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAAABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EAAABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAAABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">from</span> System.Collections.Generic <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> System.Drawing <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.Commands <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.Display <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.Geometry <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.Input <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.DocObjects <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> scriptcontext <span class="highlight-keyword">import</span> doc

m_line_objects = []

<span class="highlight-keyword">def</span> RunCommand():
  <span class="highlight-comment"># make lines thick so draw order can be easily seen</span>
  wfdm = [dm <span class="highlight-keyword">for</span> dm <span class="highlight-keyword">in</span> DisplayModeDescription.GetDisplayModes() <span class="highlight-keyword">if</span> dm.EnglishName == <span class="highlight-literal">"Wireframe"</span>][<span class="highlight-number">0</span>]
  original_thikcness = wfdm.DisplayAttributes.CurveThickness
  wfdm.DisplayAttributes.CurveThickness = <span class="highlight-number">10</span>
  DisplayModeDescription.UpdateDisplayMode(wfdm)

  AddLine(Point3d.Origin, Point3d(<span class="highlight-number">10</span>,<span class="highlight-number">10</span>,<span class="highlight-number">0</span>), Color.Red, doc)
  AddLine(Point3d(<span class="highlight-number">10</span>,<span class="highlight-number">0</span>,<span class="highlight-number">0</span>), Point3d(<span class="highlight-number">0</span>,<span class="highlight-number">10</span>,<span class="highlight-number">0</span>), Color.Blue, doc)
  AddLine(Point3d(<span class="highlight-number">8</span>,<span class="highlight-number">0</span>,<span class="highlight-number">0</span>), Point3d(<span class="highlight-number">8</span>,<span class="highlight-number">10</span>,<span class="highlight-number">0</span>), Color.Green, doc)
  AddLine(Point3d(<span class="highlight-number">0</span>,<span class="highlight-number">3</span>,<span class="highlight-number">0</span>), Point3d(<span class="highlight-number">10</span>,<span class="highlight-number">3</span>,<span class="highlight-number">0</span>), Color.Yellow, doc)
  doc.Views.Redraw()
  Pause(<span class="highlight-literal">"draw order: 1st line drawn in front, last line drawn in the back.  Any key to continue ..."</span>)

  <span class="highlight-comment">#all objects have a DisplayOrder of 0 by default so changing it to 1 moves it to the front.  Here we move the 2nd line (blue) to the front</span>
  m_line_objects[<span class="highlight-number">1</span>].Attributes.DisplayOrder = <span class="highlight-number">1</span>
  m_line_objects[<span class="highlight-number">1</span>].CommitChanges()
  doc.Views.Redraw()
  Pause(<span class="highlight-literal">"Second (blue) line now in front.  Any key to continue ..."</span>)

  <span class="highlight-keyword">for</span> i <span class="highlight-keyword">in</span> range(<span class="highlight-number">0</span>, m_line_objects.Count - <span class="highlight-number">1</span>):
    m_line_objects[i].Attributes.DisplayOrder = i
    m_line_objects[i].CommitChanges()

  doc.Views.Redraw()
  Pause(<span class="highlight-literal">"Reverse order of original lines, i.e., Yellow 1st and Red last.  Any key to continue ..."</span>)

  <span class="highlight-comment"># restore original line thickness</span>
  wfdm.DisplayAttributes.CurveThickness = original_thikcness
  DisplayModeDescription.UpdateDisplayMode(wfdm)

  doc.Views.Redraw()
  <span class="highlight-keyword">return</span> Result.Success

<span class="highlight-keyword">def</span> Pause(msg):
  rc, obj_ref = RhinoGet.GetOneObject(msg, True, ObjectType.AnyObject)

<span class="highlight-keyword">def</span> AddLine(from_pt, to_pt, color, doc):
  guid = doc.Objects.AddLine(from_pt, to_pt)
  obj = doc.Objects.Find(guid)
  m_line_objects.Add(obj)
  obj.Attributes.ObjectColor = color
  obj.Attributes.ColorSource = ObjectColorSource.ColorFromObject
  obj.CommitChanges()

<span class="highlight-keyword">if</span> __name__ == <span class="highlight-literal">"__main__"</span>:
  RunCommand()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAAABA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_DocObjects_ObjectAttributes.htm">ObjectAttributes Class</a></div><div class="seeAlsoStyle"><a href="N_Rhino_DocObjects.htm">Rhino.DocObjects Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Updated 4 October 2015 - Robert McNeel and Associates<p><a href="http://discourse.mcneel.com/" target="_blank">Report wishes and bugs: http://discourse.mcneel.com/</a></p><div class="feedbackLink">Send comments on this topic to
        <a id="HT_MailLink" href="mailto:steve%40mcneel.com?Subject=RhinoCommon SDK">steve@mcneel.com</a></div><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title + "\u0026body=" + encodeURIComponent("Your feedback is used to improve the documentation and the product. Your e-mail address will not be used for any other purpose and is disposed of after the issue you report is resolved. While working to resolve the issue that you report, you may be contacted via e-mail to get further details or clarification on the feedback you sent. After the issue you report has been addressed, you may receive an e-mail to let you know that your feedback has been addressed.");
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script> </div></body></html>