<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Mesh.Faces Property </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="Faces property" /><meta name="System.Keywords" content="Mesh.Faces property" /><meta name="Microsoft.Help.F1" content="Rhino.Geometry.Mesh.Faces" /><meta name="Microsoft.Help.F1" content="Rhino.Geometry.Mesh.get_Faces" /><meta name="Microsoft.Help.Id" content="P:Rhino.Geometry.Mesh.Faces" /><meta name="Description" content="Gets access to the mesh face list." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Geometry" /><meta name="file" content="P_Rhino_Geometry_Mesh_Faces" /><meta name="guid" content="P_Rhino_Geometry_Mesh_Faces" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.3.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon API<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="RhinoCommon API" tocid="roottoc">RhinoCommon API</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="Namespaces" tocid="R_Project_RhinoCommon">Namespaces</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Rhino_Geometry.htm" title="Rhino.Geometry" tocid="N_Rhino_Geometry">Rhino.Geometry</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Rhino_Geometry_Mesh.htm" title="Mesh Class" tocid="T_Rhino_Geometry_Mesh">Mesh Class</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Properties_T_Rhino_Geometry_Mesh.htm" title="Mesh Properties" tocid="Properties_T_Rhino_Geometry_Mesh">Mesh Properties</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Mesh_ComponentStates.htm" title="ComponentStates Property " tocid="P_Rhino_Geometry_Mesh_ComponentStates">ComponentStates Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Mesh_DisjointMeshCount.htm" title="DisjointMeshCount Property " tocid="P_Rhino_Geometry_Mesh_DisjointMeshCount">DisjointMeshCount Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Mesh_FaceNormals.htm" title="FaceNormals Property " tocid="P_Rhino_Geometry_Mesh_FaceNormals">FaceNormals Property </a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Mesh_Faces.htm" title="Faces Property " tocid="P_Rhino_Geometry_Mesh_Faces">Faces Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Mesh_HasCachedTextureCoordinates.htm" title="HasCachedTextureCoordinates Property " tocid="P_Rhino_Geometry_Mesh_HasCachedTextureCoordinates">HasCachedTextureCoordinates Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Mesh_HasPrincipalCurvatures.htm" title="HasPrincipalCurvatures Property " tocid="P_Rhino_Geometry_Mesh_HasPrincipalCurvatures">HasPrincipalCurvatures Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Mesh_IsClosed.htm" title="IsClosed Property " tocid="P_Rhino_Geometry_Mesh_IsClosed">IsClosed Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Mesh_IsOriented.htm" title="IsOriented Property " tocid="P_Rhino_Geometry_Mesh_IsOriented">IsOriented Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Mesh_IsSolid.htm" title="IsSolid Property " tocid="P_Rhino_Geometry_Mesh_IsSolid">IsSolid Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Mesh_Ngons.htm" title="Ngons Property " tocid="P_Rhino_Geometry_Mesh_Ngons">Ngons Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Mesh_Normals.htm" title="Normals Property " tocid="P_Rhino_Geometry_Mesh_Normals">Normals Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Mesh_PartitionCount.htm" title="PartitionCount Property " tocid="P_Rhino_Geometry_Mesh_PartitionCount">PartitionCount Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Mesh_TextureCoordinates.htm" title="TextureCoordinates Property " tocid="P_Rhino_Geometry_Mesh_TextureCoordinates">TextureCoordinates Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Mesh_TopologyEdges.htm" title="TopologyEdges Property " tocid="P_Rhino_Geometry_Mesh_TopologyEdges">TopologyEdges Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Mesh_TopologyVertices.htm" title="TopologyVertices Property " tocid="P_Rhino_Geometry_Mesh_TopologyVertices">TopologyVertices Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Mesh_VertexColors.htm" title="VertexColors Property " tocid="P_Rhino_Geometry_Mesh_VertexColors">VertexColors Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Mesh_Vertices.htm" title="Vertices Property " tocid="P_Rhino_Geometry_Mesh_Vertices">Vertices Property </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn"><h1>Mesh<span id="LSTEC1A06C2_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTEC1A06C2_0?cpp=::|nu=.");</script>Faces Property </h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            Gets access to the mesh face list.
            </div><p> </p>
    <strong>Namespace:</strong> 
   <a href="N_Rhino_Geometry.htm">Rhino.Geometry</a><br />
    <strong>Assembly:</strong>
   RhinoCommon (in RhinoCommon.dll)<div class="since"><strong>Since:</strong> 5.0</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">MeshFaceList</span> <span class="identifier">Faces</span> { <span class="keyword">get</span>; }</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">ReadOnly</span> <span class="keyword">Property</span> <span class="identifier">Faces</span> <span class="keyword">As</span> <span class="identifier">MeshFaceList</span>
	<span class="keyword">Get</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Property Value</h4>Type: <a href="T_Rhino_Geometry_Collections_MeshFaceList.htm">MeshFaceList</a></div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBBBA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBBBA','cs','1','2');return false;">C#</a></div><div id="ID0EBBBBA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBBBA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBBBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBBBBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBBBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">using</span> System;

<span class="highlight-keyword">partial</span> <span class="highlight-keyword">class</span> Examples
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">static</span> Rhino.Commands.Result AddMesh(Rhino.RhinoDoc doc)
  {
    Rhino.Geometry.Mesh mesh = <span class="highlight-keyword">new</span> Rhino.Geometry.Mesh();
    mesh.Vertices.Add(<span class="highlight-number">0.0</span>, <span class="highlight-number">0.0</span>, <span class="highlight-number">1.0</span>); <span class="highlight-comment">//0</span>
    mesh.Vertices.Add(<span class="highlight-number">1.0</span>, <span class="highlight-number">0.0</span>, <span class="highlight-number">1.0</span>); <span class="highlight-comment">//1</span>
    mesh.Vertices.Add(<span class="highlight-number">2.0</span>, <span class="highlight-number">0.0</span>, <span class="highlight-number">1.0</span>); <span class="highlight-comment">//2</span>
    mesh.Vertices.Add(<span class="highlight-number">3.0</span>, <span class="highlight-number">0.0</span>, <span class="highlight-number">0.0</span>); <span class="highlight-comment">//3</span>
    mesh.Vertices.Add(<span class="highlight-number">0.0</span>, <span class="highlight-number">1.0</span>, <span class="highlight-number">1.0</span>); <span class="highlight-comment">//4</span>
    mesh.Vertices.Add(<span class="highlight-number">1.0</span>, <span class="highlight-number">1.0</span>, <span class="highlight-number">2.0</span>); <span class="highlight-comment">//5</span>
    mesh.Vertices.Add(<span class="highlight-number">2.0</span>, <span class="highlight-number">1.0</span>, <span class="highlight-number">1.0</span>); <span class="highlight-comment">//6</span>
    mesh.Vertices.Add(<span class="highlight-number">3.0</span>, <span class="highlight-number">1.0</span>, <span class="highlight-number">0.0</span>); <span class="highlight-comment">//7</span>
    mesh.Vertices.Add(<span class="highlight-number">0.0</span>, <span class="highlight-number">2.0</span>, <span class="highlight-number">1.0</span>); <span class="highlight-comment">//8</span>
    mesh.Vertices.Add(<span class="highlight-number">1.0</span>, <span class="highlight-number">2.0</span>, <span class="highlight-number">1.0</span>); <span class="highlight-comment">//9</span>
    mesh.Vertices.Add(<span class="highlight-number">2.0</span>, <span class="highlight-number">2.0</span>, <span class="highlight-number">1.0</span>); <span class="highlight-comment">//10</span>
    mesh.Vertices.Add(<span class="highlight-number">3.0</span>, <span class="highlight-number">2.0</span>, <span class="highlight-number">1.0</span>); <span class="highlight-comment">//11</span>

    mesh.Faces.AddFace(<span class="highlight-number">0</span>, <span class="highlight-number">1</span>, <span class="highlight-number">5</span>, <span class="highlight-number">4</span>);
    mesh.Faces.AddFace(<span class="highlight-number">1</span>, <span class="highlight-number">2</span>, <span class="highlight-number">6</span>, <span class="highlight-number">5</span>);
    mesh.Faces.AddFace(<span class="highlight-number">2</span>, <span class="highlight-number">3</span>, <span class="highlight-number">7</span>, <span class="highlight-number">6</span>);
    mesh.Faces.AddFace(<span class="highlight-number">4</span>, <span class="highlight-number">5</span>, <span class="highlight-number">9</span>, <span class="highlight-number">8</span>);
    mesh.Faces.AddFace(<span class="highlight-number">5</span>, <span class="highlight-number">6</span>, <span class="highlight-number">10</span>, <span class="highlight-number">9</span>);
    mesh.Faces.AddFace(<span class="highlight-number">6</span>, <span class="highlight-number">7</span>, <span class="highlight-number">11</span>, <span class="highlight-number">10</span>);
    mesh.Normals.ComputeNormals();
    mesh.Compact();
    <span class="highlight-keyword">if</span> (doc.Objects.AddMesh(mesh) != Guid.Empty)
    {
      doc.Views.Redraw();
      <span class="highlight-keyword">return</span> Rhino.Commands.Result.Success;
    }
    <span class="highlight-keyword">return</span> Rhino.Commands.Result.Failure;
  }
}</pre></div><div id="ID0EBBBBA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Partial</span> <span class="highlight-keyword">Class</span> Examples
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Shared</span> <span class="highlight-keyword">Function</span> AddMesh(<span class="highlight-keyword">ByVal</span> doc <span class="highlight-keyword">As</span> Rhino.RhinoDoc) <span class="highlight-keyword">As</span> Rhino.Commands.Result
    <span class="highlight-keyword">Dim</span> mesh <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Rhino.Geometry.Mesh()
    mesh.Vertices.Add(<span class="highlight-number">0.0</span>, <span class="highlight-number">0.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">'0</span>
    mesh.Vertices.Add(<span class="highlight-number">1.0</span>, <span class="highlight-number">0.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">'1</span>
    mesh.Vertices.Add(<span class="highlight-number">2.0</span>, <span class="highlight-number">0.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">'2</span>
    mesh.Vertices.Add(<span class="highlight-number">3.0</span>, <span class="highlight-number">0.0</span>, <span class="highlight-number">0.0</span>) <span class="highlight-comment">'3</span>
    mesh.Vertices.Add(<span class="highlight-number">0.0</span>, <span class="highlight-number">1.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">'4</span>
    mesh.Vertices.Add(<span class="highlight-number">1.0</span>, <span class="highlight-number">1.0</span>, <span class="highlight-number">2.0</span>) <span class="highlight-comment">'5</span>
    mesh.Vertices.Add(<span class="highlight-number">2.0</span>, <span class="highlight-number">1.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">'6</span>
    mesh.Vertices.Add(<span class="highlight-number">3.0</span>, <span class="highlight-number">1.0</span>, <span class="highlight-number">0.0</span>) <span class="highlight-comment">'7</span>
    mesh.Vertices.Add(<span class="highlight-number">0.0</span>, <span class="highlight-number">2.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">'8</span>
    mesh.Vertices.Add(<span class="highlight-number">1.0</span>, <span class="highlight-number">2.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">'9</span>
    mesh.Vertices.Add(<span class="highlight-number">2.0</span>, <span class="highlight-number">2.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">'10</span>
    mesh.Vertices.Add(<span class="highlight-number">3.0</span>, <span class="highlight-number">2.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">'11</span>
    mesh.Faces.AddFace(<span class="highlight-number">0</span>, <span class="highlight-number">1</span>, <span class="highlight-number">5</span>, <span class="highlight-number">4</span>)
    mesh.Faces.AddFace(<span class="highlight-number">1</span>, <span class="highlight-number">2</span>, <span class="highlight-number">6</span>, <span class="highlight-number">5</span>)
    mesh.Faces.AddFace(<span class="highlight-number">2</span>, <span class="highlight-number">3</span>, <span class="highlight-number">7</span>, <span class="highlight-number">6</span>)
    mesh.Faces.AddFace(<span class="highlight-number">4</span>, <span class="highlight-number">5</span>, <span class="highlight-number">9</span>, <span class="highlight-number">8</span>)
    mesh.Faces.AddFace(<span class="highlight-number">5</span>, <span class="highlight-number">6</span>, <span class="highlight-number">10</span>, <span class="highlight-number">9</span>)
    mesh.Faces.AddFace(<span class="highlight-number">6</span>, <span class="highlight-number">7</span>, <span class="highlight-number">11</span>, <span class="highlight-number">10</span>)
    mesh.Normals.ComputeNormals()
    mesh.Compact()
    <span class="highlight-keyword">If</span> doc.Objects.AddMesh(mesh) &lt;&gt; Guid.Empty <span class="highlight-keyword">Then</span>
      doc.Views.Redraw()
      <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Success
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
    <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Failure
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBBBA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EAABBA_tab1" class="codeSnippetContainerTabSingle">Python</div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAABBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EAABBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAABBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">import</span> Rhino
<span class="highlight-keyword">import</span> scriptcontext
<span class="highlight-keyword">import</span> System.Guid

<span class="highlight-keyword">def</span> AddMesh():
    mesh = Rhino.Geometry.Mesh()
    mesh.Vertices.Add(<span class="highlight-number">0.0</span>, <span class="highlight-number">0.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">#0</span>
    mesh.Vertices.Add(<span class="highlight-number">1.0</span>, <span class="highlight-number">0.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">#1</span>
    mesh.Vertices.Add(<span class="highlight-number">2.0</span>, <span class="highlight-number">0.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">#2</span>
    mesh.Vertices.Add(<span class="highlight-number">3.0</span>, <span class="highlight-number">0.0</span>, <span class="highlight-number">0.0</span>) <span class="highlight-comment">#3</span>
    mesh.Vertices.Add(<span class="highlight-number">0.0</span>, <span class="highlight-number">1.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">#4</span>
    mesh.Vertices.Add(<span class="highlight-number">1.0</span>, <span class="highlight-number">1.0</span>, <span class="highlight-number">2.0</span>) <span class="highlight-comment">#5</span>
    mesh.Vertices.Add(<span class="highlight-number">2.0</span>, <span class="highlight-number">1.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">#6</span>
    mesh.Vertices.Add(<span class="highlight-number">3.0</span>, <span class="highlight-number">1.0</span>, <span class="highlight-number">0.0</span>) <span class="highlight-comment">#7</span>
    mesh.Vertices.Add(<span class="highlight-number">0.0</span>, <span class="highlight-number">2.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">#8</span>
    mesh.Vertices.Add(<span class="highlight-number">1.0</span>, <span class="highlight-number">2.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">#9</span>
    mesh.Vertices.Add(<span class="highlight-number">2.0</span>, <span class="highlight-number">2.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">#10</span>
    mesh.Vertices.Add(<span class="highlight-number">3.0</span>, <span class="highlight-number">2.0</span>, <span class="highlight-number">1.0</span>) <span class="highlight-comment">#11</span>

    mesh.Faces.AddFace(<span class="highlight-number">0</span>, <span class="highlight-number">1</span>, <span class="highlight-number">5</span>, <span class="highlight-number">4</span>)
    mesh.Faces.AddFace(<span class="highlight-number">1</span>, <span class="highlight-number">2</span>, <span class="highlight-number">6</span>, <span class="highlight-number">5</span>)
    mesh.Faces.AddFace(<span class="highlight-number">2</span>, <span class="highlight-number">3</span>, <span class="highlight-number">7</span>, <span class="highlight-number">6</span>)
    mesh.Faces.AddFace(<span class="highlight-number">4</span>, <span class="highlight-number">5</span>, <span class="highlight-number">9</span>, <span class="highlight-number">8</span>)
    mesh.Faces.AddFace(<span class="highlight-number">5</span>, <span class="highlight-number">6</span>, <span class="highlight-number">10</span>, <span class="highlight-number">9</span>)
    mesh.Faces.AddFace(<span class="highlight-number">6</span>, <span class="highlight-number">7</span>, <span class="highlight-number">11</span>, <span class="highlight-number">10</span>)
    mesh.Normals.ComputeNormals()
    mesh.Compact()
    <span class="highlight-keyword">if</span> scriptcontext.doc.Objects.AddMesh(mesh)!=System.Guid.Empty:
        scriptcontext.doc.Views.Redraw()
        <span class="highlight-keyword">return</span> Rhino.Commands.Result.Success
    <span class="highlight-keyword">return</span> Rhino.Commands.Result.Failure


<span class="highlight-keyword">if</span> __name__==<span class="highlight-literal">"__main__"</span>:
    AddMesh()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAABBA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_Geometry_Mesh.htm">Mesh Class</a></div><div class="seeAlsoStyle"><a href="N_Rhino_Geometry.htm">Rhino.Geometry Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Rhino 7.17.22102.05000 (Last updated: 4/21/2022)<br />Copyright © 2009-2022 Robert McNeel &amp; Associates<p><a href="https://discourse.mcneel.com/c/rhino-developer" target="_blank">Report wishes and bugs at discourse.mcneel.com</a></p> </div></body></html>