<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>ModelAidSettings.Ortho Property </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="Ortho property" /><meta name="System.Keywords" content="ModelAidSettings.Ortho property" /><meta name="Microsoft.Help.F1" content="Rhino.ApplicationSettings.ModelAidSettings.Ortho" /><meta name="Microsoft.Help.F1" content="Rhino.ApplicationSettings.ModelAidSettings.get_Ortho" /><meta name="Microsoft.Help.F1" content="Rhino.ApplicationSettings.ModelAidSettings.set_Ortho" /><meta name="Microsoft.Help.Id" content="P:Rhino.ApplicationSettings.ModelAidSettings.Ortho" /><meta name="Description" content="Gets or sets the enabled state of Rhino's ortho modeling aid." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.ApplicationSettings" /><meta name="file" content="P_Rhino_ApplicationSettings_ModelAidSettings_Ortho" /><meta name="guid" content="P_Rhino_ApplicationSettings_ModelAidSettings_Ortho" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-1.11.0.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon SDK<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino.htm" title="RhinoCommon SDK" tocid="roottoc">RhinoCommon SDK</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino_ApplicationSettings.htm" title="Rhino.ApplicationSettings" tocid="N_Rhino_ApplicationSettings">Rhino.ApplicationSettings</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="T_Rhino_ApplicationSettings_ModelAidSettings.htm" title="ModelAidSettings Class" tocid="T_Rhino_ApplicationSettings_ModelAidSettings">ModelAidSettings Class</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Properties_T_Rhino_ApplicationSettings_ModelAidSettings.htm" title="ModelAidSettings Properties" tocid="Properties_T_Rhino_ApplicationSettings_ModelAidSettings">ModelAidSettings Properties</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_AltPlusArrow.htm" title="AltPlusArrow Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_AltPlusArrow">AltPlusArrow Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_AutoGumballEnabled.htm" title="AutoGumballEnabled Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_AutoGumballEnabled">AutoGumballEnabled Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_ControlPolygonDisplayDensity.htm" title="ControlPolygonDisplayDensity Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_ControlPolygonDisplayDensity">ControlPolygonDisplayDensity Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_CtrlNudgeKeyStep.htm" title="CtrlNudgeKeyStep Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_CtrlNudgeKeyStep">CtrlNudgeKeyStep Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_DisplayControlPolygon.htm" title="DisplayControlPolygon Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_DisplayControlPolygon">DisplayControlPolygon Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_ExtendToApparentIntersection.htm" title="ExtendToApparentIntersection Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_ExtendToApparentIntersection">ExtendToApparentIntersection Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_ExtendTrimLines.htm" title="ExtendTrimLines Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_ExtendTrimLines">ExtendTrimLines Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_GridSnap.htm" title="GridSnap Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_GridSnap">GridSnap Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_HighlightControlPolygon.htm" title="HighlightControlPolygon Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_HighlightControlPolygon">HighlightControlPolygon Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_MousePickboxRadius.htm" title="MousePickboxRadius Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_MousePickboxRadius">MousePickboxRadius Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_NudgeKeyStep.htm" title="NudgeKeyStep Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_NudgeKeyStep">NudgeKeyStep Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_NudgeMode.htm" title="NudgeMode Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_NudgeMode">NudgeMode Property </a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_Ortho.htm" title="Ortho Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_Ortho">Ortho Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_OrthoAngle.htm" title="OrthoAngle Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_OrthoAngle">OrthoAngle Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_Osnap.htm" title="Osnap Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_Osnap">Osnap Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_OsnapCursorMode.htm" title="OsnapCursorMode Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_OsnapCursorMode">OsnapCursorMode Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_OsnapModes.htm" title="OsnapModes Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_OsnapModes">OsnapModes Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_OsnapPickboxRadius.htm" title="OsnapPickboxRadius Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_OsnapPickboxRadius">OsnapPickboxRadius Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_Planar.htm" title="Planar Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_Planar">Planar Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_PointDisplay.htm" title="PointDisplay Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_PointDisplay">PointDisplay Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_ProjectSnapToCPlane.htm" title="ProjectSnapToCPlane Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_ProjectSnapToCPlane">ProjectSnapToCPlane Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_ShiftNudgeKeyStep.htm" title="ShiftNudgeKeyStep Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_ShiftNudgeKeyStep">ShiftNudgeKeyStep Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_SnappyGumballEnabled.htm" title="SnappyGumballEnabled Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_SnappyGumballEnabled">SnappyGumballEnabled Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_SnapToLocked.htm" title="SnapToLocked Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_SnapToLocked">SnapToLocked Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_UniversalConstructionPlaneMode.htm" title="UniversalConstructionPlaneMode Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_UniversalConstructionPlaneMode">UniversalConstructionPlaneMode Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="P_Rhino_ApplicationSettings_ModelAidSettings_UseHorizontalDialog.htm" title="UseHorizontalDialog Property " tocid="P_Rhino_ApplicationSettings_ModelAidSettings_UseHorizontalDialog">UseHorizontalDialog Property </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn">ModelAidSettings<span id="LSTF6FDE011_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTF6FDE011_0?cpp=::|nu=.");</script>Ortho Property </td></tr></table><span class="introStyle">Rhino 5 for Windows</span><div class="summary">Gets or sets the enabled state of Rhino's ortho modeling aid.</div><p> </p><strong>Namespace:</strong> <a href="N_Rhino_ApplicationSettings.htm">Rhino.ApplicationSettings</a><br /><strong>Assembly:</strong> RhinoCommon (in RhinoCommon.dll) Version: 5.1.30000.16 (5.0.20693.0)<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">static</span> <span class="identifier">bool</span> <span class="identifier">Ortho</span> { <span class="keyword">get</span>; <span class="keyword">set</span>; }</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Shared</span> <span class="keyword">Property</span> <span class="identifier">Ortho</span> <span class="keyword">As</span> <span class="identifier">Boolean</span>
	<span class="keyword">Get</span>
	<span class="keyword">Set</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Property Value</h4>Type: <a href="http://msdn2.microsoft.com/en-us/library/a28wyd50" target="_blank">Boolean</a></div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBABA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','cs','1','2');return false;">C#</a></div><div id="ID0EBBABA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBBABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">using</span> Rhino;
<span class="highlight-keyword">using</span> Rhino.ApplicationSettings;
<span class="highlight-keyword">using</span> Rhino.Commands;
<span class="highlight-keyword">using</span> Rhino.Input.Custom;

<span class="highlight-keyword">namespace</span> examples_cs
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">class</span> OrthoCommand : Command
  {
    <span class="highlight-keyword">public</span> <span class="highlight-keyword">override</span> <span class="highlight-keyword">string</span> EnglishName
    {
      <span class="highlight-keyword">get</span> { <span class="highlight-keyword">return</span> <span class="highlight-literal">"csOrtho"</span>; }
    }

    <span class="highlight-keyword">protected</span> <span class="highlight-keyword">override</span> Result RunCommand(RhinoDoc doc, RunMode mode)
    {
      <span class="highlight-keyword">var</span> gp = <span class="highlight-keyword">new</span> GetPoint();
      gp.SetCommandPrompt(<span class="highlight-literal">"Start of line"</span>);
      gp.Get();
      <span class="highlight-keyword">if</span> (gp.CommandResult() != Result.Success)
        <span class="highlight-keyword">return</span> gp.CommandResult();
      <span class="highlight-keyword">var</span> start_point = gp.Point();

      <span class="highlight-keyword">var</span> original_ortho = ModelAidSettings.Ortho;
      <span class="highlight-keyword">if</span> (!original_ortho)
        ModelAidSettings.Ortho = <span class="highlight-keyword">true</span>;

      gp.SetCommandPrompt(<span class="highlight-literal">"End of line"</span>);
      gp.SetBasePoint(start_point, <span class="highlight-keyword">false</span>);
      gp.DrawLineFromPoint(start_point, <span class="highlight-keyword">true</span>);
      gp.Get();
      <span class="highlight-keyword">if</span> (gp.CommandResult() != Result.Success)
        <span class="highlight-keyword">return</span> gp.CommandResult();
      <span class="highlight-keyword">var</span> end_point = gp.Point();

      <span class="highlight-keyword">if</span> (ModelAidSettings.Ortho != original_ortho)
        ModelAidSettings.Ortho = original_ortho;

      doc.Objects.AddLine(start_point, end_point);
      doc.Views.Redraw();
      <span class="highlight-keyword">return</span> Result.Success;
    }
  }
}</pre></div><div id="ID0EBBABA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Imports</span> Rhino
<span class="highlight-keyword">Imports</span> Rhino.ApplicationSettings
<span class="highlight-keyword">Imports</span> Rhino.Commands
<span class="highlight-keyword">Imports</span> Rhino.Input.Custom

<span class="highlight-keyword">Namespace</span> examples_vb
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Class</span> OrthoCommand
    <span class="highlight-keyword">Inherits</span> Command
    <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">ReadOnly</span> <span class="highlight-keyword">Property</span> EnglishName() <span class="highlight-keyword">As</span> <span class="highlight-keyword">String</span>
      <span class="highlight-keyword">Get</span>
        <span class="highlight-keyword">Return</span> <span class="highlight-literal">"vbOrtho"</span>
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">Get</span>
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Property</span>

    <span class="highlight-keyword">Protected</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">Function</span> RunCommand(doc <span class="highlight-keyword">As</span> RhinoDoc, mode <span class="highlight-keyword">As</span> RunMode) <span class="highlight-keyword">As</span> Result
      <span class="highlight-keyword">Dim</span> gp = <span class="highlight-keyword">New</span> GetPoint()
      gp.SetCommandPrompt(<span class="highlight-literal">"Start of line"</span>)
      gp.[<span class="highlight-keyword">Get</span>]()
      <span class="highlight-keyword">If</span> gp.CommandResult() &lt;&gt; Result.Success <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> gp.CommandResult()
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
      <span class="highlight-keyword">Dim</span> start_point = gp.Point()

      <span class="highlight-keyword">Dim</span> original_ortho = ModelAidSettings.Ortho
      <span class="highlight-keyword">If</span> <span class="highlight-keyword">Not</span> original_ortho <span class="highlight-keyword">Then</span>
        ModelAidSettings.Ortho = <span class="highlight-keyword">True</span>
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

      gp.SetCommandPrompt(<span class="highlight-literal">"End of line"</span>)
      gp.SetBasePoint(start_point, <span class="highlight-keyword">False</span>)
      gp.DrawLineFromPoint(start_point, <span class="highlight-keyword">True</span>)
      gp.[<span class="highlight-keyword">Get</span>]()
      <span class="highlight-keyword">If</span> gp.CommandResult() &lt;&gt; Result.Success <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> gp.CommandResult()
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
      <span class="highlight-keyword">Dim</span> end_point = gp.Point()

      <span class="highlight-keyword">If</span> ModelAidSettings.Ortho &lt;&gt; original_ortho <span class="highlight-keyword">Then</span>
        ModelAidSettings.Ortho = original_ortho
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

      doc.Objects.AddLine(start_point, end_point)
      doc.Views.Redraw()
      <span class="highlight-keyword">Return</span> Result.Success
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Namespace</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBABA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAAABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EAAABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAAABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">from</span> Rhino <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.ApplicationSettings <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.Commands <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.Input.Custom <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> scriptcontext <span class="highlight-keyword">import</span> doc

<span class="highlight-keyword">def</span> RunCommand():
  gp = GetPoint()
  gp.SetCommandPrompt(<span class="highlight-literal">"Start of line"</span>)
  gp.Get()
  <span class="highlight-keyword">if</span> gp.CommandResult() != Result.Success:
    <span class="highlight-keyword">return</span> gp.CommandResult()
  start_point = gp.Point()

  original_ortho = ModelAidSettings.Ortho
  <span class="highlight-keyword">if</span> <span class="highlight-keyword">not</span> original_ortho:
    ModelAidSettings.Ortho = True

  gp.SetCommandPrompt(<span class="highlight-literal">"End of line"</span>)
  gp.SetBasePoint(start_point, False)
  gp.DrawLineFromPoint(start_point, True)
  gp.Get()
  <span class="highlight-keyword">if</span> gp.CommandResult() != Result.Success:
    <span class="highlight-keyword">return</span> gp.CommandResult()
  end_point = gp.Point()

  <span class="highlight-keyword">if</span> ModelAidSettings.Ortho != original_ortho:
    ModelAidSettings.Ortho = original_ortho

  doc.Objects.AddLine(start_point, end_point)
  doc.Views.Redraw()
  <span class="highlight-keyword">return</span> Result.Success

<span class="highlight-keyword">if</span> __name__ == <span class="highlight-literal">"__main__"</span>:
  RunCommand()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAAABA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_ApplicationSettings_ModelAidSettings.htm">ModelAidSettings Class</a></div><div class="seeAlsoStyle"><a href="N_Rhino_ApplicationSettings.htm">Rhino.ApplicationSettings Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Updated 10 March 2016 - Robert McNeel and Associates<p><a href="http://discourse.mcneel.com/" target="_blank">Report wishes and bugs: http://discourse.mcneel.com/</a></p><div class="feedbackLink">Send comments on this topic to
        <a id="HT_MailLink" href="mailto:steve%40mcneel.com?Subject=RhinoCommon SDK">steve@mcneel.com</a></div><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title + "\u0026body=" + encodeURIComponent("Your feedback is used to improve the documentation and the product. Your e-mail address will not be used for any other purpose and is disposed of after the issue you report is resolved. While working to resolve the issue that you report, you may be contacted via e-mail to get further details or clarification on the feedback you sent. After the issue you report has been addressed, you may receive an e-mail to let you know that your feedback has been addressed.");
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script> </div></body></html>