<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>MeshingParameters.Default Property </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="Default property" /><meta name="System.Keywords" content="MeshingParameters.Default property" /><meta name="Microsoft.Help.F1" content="Rhino.Geometry.MeshingParameters.Default" /><meta name="Microsoft.Help.F1" content="Rhino.Geometry.MeshingParameters.get_Default" /><meta name="Microsoft.Help.Id" content="P:Rhino.Geometry.MeshingParameters.Default" /><meta name="Description" content="Gets mesh creation parameters to create the default render mesh. Only use this if you plan on specifying your own custom meshing parameters." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Geometry" /><meta name="file" content="P_Rhino_Geometry_MeshingParameters_Default" /><meta name="guid" content="P_Rhino_Geometry_MeshingParameters_Default" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.3.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon API<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="RhinoCommon API" tocid="roottoc">RhinoCommon API</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="Namespaces" tocid="R_Project_RhinoCommon">Namespaces</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Rhino_Geometry.htm" title="Rhino.Geometry" tocid="N_Rhino_Geometry">Rhino.Geometry</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Rhino_Geometry_MeshingParameters.htm" title="MeshingParameters Class" tocid="T_Rhino_Geometry_MeshingParameters">MeshingParameters Class</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Properties_T_Rhino_Geometry_MeshingParameters.htm" title="MeshingParameters Properties" tocid="Properties_T_Rhino_Geometry_MeshingParameters">MeshingParameters Properties</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_ClosedObjectPostProcess.htm" title="ClosedObjectPostProcess Property " tocid="P_Rhino_Geometry_MeshingParameters_ClosedObjectPostProcess">ClosedObjectPostProcess Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_Coarse.htm" title="Coarse Property " tocid="P_Rhino_Geometry_MeshingParameters_Coarse">Coarse Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_ComputeCurvature.htm" title="ComputeCurvature Property " tocid="P_Rhino_Geometry_MeshingParameters_ComputeCurvature">ComputeCurvature Property </a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_Default.htm" title="Default Property " tocid="P_Rhino_Geometry_MeshingParameters_Default">Default Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_DefaultAnalysisMesh.htm" title="DefaultAnalysisMesh Property " tocid="P_Rhino_Geometry_MeshingParameters_DefaultAnalysisMesh">DefaultAnalysisMesh Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_FastRenderMesh.htm" title="FastRenderMesh Property " tocid="P_Rhino_Geometry_MeshingParameters_FastRenderMesh">FastRenderMesh Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_GridAmplification.htm" title="GridAmplification Property " tocid="P_Rhino_Geometry_MeshingParameters_GridAmplification">GridAmplification Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_GridAngle.htm" title="GridAngle Property " tocid="P_Rhino_Geometry_MeshingParameters_GridAngle">GridAngle Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_GridAspectRatio.htm" title="GridAspectRatio Property " tocid="P_Rhino_Geometry_MeshingParameters_GridAspectRatio">GridAspectRatio Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_GridMaxCount.htm" title="GridMaxCount Property " tocid="P_Rhino_Geometry_MeshingParameters_GridMaxCount">GridMaxCount Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_GridMinCount.htm" title="GridMinCount Property " tocid="P_Rhino_Geometry_MeshingParameters_GridMinCount">GridMinCount Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_JaggedSeams.htm" title="JaggedSeams Property " tocid="P_Rhino_Geometry_MeshingParameters_JaggedSeams">JaggedSeams Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_MaximumEdgeLength.htm" title="MaximumEdgeLength Property " tocid="P_Rhino_Geometry_MeshingParameters_MaximumEdgeLength">MaximumEdgeLength Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_Minimal.htm" title="Minimal Property " tocid="P_Rhino_Geometry_MeshingParameters_Minimal">Minimal Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_MinimumEdgeLength.htm" title="MinimumEdgeLength Property " tocid="P_Rhino_Geometry_MeshingParameters_MinimumEdgeLength">MinimumEdgeLength Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_MinimumTolerance.htm" title="MinimumTolerance Property " tocid="P_Rhino_Geometry_MeshingParameters_MinimumTolerance">MinimumTolerance Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_QualityRenderMesh.htm" title="QualityRenderMesh Property " tocid="P_Rhino_Geometry_MeshingParameters_QualityRenderMesh">QualityRenderMesh Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_RefineAngle.htm" title="RefineAngle Property " tocid="P_Rhino_Geometry_MeshingParameters_RefineAngle">RefineAngle Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_RefineGrid.htm" title="RefineGrid Property " tocid="P_Rhino_Geometry_MeshingParameters_RefineGrid">RefineGrid Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_RelativeTolerance.htm" title="RelativeTolerance Property " tocid="P_Rhino_Geometry_MeshingParameters_RelativeTolerance">RelativeTolerance Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_SimplePlanes.htm" title="SimplePlanes Property " tocid="P_Rhino_Geometry_MeshingParameters_SimplePlanes">SimplePlanes Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_Smooth.htm" title="Smooth Property " tocid="P_Rhino_Geometry_MeshingParameters_Smooth">Smooth Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_TextureRange.htm" title="TextureRange Property " tocid="P_Rhino_Geometry_MeshingParameters_TextureRange">TextureRange Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_MeshingParameters_Tolerance.htm" title="Tolerance Property " tocid="P_Rhino_Geometry_MeshingParameters_Tolerance">Tolerance Property </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn"><h1>MeshingParameters<span id="LSTA2C6BABB_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTA2C6BABB_0?cpp=::|nu=.");</script>Default Property </h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            Gets mesh creation parameters to create the default render mesh.
            Only use this if you plan on specifying your own custom meshing
            parameters.
            </div><p> </p>
    <strong>Namespace:</strong> 
   <a href="N_Rhino_Geometry.htm">Rhino.Geometry</a><br />
    <strong>Assembly:</strong>
   RhinoCommon (in RhinoCommon.dll)<div class="since"><strong>Since:</strong> 5.0</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">static</span> <span class="identifier">MeshingParameters</span> <span class="identifier">Default</span> { <span class="keyword">get</span>; }</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Shared</span> <span class="keyword">ReadOnly</span> <span class="keyword">Property</span> <span class="identifier">Default</span> <span class="keyword">As</span> <span class="identifier">MeshingParameters</span>
	<span class="keyword">Get</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Property Value</h4>Type: <a href="T_Rhino_Geometry_MeshingParameters.htm">MeshingParameters</a></div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBBBA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBBBA','cs','1','2');return false;">C#</a></div><div id="ID0EBBBBA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBBBA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBBBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBBBBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBBBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">using</span> Rhino;
<span class="highlight-keyword">using</span> Rhino.Commands;
<span class="highlight-keyword">using</span> Rhino.Input;
<span class="highlight-keyword">using</span> Rhino.Geometry;
<span class="highlight-keyword">using</span> Rhino.DocObjects;

<span class="highlight-keyword">namespace</span> examples_cs
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">class</span> CreateMeshFromBrepCommand : Command
  {
    <span class="highlight-keyword">public</span> <span class="highlight-keyword">override</span> <span class="highlight-keyword">string</span> EnglishName { <span class="highlight-keyword">get</span> { <span class="highlight-keyword">return</span> <span class="highlight-literal">"csCreateMeshFromBrep"</span>; } }

    <span class="highlight-keyword">protected</span> <span class="highlight-keyword">override</span> Result RunCommand(RhinoDoc doc, RunMode mode)
    {
      ObjRef obj_ref;
      <span class="highlight-keyword">var</span> rc = RhinoGet.GetOneObject(<span class="highlight-literal">"Select surface or polysurface to mesh"</span>, <span class="highlight-keyword">true</span>, ObjectType.Surface | ObjectType.PolysrfFilter, <span class="highlight-keyword">out</span> obj_ref);
      <span class="highlight-keyword">if</span> (rc != Result.Success)
        <span class="highlight-keyword">return</span> rc;
      <span class="highlight-keyword">var</span> brep = obj_ref.Brep();
      <span class="highlight-keyword">if</span> (<span class="highlight-keyword">null</span> == brep)
        <span class="highlight-keyword">return</span> Result.Failure;

      <span class="highlight-comment">// you could choose anyone of these for example</span>
      <span class="highlight-keyword">var</span> jagged_and_faster = MeshingParameters.Coarse;
      <span class="highlight-keyword">var</span> smooth_and_slower = MeshingParameters.Smooth;
      <span class="highlight-keyword">var</span> default_mesh_params = MeshingParameters.Default;
      <span class="highlight-keyword">var</span> minimal = MeshingParameters.Minimal;

      <span class="highlight-keyword">var</span> meshes = Mesh.CreateFromBrep(brep, smooth_and_slower);
      <span class="highlight-keyword">if</span> (meshes == <span class="highlight-keyword">null</span> || meshes.Length == <span class="highlight-number">0</span>)
        <span class="highlight-keyword">return</span> Result.Failure;

      <span class="highlight-keyword">var</span> brep_mesh = <span class="highlight-keyword">new</span> Mesh();
      <span class="highlight-keyword">foreach</span> (<span class="highlight-keyword">var</span> mesh <span class="highlight-keyword">in</span> meshes)
        brep_mesh.Append(mesh);
      doc.Objects.AddMesh(brep_mesh);
      doc.Views.Redraw();

      <span class="highlight-keyword">return</span> Result.Success;
    }
  }
}</pre></div><div id="ID0EBBBBA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Imports</span> Rhino
<span class="highlight-keyword">Imports</span> Rhino.Commands
<span class="highlight-keyword">Imports</span> Rhino.Geometry
<span class="highlight-keyword">Imports</span> Rhino.DocObjects

<span class="highlight-keyword">Namespace</span> examples_vb
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Class</span> CreateMeshFromBrepCommand
    <span class="highlight-keyword">Inherits</span> Command
    <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">ReadOnly</span> <span class="highlight-keyword">Property</span> EnglishName() <span class="highlight-keyword">As</span> <span class="highlight-keyword">String</span>
      <span class="highlight-keyword">Get</span>
        <span class="highlight-keyword">Return</span> <span class="highlight-literal">"vbCreateMeshFromBrep"</span>
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">Get</span>
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Property</span>

    <span class="highlight-keyword">Protected</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">Function</span> RunCommand(doc <span class="highlight-keyword">As</span> RhinoDoc, mode <span class="highlight-keyword">As</span> RunMode) <span class="highlight-keyword">As</span> Result
      <span class="highlight-keyword">Dim</span> objRef <span class="highlight-keyword">As</span> ObjRef = <span class="highlight-keyword">Nothing</span>
      <span class="highlight-keyword">Dim</span> rc = Rhino.Input.RhinoGet.GetOneObject(<span class="highlight-literal">"Select surface or polysurface to mesh"</span>, <span class="highlight-keyword">True</span>, ObjectType.Surface <span class="highlight-keyword">Or</span> ObjectType.PolysrfFilter, objRef)
      <span class="highlight-keyword">If</span> rc &lt;&gt; Result.Success <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> rc
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
      <span class="highlight-keyword">Dim</span> brep = objRef.Brep()
      <span class="highlight-keyword">If</span> brep <span class="highlight-keyword">Is</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> Result.Failure
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

      <span class="highlight-comment">' you could choose any one of these for example</span>
      <span class="highlight-keyword">Dim</span> jaggedAndFaster = MeshingParameters.Coarse
      <span class="highlight-keyword">Dim</span> smoothAndSlower = MeshingParameters.Smooth
      <span class="highlight-keyword">Dim</span> defaultMeshParams = MeshingParameters.<span class="highlight-keyword">Default</span>
      <span class="highlight-keyword">Dim</span> minimal = MeshingParameters.Minimal

      <span class="highlight-keyword">Dim</span> meshes = Mesh.CreateFromBrep(brep, smoothAndSlower)
      <span class="highlight-keyword">If</span> meshes <span class="highlight-keyword">Is</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">OrElse</span> meshes.Length = <span class="highlight-number">0</span> <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> Result.Failure
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

      <span class="highlight-keyword">Dim</span> brepmesh = <span class="highlight-keyword">New</span> Mesh()
      <span class="highlight-keyword">For</span> <span class="highlight-keyword">Each</span> facemesh <span class="highlight-keyword">As</span> Mesh <span class="highlight-keyword">In</span> meshes
        brepmesh.Append(facemesh)
      <span class="highlight-keyword">Next</span>

      doc.Objects.AddMesh(brepmesh)
      doc.Views.Redraw()
      <span class="highlight-keyword">Return</span> Result.Success
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Namespace</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBBBA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EAABBA_tab1" class="codeSnippetContainerTabSingle">Python</div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAABBA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EAABBA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAABBA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">import</span> Rhino
<span class="highlight-keyword">from</span> Rhino.Geometry <span class="highlight-keyword">import</span> *
<span class="highlight-keyword">from</span> Rhino.Input <span class="highlight-keyword">import</span> RhinoGet
<span class="highlight-keyword">from</span> Rhino.Commands <span class="highlight-keyword">import</span> Result
<span class="highlight-keyword">from</span> Rhino.DocObjects <span class="highlight-keyword">import</span> ObjectType
<span class="highlight-keyword">import</span> rhinoscriptsyntax <span class="highlight-keyword">as</span> rs
<span class="highlight-keyword">from</span> scriptcontext <span class="highlight-keyword">import</span> doc

<span class="highlight-keyword">def</span> RunCommand():
  rc, objRef = RhinoGet.GetOneObject(<span class="highlight-literal">"Select surface or polysurface to mesh"</span>, True, 
                                     ObjectType.Surface | ObjectType.PolysrfFilter)
  <span class="highlight-keyword">if</span> rc &lt;&gt; Result.Success:
    <span class="highlight-keyword">return</span> rc
  brep = objRef.Brep()
  <span class="highlight-keyword">if</span> None == brep:
    <span class="highlight-keyword">return</span> Result.Failure

  jaggedAndFaster = MeshingParameters.Coarse
  smoothAndSlower = MeshingParameters.Smooth
  defaultMeshParams = MeshingParameters.Default
  minimal = MeshingParameters.Minimal

  meshes = Mesh.CreateFromBrep(brep, smoothAndSlower)
  <span class="highlight-keyword">if</span> meshes == None <span class="highlight-keyword">or</span> meshes.Length == <span class="highlight-number">0</span>:
    <span class="highlight-keyword">return</span> Result.Failure

  brepMesh = Mesh()
  <span class="highlight-keyword">for</span> mesh <span class="highlight-keyword">in</span> meshes:
    brepMesh.Append(mesh)
  doc.Objects.AddMesh(brepMesh)
  doc.Views.Redraw()

<span class="highlight-keyword">if</span> __name__ == <span class="highlight-literal">"__main__"</span>:
  RunCommand()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAABBA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_Geometry_MeshingParameters.htm">MeshingParameters Class</a></div><div class="seeAlsoStyle"><a href="N_Rhino_Geometry.htm">Rhino.Geometry Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Rhino 7.16.22067.13000 (Last updated: 3/10/2022)<br />Copyright © 2009-2022 Robert McNeel &amp; Associates<p><a href="https://discourse.mcneel.com/c/rhino-developer" target="_blank">Report wishes and bugs at discourse.mcneel.com</a></p> </div></body></html>