<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>SubDCreationOptions Properties</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="SubDCreationOptions class, properties" /><meta name="Microsoft.Help.Id" content="Properties.T:Rhino.Geometry.SubDCreationOptions" /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Geometry" /><meta name="file" content="Properties_T_Rhino_Geometry_SubDCreationOptions" /><meta name="guid" content="Properties_T_Rhino_Geometry_SubDCreationOptions" /><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.3.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon API<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="RhinoCommon API" tocid="roottoc">RhinoCommon API</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="Namespaces" tocid="R_Project_RhinoCommon">Namespaces</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Rhino_Geometry.htm" title="Rhino.Geometry" tocid="N_Rhino_Geometry">Rhino.Geometry</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Rhino_Geometry_SubDCreationOptions.htm" title="SubDCreationOptions Class" tocid="T_Rhino_Geometry_SubDCreationOptions">SubDCreationOptions Class</a></div><div class="toclevel1 current" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Properties_T_Rhino_Geometry_SubDCreationOptions.htm" title="SubDCreationOptions Properties" tocid="Properties_T_Rhino_Geometry_SubDCreationOptions">SubDCreationOptions Properties</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_SubDCreationOptions_ConcaveCornerTest.htm" title="ConcaveCornerTest Property " tocid="P_Rhino_Geometry_SubDCreationOptions_ConcaveCornerTest">ConcaveCornerTest Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_SubDCreationOptions_ConvexCornersAndInteriorCreases.htm" title="ConvexCornersAndInteriorCreases Property " tocid="P_Rhino_Geometry_SubDCreationOptions_ConvexCornersAndInteriorCreases">ConvexCornersAndInteriorCreases Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_SubDCreationOptions_ConvexCornerTest.htm" title="ConvexCornerTest Property " tocid="P_Rhino_Geometry_SubDCreationOptions_ConvexCornerTest">ConvexCornerTest Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_SubDCreationOptions_InteriorCreases.htm" title="InteriorCreases Property " tocid="P_Rhino_Geometry_SubDCreationOptions_InteriorCreases">InteriorCreases Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_SubDCreationOptions_InteriorCreaseTest.htm" title="InteriorCreaseTest Property " tocid="P_Rhino_Geometry_SubDCreationOptions_InteriorCreaseTest">InteriorCreaseTest Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_SubDCreationOptions_InterpolateMeshVertices.htm" title="InterpolateMeshVertices Property " tocid="P_Rhino_Geometry_SubDCreationOptions_InterpolateMeshVertices">InterpolateMeshVertices Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_SubDCreationOptions_MaximumConvexCornerAngleRadians.htm" title="MaximumConvexCornerAngleRadians Property " tocid="P_Rhino_Geometry_SubDCreationOptions_MaximumConvexCornerAngleRadians">MaximumConvexCornerAngleRadians Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_SubDCreationOptions_MaximumConvexCornerEdgeCount.htm" title="MaximumConvexCornerEdgeCount Property " tocid="P_Rhino_Geometry_SubDCreationOptions_MaximumConvexCornerEdgeCount">MaximumConvexCornerEdgeCount Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_SubDCreationOptions_MinimumConcaveCornerAngleRadians.htm" title="MinimumConcaveCornerAngleRadians Property " tocid="P_Rhino_Geometry_SubDCreationOptions_MinimumConcaveCornerAngleRadians">MinimumConcaveCornerAngleRadians Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_SubDCreationOptions_MinimumConcaveCornerEdgeCount.htm" title="MinimumConcaveCornerEdgeCount Property " tocid="P_Rhino_Geometry_SubDCreationOptions_MinimumConcaveCornerEdgeCount">MinimumConcaveCornerEdgeCount Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_SubDCreationOptions_Smooth.htm" title="Smooth Property " tocid="P_Rhino_Geometry_SubDCreationOptions_Smooth">Smooth Property </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn"><h1>SubDCreationOptions Properties</h1></td></tr></table><span class="introStyle"></span> <p>The <a href="T_Rhino_Geometry_SubDCreationOptions.htm">SubDCreationOptions</a> type exposes the following members.</p><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID0RB')" onkeypress="SectionExpandCollapse_CheckKey('ID0RB', event)" tabindex="0"><img id="ID0RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Properties</span></div><div id="ID0RBSection" class="collapsibleSection"><table class="members" id="propertyList"><tr><th class="iconColumn">
								 
							</th><th>Name</th><th>Description</th></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_SubDCreationOptions_ConcaveCornerTest.htm">ConcaveCornerTest</a></td><td><div class="summary">
            Get or sets the concave corner test option.
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="../icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="P_Rhino_Geometry_SubDCreationOptions_ConvexCornersAndInteriorCreases.htm">ConvexCornersAndInteriorCreases</a></td><td><div class="summary">
            Look for convex corners at sub-D vertices with 2 edges that have an
            included angle &lt;= 90 degrees.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_SubDCreationOptions_ConvexCornerTest.htm">ConvexCornerTest</a></td><td><div class="summary">
            Get or sets the convex corner test option.
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="../icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="P_Rhino_Geometry_SubDCreationOptions_InteriorCreases.htm">InteriorCreases</a></td><td><div class="summary">
            Create an interior sub-D crease along all input mesh double edges
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_SubDCreationOptions_InteriorCreaseTest.htm">InteriorCreaseTest</a></td><td><div class="summary">
            Get or sets the interior crease test option.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_SubDCreationOptions_InterpolateMeshVertices.htm">InterpolateMeshVertices</a></td><td><div class="summary">
            If false, input mesh vertex locations will be used to set SubD vertex control net locations.
            If true, input mesh vertex locations will be used to set SubD vertex limit surface locations.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_SubDCreationOptions_MaximumConvexCornerAngleRadians.htm">MaximumConvexCornerAngleRadians</a></td><td><div class="summary">
            If ConvexCornerTest == ConvexCornerOption.AtMeshCorner, then an input mesh boundary
            vertex becomes a SubD corner when the number of edges that end at the
            vertex is &lt;= MaximumConvexCornerEdgeCount edges and the corner angle
            is &lt;= MaximumConvexCornerAngleRadians.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_SubDCreationOptions_MaximumConvexCornerEdgeCount.htm">MaximumConvexCornerEdgeCount</a></td><td><div class="summary">
            If ConvexCornerTest == ConvexCornerOption.AtMeshCorner, then an input mesh boundary
            vertex becomes a SubD corner when the number of edges that end at the
            vertex is &lt;= MaximumConvexCornerEdgeCount edges and the corner angle
            is &lt;= MaximumConvexCornerAngleRadians.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_SubDCreationOptions_MinimumConcaveCornerAngleRadians.htm">MinimumConcaveCornerAngleRadians</a></td><td><div class="summary">
            If ConcaveCornerTest == ConcaveCornerOption.AtMeshCorner, then an
            input mesh boundary vertex becomes a SubD corner when the number of
            edges that end at the vertex is &gt;= MinimumConcaveCornerEdgeCount edges
            and the corner angle is &gt;= MinimumConcaveCornerAngleRadians.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_SubDCreationOptions_MinimumConcaveCornerEdgeCount.htm">MinimumConcaveCornerEdgeCount</a></td><td><div class="summary">
            If ConcaveCornerTest == ConcaveCornerOption.AtMeshCorner, then an
            input mesh boundary vertex becomes a SubD corner when the number of
            edges that end at the vertex is &gt;= MinimumConcaveCornerEdgeCount edges
            and the corner angle is &gt;= MinimumConcaveCornerAngleRadians.
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="../icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="P_Rhino_Geometry_SubDCreationOptions_Smooth.htm">Smooth</a></td><td><div class="summary">
            No interior creases and no corners.
            </div></td></tr></table><a href="#PageHeader">Top</a></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID1RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_Geometry_SubDCreationOptions.htm">SubDCreationOptions Class</a></div><div class="seeAlsoStyle"><a href="N_Rhino_Geometry.htm">Rhino.Geometry Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Rhino 7.17.22102.05000 (Last updated: 4/21/2022)<br />Copyright © 2009-2022 Robert McNeel &amp; Associates<p><a href="https://discourse.mcneel.com/c/rhino-developer" target="_blank">Report wishes and bugs at discourse.mcneel.com</a></p> </div></body></html>