<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Arc Properties</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="Arc structure, properties" /><meta name="Microsoft.Help.Id" content="Properties.T:Rhino.Geometry.Arc" /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Geometry" /><meta name="file" content="Properties_T_Rhino_Geometry_Arc" /><meta name="guid" content="Properties_T_Rhino_Geometry_Arc" /><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.3.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon API<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="RhinoCommon API" tocid="roottoc">RhinoCommon API</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="Namespaces" tocid="R_Project_RhinoCommon">Namespaces</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Rhino_Geometry.htm" title="Rhino.Geometry" tocid="N_Rhino_Geometry">Rhino.Geometry</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Rhino_Geometry_Arc.htm" title="Arc Structure" tocid="T_Rhino_Geometry_Arc">Arc Structure</a></div><div class="toclevel1 current" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Properties_T_Rhino_Geometry_Arc.htm" title="Arc Properties" tocid="Properties_T_Rhino_Geometry_Arc">Arc Properties</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_Angle.htm" title="Angle Property " tocid="P_Rhino_Geometry_Arc_Angle">Angle Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_AngleDegrees.htm" title="AngleDegrees Property " tocid="P_Rhino_Geometry_Arc_AngleDegrees">AngleDegrees Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_AngleDomain.htm" title="AngleDomain Property " tocid="P_Rhino_Geometry_Arc_AngleDomain">AngleDomain Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_Center.htm" title="Center Property " tocid="P_Rhino_Geometry_Arc_Center">Center Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_Circumference.htm" title="Circumference Property " tocid="P_Rhino_Geometry_Arc_Circumference">Circumference Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_Diameter.htm" title="Diameter Property " tocid="P_Rhino_Geometry_Arc_Diameter">Diameter Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_EndAngle.htm" title="EndAngle Property " tocid="P_Rhino_Geometry_Arc_EndAngle">EndAngle Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_EndAngleDegrees.htm" title="EndAngleDegrees Property " tocid="P_Rhino_Geometry_Arc_EndAngleDegrees">EndAngleDegrees Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_EndPoint.htm" title="EndPoint Property " tocid="P_Rhino_Geometry_Arc_EndPoint">EndPoint Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_IsCircle.htm" title="IsCircle Property " tocid="P_Rhino_Geometry_Arc_IsCircle">IsCircle Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_IsValid.htm" title="IsValid Property " tocid="P_Rhino_Geometry_Arc_IsValid">IsValid Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_Length.htm" title="Length Property " tocid="P_Rhino_Geometry_Arc_Length">Length Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_MidPoint.htm" title="MidPoint Property " tocid="P_Rhino_Geometry_Arc_MidPoint">MidPoint Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_Plane.htm" title="Plane Property " tocid="P_Rhino_Geometry_Arc_Plane">Plane Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_Radius.htm" title="Radius Property " tocid="P_Rhino_Geometry_Arc_Radius">Radius Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_StartAngle.htm" title="StartAngle Property " tocid="P_Rhino_Geometry_Arc_StartAngle">StartAngle Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_StartAngleDegrees.htm" title="StartAngleDegrees Property " tocid="P_Rhino_Geometry_Arc_StartAngleDegrees">StartAngleDegrees Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_StartPoint.htm" title="StartPoint Property " tocid="P_Rhino_Geometry_Arc_StartPoint">StartPoint Property </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="../html/P_Rhino_Geometry_Arc_Unset.htm" title="Unset Property " tocid="P_Rhino_Geometry_Arc_Unset">Unset Property </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn"><h1>Arc Properties</h1></td></tr></table><span class="introStyle"></span> <p>The <a href="T_Rhino_Geometry_Arc.htm">Arc</a> type exposes the following members.</p><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID0RB')" onkeypress="SectionExpandCollapse_CheckKey('ID0RB', event)" tabindex="0"><img id="ID0RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Properties</span></div><div id="ID0RBSection" class="collapsibleSection"><table class="members" id="propertyList"><tr><th class="iconColumn">
								 
							</th><th>Name</th><th>Description</th></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_Angle.htm">Angle</a></td><td><div class="summary">
            Gets or sets the sweep -or subtended- angle (in Radians) for this arc segment.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_AngleDegrees.htm">AngleDegrees</a></td><td><div class="summary">
            Gets or sets the sweep -or subtended- angle (in Radians) for this arc segment.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_AngleDomain.htm">AngleDomain</a></td><td><div class="summary">
            Gets or sets the angle domain (in Radians) of this arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_Center.htm">Center</a></td><td><div class="summary">
            Gets or sets the center point for this arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_Circumference.htm">Circumference</a></td><td><div class="summary">
            Gets the circumference of the circle that is coincident with this arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_Diameter.htm">Diameter</a></td><td><div class="summary">
            Gets or sets the Diameter of this arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_EndAngle.htm">EndAngle</a></td><td><div class="summary">
            Gets or sets the end angle (in Radians) for this arc segment.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_EndAngleDegrees.htm">EndAngleDegrees</a></td><td><div class="summary">
            Gets or sets the end angle (in Radians) for this arc segment.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_EndPoint.htm">EndPoint</a></td><td><div class="summary">
            Gets the end point of the arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_IsCircle.htm">IsCircle</a></td><td><div class="summary">
            Gets a value indicating whether or not this arc is a complete circle.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_IsValid.htm">IsValid</a></td><td><div class="summary">
            Gets a value indicating whether or not this arc is valid.
            Detail:
             Radius&gt;0 and 0&lt;AngleRadians()&lt;=2*Math.Pi.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_Length.htm">Length</a></td><td><div class="summary">
            Gets the length of the arc. (Length = Radius * (subtended angle in radians)).
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_MidPoint.htm">MidPoint</a></td><td><div class="summary">
            Gets the mid-point of the arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_Plane.htm">Plane</a></td><td><div class="summary">
            Gets or sets the plane in which this arc lies.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_Radius.htm">Radius</a></td><td><div class="summary">
            Gets or sets the radius of this arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_StartAngle.htm">StartAngle</a></td><td><div class="summary">
            Gets or sets the start angle (in Radians) for this arc segment.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_StartAngleDegrees.htm">StartAngleDegrees</a></td><td><div class="summary">
            Gets or sets the start angle (in Radians) for this arc segment.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_StartPoint.htm">StartPoint</a></td><td><div class="summary">
            Gets the start point of the arc.
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="../icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="P_Rhino_Geometry_Arc_Unset.htm">Unset</a></td><td><div class="summary">
            Gets an Arc with Unset components.
            </div></td></tr></table><a href="#PageHeader">Top</a></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID1RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_Geometry_Arc.htm">Arc Structure</a></div><div class="seeAlsoStyle"><a href="N_Rhino_Geometry.htm">Rhino.Geometry Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Rhino 7.16.22067.13000 (Last updated: 3/10/2022)<br />Copyright © 2009-2022 Robert McNeel &amp; Associates<p><a href="https://discourse.mcneel.com/c/rhino-developer" target="_blank">Report wishes and bugs at discourse.mcneel.com</a></p> </div></body></html>