<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Arc Structure</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="Arc structure" /><meta name="System.Keywords" content="Rhino.Geometry.Arc structure" /><meta name="Microsoft.Help.F1" content="Rhino.Geometry.Arc" /><meta name="Microsoft.Help.Id" content="T:Rhino.Geometry.Arc" /><meta name="Description" content="Represents the value of a plane, two angles and a radius in a sub-curve of a three-dimensional circle. The curve is parameterized by an angle expressed in radians." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Geometry" /><meta name="file" content="T_Rhino_Geometry_Arc" /><meta name="guid" content="T_Rhino_Geometry_Arc" /><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-3.3.1.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script><script type="text/javascript" src="../scripts/clipboard.min.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon API<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="RhinoCommon API" tocid="roottoc">RhinoCommon API</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/R_Project_RhinoCommon.htm" title="Namespaces" tocid="R_Project_RhinoCommon">Namespaces</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/N_Rhino_Geometry.htm" title="Rhino.Geometry" tocid="N_Rhino_Geometry">Rhino.Geometry</a></div><div class="toclevel1 current" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/T_Rhino_Geometry_Arc.htm" title="Arc Structure" tocid="T_Rhino_Geometry_Arc">Arc Structure</a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Overload_Rhino_Geometry_Arc__ctor.htm" title="Arc Constructor " tocid="Overload_Rhino_Geometry_Arc__ctor">Arc Constructor </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Properties_T_Rhino_Geometry_Arc.htm" title="Arc Properties" tocid="Properties_T_Rhino_Geometry_Arc">Arc Properties</a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Methods_T_Rhino_Geometry_Arc.htm" title="Arc Methods" tocid="Methods_T_Rhino_Geometry_Arc">Arc Methods</a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="../html/Operators_T_Rhino_Geometry_Arc.htm" title="Arc Operators" tocid="Operators_T_Rhino_Geometry_Arc">Arc Operators</a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn"><h1>Arc Structure</h1></td></tr></table><span class="introStyle"></span> <div class="summary">
            Represents the value of a plane, two angles and a radius in
            a sub-curve of a three-dimensional circle.
            
            <p>The curve is parameterized by an angle expressed in radians. For an IsValid arc
            the total subtended angle AngleRadians() = Domain()(1) - Domain()(0) must satisfy
            0 &lt; AngleRadians() &lt; 2*Pi</p><p>The parameterization of the Arc is inherited from the Circle it is derived from.
            In particular</p><p>t -&gt; center + cos(t)*radius*xaxis + sin(t)*radius*yaxis</p><p>where xaxis and yaxis, (part of Circle.Plane) form an orthonormal frame of the plane
            containing the circle.</p></div><p> </p>
    <strong>Namespace:</strong> 
   <a href="N_Rhino_Geometry.htm">Rhino.Geometry</a><br />
    <strong>Assembly:</strong>
   RhinoCommon (in RhinoCommon.dll)<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" class="copyCodeSnippet" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve">[<span class="identifier">SerializableAttribute</span>]
<span class="keyword">public</span> <span class="keyword">struct</span> <span class="identifier">Arc</span> : <span class="identifier">IEquatable</span>&lt;<span class="identifier">Arc</span>&gt;, <span class="identifier">IEpsilonComparable</span>&lt;<span class="identifier">Arc</span>&gt;, 
	<span class="identifier">ICloneable</span></pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve">&lt;<span class="identifier">SerializableAttribute</span>&gt;
<span class="keyword">Public</span> <span class="keyword">Structure</span> <span class="identifier">Arc</span>
	<span class="keyword">Implements</span> <span class="identifier">IEquatable</span>(<span class="keyword">Of</span> <span class="identifier">Arc</span>), <span class="identifier">IEpsilonComparable</span>(<span class="keyword">Of</span> <span class="identifier">Arc</span>), 
	<span class="identifier">ICloneable</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script></div><p>The <span class="selflink">Arc</span> type exposes the following members.</p><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Constructors</span></div><div id="ID2RBSection" class="collapsibleSection"><table class="members" id="constructorList"><tr><th class="iconColumn">
								 
							</th><th>Name</th><th>Description</th></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc__ctor.htm">Arc(Circle, Interval)</a></td><td><div class="summary">
            Initializes a new instance of an arc from a base circle and an interval of angles.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc__ctor_1.htm">Arc(Circle, Double)</a></td><td><div class="summary">
            Initializes a new instance of an arc from a base circle and an angle.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc__ctor_3.htm">Arc(Plane, Double, Double)</a></td><td><div class="summary">
            Initializes a new arc from a base plane, a radius value and an angle.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc__ctor_4.htm">Arc(Point3d, Point3d, Point3d)</a></td><td><div class="summary">
            Initializes a new arc through three points. If the points are coincident 
            or co-linear, this will result in an Invalid arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc__ctor_5.htm">Arc(Point3d, Vector3d, Point3d)</a></td><td><div class="summary">
            Initializes a new arc from end points and a tangent vector. 
            If the tangent is parallel with the endpoints this will result in an Invalid arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc__ctor_6.htm">Arc(Point3d, Double, Double)</a></td><td><div class="summary">
            Initializes a new horizontal arc at the given center point, with a custom radius and angle.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc__ctor_2.htm">Arc(Plane, Point3d, Double, Double)</a></td><td><div class="summary">
            Initializes a new aligned arc at the given center point, with a custom radius and angle.
            </div></td></tr></table><a href="#PageHeader">Top</a></div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Properties</span></div><div id="ID3RBSection" class="collapsibleSection"><table class="members" id="propertyList"><tr><th class="iconColumn">
								 
							</th><th>Name</th><th>Description</th></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_Angle.htm">Angle</a></td><td><div class="summary">
            Gets or sets the sweep -or subtended- angle (in Radians) for this arc segment.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_AngleDegrees.htm">AngleDegrees</a></td><td><div class="summary">
            Gets or sets the sweep -or subtended- angle (in Radians) for this arc segment.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_AngleDomain.htm">AngleDomain</a></td><td><div class="summary">
            Gets or sets the angle domain (in Radians) of this arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_Center.htm">Center</a></td><td><div class="summary">
            Gets or sets the center point for this arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_Circumference.htm">Circumference</a></td><td><div class="summary">
            Gets the circumference of the circle that is coincident with this arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_Diameter.htm">Diameter</a></td><td><div class="summary">
            Gets or sets the Diameter of this arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_EndAngle.htm">EndAngle</a></td><td><div class="summary">
            Gets or sets the end angle (in Radians) for this arc segment.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_EndAngleDegrees.htm">EndAngleDegrees</a></td><td><div class="summary">
            Gets or sets the end angle (in Radians) for this arc segment.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_EndPoint.htm">EndPoint</a></td><td><div class="summary">
            Gets the end point of the arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_IsCircle.htm">IsCircle</a></td><td><div class="summary">
            Gets a value indicating whether or not this arc is a complete circle.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_IsValid.htm">IsValid</a></td><td><div class="summary">
            Gets a value indicating whether or not this arc is valid.
            Detail:
             Radius&gt;0 and 0&lt;AngleRadians()&lt;=2*Math.Pi.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_Length.htm">Length</a></td><td><div class="summary">
            Gets the length of the arc. (Length = Radius * (subtended angle in radians)).
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_MidPoint.htm">MidPoint</a></td><td><div class="summary">
            Gets the mid-point of the arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_Plane.htm">Plane</a></td><td><div class="summary">
            Gets or sets the plane in which this arc lies.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_Radius.htm">Radius</a></td><td><div class="summary">
            Gets or sets the radius of this arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_StartAngle.htm">StartAngle</a></td><td><div class="summary">
            Gets or sets the start angle (in Radians) for this arc segment.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_StartAngleDegrees.htm">StartAngleDegrees</a></td><td><div class="summary">
            Gets or sets the start angle (in Radians) for this arc segment.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="P_Rhino_Geometry_Arc_StartPoint.htm">StartPoint</a></td><td><div class="summary">
            Gets the start point of the arc.
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="../icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="P_Rhino_Geometry_Arc_Unset.htm">Unset</a></td><td><div class="summary">
            Gets an Arc with Unset components.
            </div></td></tr></table><a href="#PageHeader">Top</a></div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID4RB')" onkeypress="SectionExpandCollapse_CheckKey('ID4RB', event)" tabindex="0"><img id="ID4RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Methods</span></div><div id="ID4RBSection" class="collapsibleSection"><table class="members" id="methodList"><tr><th class="iconColumn">
								 
							</th><th>Name</th><th>Description</th></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc_BoundingBox.htm">BoundingBox</a></td><td><div class="summary">
            Computes the 3D axis aligned bounding box for this arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc_ClosestParameter.htm">ClosestParameter</a></td><td><div class="summary">
            Gets parameter on the arc closest to a test point.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc_ClosestPoint.htm">ClosestPoint</a></td><td><div class="summary">
            Computes the point on an arc that is closest to a test point.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc_EpsilonEquals.htm">EpsilonEquals</a></td><td><div class="summary">
            Check that all values in other are within epsilon of the values in this
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc_Equals_1.htm">Equals(Object)</a></td><td><div class="summary">
            Determines whether another object is an arc and has the same value as this arc.
            </div> (Overrides <a href="https://docs.microsoft.com/dotnet/api/system.valuetype.equals#System_ValueType_Equals_System_Object_" target="_blank">ValueType<span id="LST11BA45D2_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST11BA45D2_0?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Equals(Object)</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc_Equals.htm">Equals(Arc)</a></td><td><div class="summary">
            Determines whether another arc has the same value as this arc.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc_GetHashCode.htm">GetHashCode</a></td><td><div class="summary">
            Computes a hash code for the present arc.
            </div> (Overrides <a href="https://docs.microsoft.com/dotnet/api/system.valuetype.gethashcode#System_ValueType_GetHashCode" target="_blank">ValueType<span id="LST11BA45D2_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST11BA45D2_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>GetHashCode<span id="LST11BA45D2_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST11BA45D2_2?cs=()|vb=|cpp=()|nu=()|fs=()");</script></a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="https://docs.microsoft.com/dotnet/api/system.object.gettype#System_Object_GetType" target="_blank">GetType</a></td><td><div class="summary">Gets the <a href="https://docs.microsoft.com/dotnet/api/system.type" target="_blank">Type</a> of the current instance.</div> (Inherited from <a href="https://docs.microsoft.com/dotnet/api/system.object" target="_blank">Object</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc_PointAt.htm">PointAt</a></td><td><div class="summary">
            Gets the point at the given arc parameter.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc_Reverse.htm">Reverse</a></td><td><div class="summary">
            Reverses the orientation of the arc. Changes the domain from [a,b]
            to [-b,-a].
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc_TangentAt.htm">TangentAt</a></td><td><div class="summary">
            Gets the tangent at the given parameter.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc_ToNurbsCurve.htm">ToNurbsCurve<span id="LST11BA45D2_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST11BA45D2_3?cs=()|vb=|cpp=()|nu=()|fs=()");</script></a></td><td><div class="summary">
            Initializes a nurbs curve representation of this arc. 
            This amounts to the same as calling NurbsCurve.CreateFromArc().
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc_ToNurbsCurve_1.htm">ToNurbsCurve(Int32, Int32)</a></td><td><div class="summary">
            Create a uniform non-rational cubic NURBS approximation of an arc.
            </div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="https://docs.microsoft.com/dotnet/api/system.valuetype.tostring#System_ValueType_ToString" target="_blank">ToString</a></td><td><div class="summary">Returns the fully qualified type name of this instance.</div> (Inherited from <a href="https://docs.microsoft.com/dotnet/api/system.valuetype" target="_blank">ValueType</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc_Transform.htm">Transform</a></td><td><div class="summary">
            Transforms the arc using a Transformation matrix.
            </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="../icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="M_Rhino_Geometry_Arc_Trim.htm">Trim</a></td><td><div class="summary">
            Sets arc's angle domain (in radians) as a sub-domain of the circle.
            </div></td></tr></table><a href="#PageHeader">Top</a></div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID5RB')" onkeypress="SectionExpandCollapse_CheckKey('ID5RB', event)" tabindex="0"><img id="ID5RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Operators</span></div><div id="ID5RBSection" class="collapsibleSection"><table class="members" id="operatorList"><tr><th class="iconColumn">
								 
							</th><th>Name</th><th>Description</th></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/puboperator.gif" alt="Public operator" title="Public operator" /><img src="../icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="M_Rhino_Geometry_Arc_op_Equality.htm">Equality</a></td><td><div class="summary">
            Determines whether two arcs have equal values.
            </div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="../icons/puboperator.gif" alt="Public operator" title="Public operator" /><img src="../icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="M_Rhino_Geometry_Arc_op_Inequality.htm">Inequality</a></td><td><div class="summary">
            Determines whether two arcs have different values.
            </div></td></tr></table><a href="#PageHeader">Top</a></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID6RB')" onkeypress="SectionExpandCollapse_CheckKey('ID6RB', event)" tabindex="0"><img id="ID6RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID6RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="N_Rhino_Geometry.htm">Rhino.Geometry Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Rhino 7.16.22067.13000 (Last updated: 3/10/2022)<br />Copyright © 2009-2022 Robert McNeel &amp; Associates<p><a href="https://discourse.mcneel.com/c/rhino-developer" target="_blank">Report wishes and bugs at discourse.mcneel.com</a></p> </div></body></html>